**BANGALORE CARS DATA**

In [1]:
# importing libraries
import pandas as pd
import ast

In [2]:
path = r"C:/Users/jagadesh/Documents/Python Scripts/car dekho - used car prediction/unstructured_files/bangalore_cars.xlsx"
data_b = pd.read_excel(path)

In [3]:
data_b

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [4]:
data_b.drop(columns=["car_links"], inplace=True, axis=1)

In [5]:
data_b.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."

**new_car_detail**

In [6]:
#view new_car_detail
data_b["new_car_detail"]

0       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
4       {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
                              ...
1476    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1477    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1478    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1479    {'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...
1480    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
Name: new_car_detail, Length: 1481, dtype: object

In [7]:
data_b["new_car_detail"][0]

"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', 'km': '1,20,000', 'transmission': 'Manual', 'ownerNo': 3, 'owner': '3rd Owner', 'oem': 'Maruti', 'model': 'Maruti Celerio', 'modelYear': 2015, 'centralVariantId': 3979, 'variantName': 'VXI', 'price': 'â‚¹ 4 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

In [8]:
#convert string to dict by using abstract syntax trees
data_b["new_car_detail_dict"]= data_b["new_car_detail"].apply(ast.literal_eval)
data_b["new_car_detail_dict"]

0       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
4       {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
                              ...
1476    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1477    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1478    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1479    {'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...
1480    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
Name: new_car_detail_dict, Length: 1481, dtype: object

In [9]:
data_b["new_car_detail_dict"][0]

{'it': 0,
 'ft': 'Petrol',
 'bt': 'Hatchback',
 'km': '1,20,000',
 'transmission': 'Manual',
 'ownerNo': 3,
 'owner': '3rd Owner',
 'oem': 'Maruti',
 'model': 'Maruti Celerio',
 'modelYear': 2015,
 'centralVariantId': 3979,
 'variantName': 'VXI',
 'price': 'â‚¹ 4 Lakh',
 'priceActual': '',
 'priceSaving': '',
 'priceFixedText': None,
 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg',
  'heading': 'Trending Car!',
  'desc': 'High chances of sale in next 6 days'}}

In [10]:
data_b

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,new_car_detail_dict
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':..."
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '..."
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '..."
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':..."
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '..."
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '..."
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...","{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '..."

In [11]:
#flatten the nested dict to dataframe
new_car_detail_b = pd.json_normalize(data_b["new_car_detail_dict"])
new_car_detail_b

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,â‚¹ 5.85 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,â‚¹ 4.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,â‚¹ 7.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,2253,4x4 MT,â‚¹ 16.49 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,4257,Zxi BSIII,â‚¹ 3.30 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,1188,S MT,â‚¹ 4.25 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,5695,1.4 Asta Dual Tone,â‚¹ 7.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,1523,Asta Option AT,â‚¹ 6.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

***new_car_overview***

In [12]:
#view new_car_overview
data_b["new_car_overview"]

0       {'heading': 'Car overview', 'top': [{'key': 'R...
1       {'heading': 'Car overview', 'top': [{'key': 'R...
2       {'heading': 'Car overview', 'top': [{'key': 'R...
3       {'heading': 'Car overview', 'top': [{'key': 'R...
4       {'heading': 'Car overview', 'top': [{'key': 'R...
                              ...
1476    {'heading': 'Car overview', 'top': [{'key': 'R...
1477    {'heading': 'Car overview', 'top': [{'key': 'R...
1478    {'heading': 'Car overview', 'top': [{'key': 'R...
1479    {'heading': 'Car overview', 'top': [{'key': 'R...
1480    {'heading': 'Car overview', 'top': [{'key': 'R...
Name: new_car_overview, Length: 1481, dtype: object

In [13]:
data_b["new_car_overview"][0]

"{'heading': 'Car overview', 'top': [{'key': 'Registration Year', 'value': '2015', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'}, {'key': 'Insurance Validity', 'value': 'Third Party insurance', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'}, {'key': 'Fuel Type', 'value': 'Petrol', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'}, {'key': 'Seats', 'value': '5 Seats', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'}, {'key': 'Kms Driven', 'value': '1,20,000 Kms', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'}, {'key': 'RTO', 'value': 'KA51', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'}, {'key': 'Ownership', 'value': 'Third Owner', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'}, {'key': 'Engine Displacement', 'value': '998 cc', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'}, {'key': 'Transmission', 'value': 'Manual', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'}, {'key': 'Year of Manufacture', 'value': 2015, 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}], 'bottomData': None}"

In [14]:
#convert string to dict using abstract syntax trees
data_b["new_car_overview_dict"]=data_b["new_car_overview"].apply(ast.literal_eval)
data_b["new_car_overview_dict"][0]

{'heading': 'Car overview',
 'top': [{'key': 'Registration Year',
   'value': '2015',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'},
  {'key': 'Insurance Validity',
   'value': 'Third Party insurance',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'},
  {'key': 'Fuel Type',
   'value': 'Petrol',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'},
  {'key': 'Seats',
   'value': '5 Seats',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'},
  {'key': 'Kms Driven',
   'value': '1,20,000 Kms',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'},
  {'key': 'RTO',
   'value': 'KA51',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'},
  {'key': 'Ownership',
   'value': 'Third Owner',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'},
  {'key': 'Engine Displacement',
   'value': '998 cc',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'},
  {'key': 'Transmission',
   'value': 'Manual',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'},
  {'key': 'Year of Manufacture',
   'value': 2015,
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}],
 'bottomData': None}

In [15]:
#flatten the nested dict to dataframe
new_car_overview_b = pd.json_normalize(data_b["new_car_overview_dict"])
new_car_overview_b

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': 'Sept 2...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
...,...,...,...
1476,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None
1477,Car overview,"[{'key': 'Registration Year', 'value': 'Jun 20...",None
1478,Car overview,"[{'key': 'Registration Year', 'value': 'Sept 2...",None
1479,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
1480,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None

In [16]:
#drop column from dataframe
new_car_overview_b.drop(columns=["bottomData"], inplace=True, axis=1)
new_car_overview_b

           heading                                                top
0     Car overview  [{'key': 'Registration Year', 'value': '2015',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
2     Car overview  [{'key': 'Registration Year', 'value': 'Sept 2...
3     Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2015',...
...            ...                                                ...
1476  Car overview  [{'key': 'Registration Year', 'value': 'May 20...
1477  Car overview  [{'key': 'Registration Year', 'value': 'Jun 20...
1478  Car overview  [{'key': 'Registration Year', 'value': 'Sept 2...
1479  Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
1480  Car overview  [{'key': 'Registration Year', 'value': 'May 20...

[1481 rows x 2 columns]

In [17]:
new_car_overview_b["top"][0]

[{'key': 'Registration Year',
  'value': '2015',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'},
 {'key': 'Insurance Validity',
  'value': 'Third Party insurance',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'},
 {'key': 'Fuel Type',
  'value': 'Petrol',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'},
 {'key': 'Seats',
  'value': '5 Seats',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'},
 {'key': 'Kms Driven',
  'value': '1,20,000 Kms',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'},
 {'key': 'RTO',
  'value': 'KA51',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'},
 {'key': 'Ownership',
  'value': 'Third Owner',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'},
 {'key': 'Engine Displacement',
  'value': '998 cc',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'},
 {'key': 'Transmission',
  'value': 'Manual',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'},
 {'key': 'Year of Manufacture',
  'value': 2015,
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}]

In [18]:
# function to get key and value in separate dict
def extract_key_value_dicts(details):
    if isinstance(details, list):
        return {df['key']:df['value'] for df in details}
    else:
        return {}

In [19]:
#apply function to all values in top column
new_car_overview = new_car_overview_b['top'].apply(extract_key_value_dicts)
new_car_overview

0       {'Registration Year': '2015', 'Insurance Valid...
1       {'Registration Year': 'Feb 2018', 'Insurance V...
2       {'Registration Year': 'Sept 2018', 'Insurance ...
3       {'Registration Year': 'Dec 2014', 'Insurance V...
4       {'Registration Year': '2015', 'Insurance Valid...
                              ...
1476    {'Registration Year': 'May 2012', 'Insurance V...
1477    {'Registration Year': 'Jun 2008', 'Insurance V...
1478    {'Registration Year': 'Sept 2014', 'Insurance ...
1479    {'Registration Year': 'Dec 2018', 'Insurance V...
1480    {'Registration Year': 'May 2017', 'Insurance V...
Name: top, Length: 1481, dtype: object

In [20]:
new_car_overview_blr = pd.json_normalize(new_car_overview)
new_car_overview_blr

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2015,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",KA51,Third Owner,998 cc,Manual,2015.0
1,Feb 2018,Comprehensive,Petrol,5 Seats,"32,706 Kms",KA05,Second Owner,1497 cc,Manual,2018.0
2,Sept 2018,Comprehensive,Petrol,5 Seats,"11,949 Kms",KA03,First Owner,1199 cc,Manual,2018.0
3,Dec 2014,Comprehensive,Petrol,5 Seats,"17,794 Kms",KA53,First Owner,1197 cc,Manual,2014.0
4,2015,Third Party insurance,Diesel,5 Seats,"60,000 Kms",KA04,First Owner,1248 cc,Manual,2015.0
...,...,...,...,...,...,...,...,...,...,...
1476,May 2012,Comprehensive,Diesel,7 Seats,"1,56,039 Kms",KA01,Second Owner,2982 cc,Manual,2012.0
1477,Jun 2008,Third Party insurance,Petrol,5 Seats,"56,000 Kms",KA02,Second Owner,1586 cc,Manual,2008.0
1478,Sept 2014,Comprehensive,Petrol,5 Seats,"42,000 Kms",KA03,Second Owner,1198 cc,Manual,2014.0
1479,Dec 2018,Comprehensive,Diesel,5 Seats,"93,003 Kms",KA03,First Owner,1396 cc,Manual,2018.0
1480,May 2017,Comprehensive,Petrol,5 Seats,"36,000 Kms",KA04,Second Owner,1197 cc,Automatic,2017.0

## NEW_CAR_FEATURE

In [21]:
data_b["new_car_feature"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1476    {'heading': 'Features', 'top': [{'value': 'Pow...
1477    {'heading': 'Features', 'top': [{'value': 'Pow...
1478    {'heading': 'Features', 'top': [{'value': 'Pow...
1479    {'heading': 'Features', 'top': [{'value': 'Pow...
1480    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature, Length: 1481, dtype: object

In [22]:
data_b["new_car_feature"][0]

"{'heading': 'Features', 'top': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Head Lights'}, {'value': 'Manually Adjustable Exterior Rear View Mirror'}, {'value': 'Centeral Locking'}, {'value': 'Child Safety Locks'}], 'data': [{'heading': 'Comfort & Convenience', 'subHeading': 'Comfort', 'list': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Power Windows Rear'}, {'value': 'Remote Trunk Opener'}, {'value': 'Remote Fuel Lid Opener'}, {'value': 'Low Fuel Warning Light'}, {'value': 'Accessory Power Outlet'}, {'value': 'Vanity Mirror'}, {'value': 'Rear Seat Headrest'}, {'value': 'Cup Holders Front'}]}, {'heading': 'Interior', 'subHeading': 'Interior', 'list': [{'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Digital Odometer'}, {'value': 'Electronic Multi Tripmeter'}, {'value': 'Fabric Upholstery'}, {'value': 'Glove Compartment'}, {'value': 'Digital Clock'}]}, {'heading': 'Exterior', 'subHeading': 'Exterior', 'list': [{'value': 'Adjustable Head Lights'}, {'value': 'Manually Adjustable Exterior Rear View Mirror'}, {'value': 'Wheel Covers'}, {'value': 'Power Antenna'}, {'value': 'Chrome Grille'}]}, {'heading': 'Safety', 'subHeading': 'Safety', 'list': [{'value': 'Centeral Locking'}, {'value': 'Child Safety Locks'}, {'value': 'Day Night Rear View Mirror'}, {'value': 'Passenger Side Rear View Mirror'}, {'value': 'Halogen Headlamps'}, {'value': 'Rear Seat Belts'}, {'value': 'Door Ajar Warning'}, {'value': 'Side Impact Beams'}, {'value': 'Front Impact Beams'}, {'value': 'Adjustable Seats'}, {'value': 'Centrally Mounted Fuel Tank'}, {'value': 'Engine Immobilizer'}, {'value': 'Anti Theft Device'}]}], 'commonIcon': 'https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg'}"

In [23]:
data_b["new_car_feature_dict"] = data_b["new_car_feature"].apply(ast.literal_eval)

In [24]:
data_b["new_car_feature_dict"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1476    {'heading': 'Features', 'top': [{'value': 'Pow...
1477    {'heading': 'Features', 'top': [{'value': 'Pow...
1478    {'heading': 'Features', 'top': [{'value': 'Pow...
1479    {'heading': 'Features', 'top': [{'value': 'Pow...
1480    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature_dict, Length: 1481, dtype: object

In [25]:
#flatten the nested dict to dataframe
new_car_feature_b = pd.json_normalize(data_b["new_car_feature_dict"])
new_car_feature_b

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1476,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1477,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1478,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1479,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [26]:
#drop column from dataframe
new_car_feature_b.drop(columns=["commonIcon"], inplace=True, axis=1)
new_car_feature_b

,heading,top,data
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
...,...,...,...
1476,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1477,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1478,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1479,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."

In [27]:
new_car_feature_b["top"][0]

[{'value': 'Power Steering'},
 {'value': 'Power Windows Front'},
 {'value': 'Air Conditioner'},
 {'value': 'Heater'},
 {'value': 'Adjustable Head Lights'},
 {'value': 'Manually Adjustable Exterior Rear View Mirror'},
 {'value': 'Centeral Locking'},
 {'value': 'Child Safety Locks'}]

In [28]:
#function to get key and values in top column
def extract_key_value_dicts1(details_1):
    if isinstance(details_1, list):
        return {i: df["value"] for i, df in enumerate(details_1)}
    else:
        return{}

In [29]:
#apply function to all values in top column
new_car_feature = new_car_feature_b["top"].apply(extract_key_value_dicts1)

In [30]:
new_car_feature

0       {0: 'Power Steering', 1: 'Power Windows Front'...
1       {0: 'Power Steering', 1: 'Power Windows Front'...
2       {0: 'Power Steering', 1: 'Power Windows Front'...
3       {0: 'Power Steering', 1: 'Power Windows Front'...
4       {0: 'Power Steering', 1: 'Power Windows Front'...
                              ...
1476    {0: 'Power Steering', 1: 'Power Windows Front'...
1477    {0: 'Power Steering', 1: 'Power Windows Front'...
1478    {0: 'Power Steering', 1: 'Power Windows Front'...
1479    {0: 'Power Steering', 1: 'Power Windows Front'...
1480    {0: 'Power Steering', 1: 'Power Windows Front'...
Name: top, Length: 1481, dtype: object

In [31]:
new_car_feature_blr = pd.json_normalize(new_car_feature)
new_car_feature_blr

,0,1,2,3,4,5,6,7,8
0,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Centeral Locking,Child Safety Locks,NaN
1,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
2,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
3,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
4,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
...,...,...,...,...,...,...,...,...,...
1476,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player
1477,Power Steering,Power Windows Front,Air Conditioner,Heater,Fog Lights Front,Fog Lights Rear,Anti Lock Braking System,Brake Assist,Cd Player
1478,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Centeral Locking,Power Door Locks,Radio
1479,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
1480,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player

In [32]:
new_car_feature_b["data"][0]

[{'heading': 'Comfort & Convenience',
  'subHeading': 'Comfort',
  'list': [{'value': 'Power Steering'},
   {'value': 'Power Windows Front'},
   {'value': 'Power Windows Rear'},
   {'value': 'Remote Trunk Opener'},
   {'value': 'Remote Fuel Lid Opener'},
   {'value': 'Low Fuel Warning Light'},
   {'value': 'Accessory Power Outlet'},
   {'value': 'Vanity Mirror'},
   {'value': 'Rear Seat Headrest'},
   {'value': 'Cup Holders Front'}]},
 {'heading': 'Interior',
  'subHeading': 'Interior',
  'list': [{'value': 'Air Conditioner'},
   {'value': 'Heater'},
   {'value': 'Digital Odometer'},
   {'value': 'Electronic Multi Tripmeter'},
   {'value': 'Fabric Upholstery'},
   {'value': 'Glove Compartment'},
   {'value': 'Digital Clock'}]},
 {'heading': 'Exterior',
  'subHeading': 'Exterior',
  'list': [{'value': 'Adjustable Head Lights'},
   {'value': 'Manually Adjustable Exterior Rear View Mirror'},
   {'value': 'Wheel Covers'},
   {'value': 'Power Antenna'},
   {'value': 'Chrome Grille'}]},
 {'heading': 'Safety',
  'subHeading': 'Safety',
  'list': [{'value': 'Centeral Locking'},
   {'value': 'Child Safety Locks'},
   {'value': 'Day Night Rear View Mirror'},
   {'value': 'Passenger Side Rear View Mirror'},
   {'value': 'Halogen Headlamps'},
   {'value': 'Rear Seat Belts'},
   {'value': 'Door Ajar Warning'},
   {'value': 'Side Impact Beams'},
   {'value': 'Front Impact Beams'},
   {'value': 'Adjustable Seats'},
   {'value': 'Centrally Mounted Fuel Tank'},
   {'value': 'Engine Immobilizer'},
   {'value': 'Anti Theft Device'}]}]

In [33]:
#flatten the nested dict to dataframe
new_car_feature_cc=pd.json_normalize(new_car_feature_b["data"])
new_car_feature_cc

,0,1,2,3,4
0,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",None
1,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
2,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
3,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
4,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
...,...,...,...,...,...
1476,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1477,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1478,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1479,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1480,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."

In [34]:
#flatten the nested dict to dataframe = 'comfort & convenience'
new_car_feature_data_1=pd.json_normalize(new_car_feature_cc[0])
new_car_feature_data_1

,heading,subHeading,list
0,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
2,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
3,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
4,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
...,...,...,...
1476,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1477,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1478,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1479,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1480,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."

In [35]:
# apply function to all values in list column
new_car_feature_list_1= new_car_feature_data_1["list"].apply(extract_key_value_dicts1)

In [36]:
new_car_feature_list_1[0]

{0: 'Power Steering',
 1: 'Power Windows Front',
 2: 'Power Windows Rear',
 3: 'Remote Trunk Opener',
 4: 'Remote Fuel Lid Opener',
 5: 'Low Fuel Warning Light',
 6: 'Accessory Power Outlet',
 7: 'Vanity Mirror',
 8: 'Rear Seat Headrest',
 9: 'Cup Holders Front'}

In [37]:
new_car_feature_list_1=pd.json_normalize(new_car_feature_list_1)
new_car_feature_list_1

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
#flatten the nested dict to dataframe = 'interior'
new_car_feature_data_2 = pd.json_normalize(new_car_feature_cc[1])
new_car_feature_data_2

       heading subHeading                                               list
0     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
2     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
3     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
4     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
...        ...        ...                                                ...
1476  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1477  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1478  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1479  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1480  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...

[1481 rows x 3 columns]

In [39]:
new_car_feature_list_2 = new_car_feature_data_2["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2

0       {0: 'Air Conditioner', 1: 'Heater', 2: 'Digita...
1       {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
2       {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
3       {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
4       {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
                              ...
1476    {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
1477    {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
1478    {0: 'Air Conditioner', 1: 'Heater', 2: 'Digita...
1479    {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
1480    {0: 'Air Conditioner', 1: 'Heater', 2: 'Adjust...
Name: list, Length: 1481, dtype: object

In [40]:
new_car_feature_list_2 = pd.json_normalize(new_car_feature_list_2)
new_car_feature_list_2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Air Conditioner,Heater,Digital Odometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
1477,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,NaN,NaN,NaN,NaN
1478,Air Conditioner,Heater,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
1479,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,Dual Tone Dashboard,NaN,NaN,NaN,NaN,NaN
1480,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN

In [41]:
#flatten the nested dict to dataframe ='Exterior'
new_car_feature_data_3= pd.json_normalize(new_car_feature_cc[2])
new_car_feature_data_3

       heading subHeading                                               list
0     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
2     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
3     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
4     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
...        ...        ...                                                ...
1476  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1477  Exterior   Exterior  [{'value': 'Fog Lights Front'}, {'value': 'Fog...
1478  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1479  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1480  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...

[1481 rows x 3 columns]

In [42]:
# apply function to all values in list column
new_car_feature_list_3 = new_car_feature_data_3["list"].apply(extract_key_value_dicts1)
new_car_feature_list_3 = pd.json_normalize(new_car_feature_list_3)
new_car_feature_list_3

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Wheel Covers,Power Antenna,Chrome Grille,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Wheel Covers,Power Antenna,Tinted Glass,Rear Spoiler,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Alloy Wheels,Power Antenna,Outside Rear View Mirror Turn Indicators,Chrome Grille,Chrome Garnish,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Tinted Glass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Side Stepper,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Alloy Wheels,Tinted Glass,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Wheel Covers,Power Antenna,Chrome Grille,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Rear Spoiler,Outside Rear View Mirror Turn Indicators,Chrome Grille,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Tinted Glass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
#flatten the nested dict to dataframe  ='safety'
new_car_feature_data_4 = pd.json_normalize(new_car_feature_cc[3])
new_car_feature_data_4

     heading subHeading                                               list
0     Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Chi...
1     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
2     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
3     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
4     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
...      ...        ...                                                ...
1476  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1477  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1478  Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Pow...
1479  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1480  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...

[1481 rows x 3 columns]

In [44]:
#apply function to all values in list column
new_car_feature_list_4= new_car_feature_data_4["list"].apply(extract_key_value_dicts1)
new_car_feature_list_4

0       {0: 'Centeral Locking', 1: 'Child Safety Locks...
1       {0: 'Anti Lock Braking System', 1: 'Centeral L...
2       {0: 'Anti Lock Braking System', 1: 'Centeral L...
3       {0: 'Anti Lock Braking System', 1: 'Centeral L...
4       {0: 'Anti Lock Braking System', 1: 'Centeral L...
                              ...
1476    {0: 'Anti Lock Braking System', 1: 'Brake Assi...
1477    {0: 'Anti Lock Braking System', 1: 'Brake Assi...
1478    {0: 'Centeral Locking', 1: 'Power Door Locks',...
1479    {0: 'Anti Lock Braking System', 1: 'Centeral L...
1480    {0: 'Anti Lock Braking System', 1: 'Centeral L...
Name: list, Length: 1481, dtype: object

In [45]:
new_car_feature_list_4 = pd.json_normalize(new_car_feature_list_4)
new_car_feature_list_4

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,Centeral Locking,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Door Ajar Warning,Side Impact Beams,Front Impact Beams,Adjustable Seats,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Centeral Locking,Power Door Locks,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,Side Impact Beams,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
# flatten the nested dict to dataframe = 'Entertainment & communication'
new_car_feature_data_5 = pd.json_normalize(new_car_feature_cc[4])
new_car_feature_data_5

,heading,subHeading,list
0,NaN,NaN,NaN
1,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
2,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
3,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
4,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Audio System R..."
...,...,...,...
1476,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Dvd Player..."
1477,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1478,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1479,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1480,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."

In [47]:
#apply function to all values in list column
new_car_feature_list_5 = new_car_feature_data_5["list"].apply(extract_key_value_dicts1)
new_car_feature_list_5 = pd.json_normalize(new_car_feature_list_5)
new_car_feature_list_5

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Cd Player,Dvd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Cd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## New_car_specs

In [48]:
#convert string to dict
data_b["new_car_specs_dict"]= data_b["new_car_specs"].apply(ast.literal_eval)

In [49]:
#flatten the nested dict to dataframe
new_car_specs_b = pd.json_normalize(data_b["new_car_specs_dict"])
new_car_specs_b

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1476,Specifications,"[{'key': 'Mileage', 'value': '12.55 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1477,Specifications,"[{'key': 'Mileage', 'value': '15 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1478,Specifications,"[{'key': 'Mileage', 'value': '19.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1479,Specifications,"[{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1480,Specifications,"[{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",

In [50]:
new_car_specs_b.drop(columns=["commonIcon"], inplace=True, axis=1)
new_car_specs_b

,heading,top,data
0,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
2,Specifications,"[{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
3,Specifications,"[{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
4,Specifications,"[{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
...,...,...,...
1476,Specifications,"[{'key': 'Mileage', 'value': '12.55 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1477,Specifications,"[{'key': 'Mileage', 'value': '15 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
1478,Specifications,"[{'key': 'Mileage', 'value': '19.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1479,Specifications,"[{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1480,Specifications,"[{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."

In [51]:
new_car_specs_b["top"][0]

[{'key': 'Mileage', 'value': '23.1 kmpl'},
 {'key': 'Engine', 'value': '998 CC'},
 {'key': 'Max Power', 'value': '67.04bhp'},
 {'key': 'Torque', 'value': '90Nm'},
 {'key': 'Seats', 'value': '5'}]

In [52]:
#function to get kay and value in separate dict
def extract_key_value_dicts2(details2):
    if isinstance(details2, list):
        return {df['key']:df['value'] for df in details2 }
    else:
        return {}

In [53]:
#apply function to get all values in top column 
new_car_specs_top_blr = new_car_specs_b["top"].apply(extract_key_value_dicts2)
new_car_specs_top_blr

0       {'Mileage': '23.1 kmpl', 'Engine': '998 CC', '...
1       {'Mileage': '17 kmpl', 'Engine': '1497 CC', 'M...
2       {'Mileage': '23.84 kmpl', 'Engine': '1199 CC',...
3       {'Mileage': '19.1 kmpl', 'Engine': '1197 CC', ...
4       {'Mileage': '23.65 kmpl', 'Engine': '1248 CC',...
                              ...
1476    {'Mileage': '12.55 kmpl', 'Engine': '2982 CC',...
1477    {'Mileage': '15 kmpl', 'Engine': '1586 CC', 'M...
1478    {'Mileage': '19.4 kmpl', 'Engine': '1198 CC', ...
1479    {'Mileage': '22.54 kmpl', 'Engine': '1396 CC',...
1480    {'Mileage': '18.9 kmpl', 'Engine': '1197 CC', ...
Name: top, Length: 1481, dtype: object

In [54]:
new_car_specs_top_blr = pd.json_normalize(new_car_specs_top_blr)
new_car_specs_top_blr

         Mileage   Engine  Max Power    Torque Seats Wheel Size
0      23.1 kmpl   998 CC   67.04bhp      90Nm     5        NaN
1        17 kmpl  1497 CC  121.31bhp     150Nm     5         16
2     23.84 kmpl  1199 CC      84bhp     114Nm     5         14
3      19.1 kmpl  1197 CC   81.86bhp  113.75Nm     5         14
4     23.65 kmpl  1248 CC    88.5bhp     200Nm     5         16
...          ...      ...        ...       ...   ...        ...
1476  12.55 kmpl  2982 CC   168.5bhp     343Nm     7         17
1477     15 kmpl  1586 CC     104.68       145     5         16
1478   19.4 kmpl  1198 CC    86.8bhp     109Nm     5        NaN
1479  22.54 kmpl  1396 CC   88.73bhp   219.7Nm     5         16
1480   18.9 kmpl  1197 CC      82bhp     114Nm     5         14

[1481 rows x 6 columns]

In [55]:
new_car_specs_b["data"][0]

[{'heading': 'Engine and Transmission',
  'subHeading': 'Engine',
  'list': [{'key': 'Color', 'value': 'White'},
   {'key': 'Engine Type', 'value': 'K10B Engine'},
   {'key': 'Displacement', 'value': '998'},
   {'key': 'Max Power', 'value': '67.04bhp@6000rpm'},
   {'key': 'Max Torque', 'value': '90Nm@3500rpm'},
   {'key': 'No of Cylinder', 'value': 3},
   {'key': 'Values per Cylinder', 'value': 4},
   {'key': 'Value Configuration', 'value': 'DOHC'},
   {'key': 'Fuel Suppy System', 'value': 'MPFi'},
   {'key': 'BoreX Stroke', 'value': '73 X 82 mm'},
   {'key': 'Compression Ratio', 'value': '11.0:1'},
   {'key': 'Turbo Charger', 'value': 'No'},
   {'key': 'Super Charger', 'value': 'No'}]},
 {'heading': 'Dimensions & Capacity',
  'subHeading': 'Dimensions',
  'list': [{'key': 'Length', 'value': '3715mm'},
   {'key': 'Width', 'value': '1635mm'},
   {'key': 'Height', 'value': '1565mm'},
   {'key': 'Wheel Base', 'value': '2425mm'},
   {'key': 'Front Tread', 'value': '1420mm'},
   {'key': 'Rear Tread', 'value': '1410mm'},
   {'key': 'Kerb Weight', 'value': '835kg'},
   {'key': 'Gross Weight', 'value': '1250kg'}]},
 {'heading': 'Miscellaneous',
  'subHeading': 'Miscellaneous',
  'list': [{'key': 'Gear Box', 'value': '5 Speed '},
   {'key': 'Drive Type', 'value': 'FWD'},
   {'key': 'Seating Capacity', 'value': '5'},
   {'key': 'Steering Type', 'value': 'Power'},
   {'key': 'Turning Radius', 'value': '4.7 metres'},
   {'key': 'Front Brake Type', 'value': 'Ventilated Disc'},
   {'key': 'Rear Brake Type', 'value': 'Drum'},
   {'key': 'Top Speed', 'value': '150 Kmph'},
   {'key': 'Acceleration', 'value': '15.05 Seconds'},
   {'key': 'Tyre Type', 'value': 'Tubeless, Radial'},
   {'key': 'No Door Numbers', 'value': '5'},
   {'key': 'Cargo Volumn', 'value': '235-litres'}]}]

In [56]:
#flatten the nested dict in new_car_specs["data"] to dataframe
new_car_specs_data = pd.json_normalize(new_car_specs_b["data"])
new_car_specs_data

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1476,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1477,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1478,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1479,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1480,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [57]:
new_car_specs_data[0][0]

{'heading': 'Engine and Transmission',
 'subHeading': 'Engine',
 'list': [{'key': 'Color', 'value': 'White'},
  {'key': 'Engine Type', 'value': 'K10B Engine'},
  {'key': 'Displacement', 'value': '998'},
  {'key': 'Max Power', 'value': '67.04bhp@6000rpm'},
  {'key': 'Max Torque', 'value': '90Nm@3500rpm'},
  {'key': 'No of Cylinder', 'value': 3},
  {'key': 'Values per Cylinder', 'value': 4},
  {'key': 'Value Configuration', 'value': 'DOHC'},
  {'key': 'Fuel Suppy System', 'value': 'MPFi'},
  {'key': 'BoreX Stroke', 'value': '73 X 82 mm'},
  {'key': 'Compression Ratio', 'value': '11.0:1'},
  {'key': 'Turbo Charger', 'value': 'No'},
  {'key': 'Super Charger', 'value': 'No'}]}

In [58]:
#flatten the nested dict to dataframe ='Engine and Transmission'
new_car_specs_data_1=pd.json_normalize(new_car_specs_data[0])
new_car_specs_data_1

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Gray'}, {'key': 'E..."
...,...,...,...
1476,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Blue'}, {'key': 'E..."
1477,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
1478,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
1479,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
1480,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."

In [59]:
new_car_specs_data_1["list"][0]

[{'key': 'Color', 'value': 'White'},
 {'key': 'Engine Type', 'value': 'K10B Engine'},
 {'key': 'Displacement', 'value': '998'},
 {'key': 'Max Power', 'value': '67.04bhp@6000rpm'},
 {'key': 'Max Torque', 'value': '90Nm@3500rpm'},
 {'key': 'No of Cylinder', 'value': 3},
 {'key': 'Values per Cylinder', 'value': 4},
 {'key': 'Value Configuration', 'value': 'DOHC'},
 {'key': 'Fuel Suppy System', 'value': 'MPFi'},
 {'key': 'BoreX Stroke', 'value': '73 X 82 mm'},
 {'key': 'Compression Ratio', 'value': '11.0:1'},
 {'key': 'Turbo Charger', 'value': 'No'},
 {'key': 'Super Charger', 'value': 'No'}]

In [60]:
#apply function to all values in list column
new_car_specs_list_blr = new_car_specs_data_1["list"].apply(extract_key_value_dicts2)
new_car_specs_list_blr

0       {'Color': 'White', 'Engine Type': 'K10B Engine...
1       {'Color': 'White', 'Engine Type': 'Ti-VCT Petr...
2       {'Color': 'Red', 'Engine Type': 'Revotron Engi...
3       {'Color': 'Others', 'Engine Type': 'Kappa VTVT...
4       {'Color': 'Gray', 'Engine Type': 'DDiS 200 Die...
                              ...
1476    {'Color': 'Blue', 'Engine Type': 'D-4D Diesel ...
1477    {'Color': 'Red', 'Engine Type': 'In-Line Engin...
1478    {'Color': 'White', 'Engine Type': 'i-VTEC Engi...
1479    {'Color': 'Red', 'Engine Type': 'U2 CRDI Diese...
1480    {'Color': 'White', 'Engine Type': 'Kappa VTVT ...
Name: list, Length: 1481, dtype: object

In [61]:
new_car_specs_list_blr= pd.json_normalize(new_car_specs_list_blr)
new_car_specs_list_blr

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,White,K10B Engine,998,67.04bhp@6000rpm,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,NaN,NaN,NaN,NaN,NaN
1,White,Ti-VCT Petrol Engine,1497,121.31bhp@6500rpm,150Nm@4500rpm,3.0,4.0,DOHC,Direct Injection,79 X 76.5 mm,11.0:1,No,No,NaN,NaN,NaN,NaN,NaN
2,Red,Revotron Engine,1199,84bhp@6000rpm,114Nm@3500rpm,3.0,4.0,DOHC,MPFi,77 X 85.8 mm,10.8:1,No,No,NaN,NaN,NaN,NaN,NaN
3,Others,Kappa VTVT Petrol Engine,1197,81.86bhp@6000rpm,113.75Nm@4000rpm,4.0,4.0,DOHC,Direct Injection,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN
4,Gray,DDiS 200 Diesel Engine,1248,88.5bhp@4000rpm,200Nm@1750rpm,4.0,4.0,DOHC,NaN,69.6 x 82 mm,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Blue,D-4D Diesel Engine,2982,168.5bhp@3600rpm,343Nm@1400-3400rpm,4.0,4.0,DOHC,CRDi,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
1477,Red,In-Line Engine,1586,"104.68@5,600 (PS@rpm)","145@4,100 (kgm@rpm)",4.0,4.0,DOHC,MPFI,78 x 83 mm,9:01,No,No,NaN,NaN,NaN,NaN,NaN
1478,White,i-VTEC Engine,1198,86.8bhp@6000rpm,109Nm@4500rpm,4.0,4.0,SOHC,PGM - Fi,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN
1479,Red,U2 CRDI Diesel Engine,1396,88.73bhp@4000rpm,219.7Nm@1500-2750rpm,4.0,4.0,DOHC,CRDI,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
1480,White,Kappa VTVT Petrol Engine,1197,82bhp@6000rpm,114Nm@4000rpm,4.0,4.0,DOHC,MPFI,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN

In [62]:
#flatten the nested dict to dataframe ='Dimension & Capacity' 
new_car_specs_data_2 = pd.json_normalize(new_car_specs_data[1])
new_car_specs_data_2

,heading,subHeading,list
0,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3715mm'}, {'key':..."
1,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3998mm'}, {'key':..."
2,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3746mm'}, {'key':..."
3,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."
4,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4300mm'}, {'key':..."
...,...,...,...
1476,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4705mm'}, {'key':..."
1477,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4490mm'}, {'key':..."
1478,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3610mm'}, {'key':..."
1479,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3985mm'}, {'key':..."
1480,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3765mm'}, {'key':..."

In [63]:
new_car_specs_list_2_blr = new_car_specs_data_2["list"].apply(extract_key_value_dicts2)
new_car_specs_list_2_blr

0       {'Length': '3715mm', 'Width': '1635mm', 'Heigh...
1       {'Length': '3998mm', 'Width': '1765mm', 'Heigh...
2       {'Length': '3746mm', 'Width': '1647mm', 'Heigh...
3       {'Length': '3995mm', 'Width': '1660mm', 'Heigh...
4       {'Length': '4300mm', 'Width': '1785mm', 'Heigh...
                              ...
1476    {'Length': '4705mm', 'Width': '1840mm', 'Heigh...
1477    {'Length': '4490mm', 'Width': '1735mm', 'Heigh...
1478    {'Length': '3610mm', 'Width': '1680mm', 'Heigh...
1479    {'Length': '3985mm', 'Width': '1734mm', 'Heigh...
1480    {'Length': '3765mm', 'Width': '1660mm', 'Heigh...
Name: list, Length: 1481, dtype: object

In [64]:
new_car_specs_list_2_blr= pd.json_normalize(new_car_specs_list_2_blr)
new_car_specs_list_2_blr

,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,NaN,NaN,NaN,NaN,NaN,NaN
1,3998mm,1765mm,1647mm,2519mm,NaN,NaN,1242Kg,1660Kg,NaN,NaN,NaN,NaN,NaN,NaN
2,3746mm,1647mm,1535mm,2400mm,1400mm,1420mm,1012kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3995mm,1660mm,1520mm,2425mm,1479mm,1493mm,1180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4300mm,1785mm,1595mm,2600mm,NaN,NaN,1230Kg,1670kg,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,4705mm,1840mm,1850mm,2750mm,1540mm,1540mm,1970kg,2510kg,NaN,NaN,NaN,NaN,NaN,NaN
1477,4490mm,1735mm,1570mm,2500mm,1500mm,1495mm,1200kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,3610mm,1680mm,1500mm,2345mm,1480mm,1465mm,925kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,3985mm,1734mm,1505mm,2570mm,1505mm,1503mm,1515kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,3765mm,1660mm,1520mm,2425mm,1479mm,1493mm,935kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
#flatten the nested dict to dataframe  ='miscellaneous'
new_car_specs_data_3 = pd.json_normalize(new_car_specs_data[2])
new_car_specs_data_3

,heading,subHeading,list
0,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed '}, {'k..."
1,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
2,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
3,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed '}, {'k..."
4,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
...,...,...,...
1476,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1477,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1478,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1479,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1480,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '4 Speed'}, {'ke..."

In [66]:
#apply function to all values in list column
new_car_specs_list_3_blr= new_car_specs_data_3["list"].apply(extract_key_value_dicts2)
new_car_specs_list_3_blr = pd.json_normalize(new_car_specs_list_3_blr)
new_car_specs_list_3_blr

,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size
0,5 Speed,FWD,5,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN
1,5 Speed,FWD,5,Power,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16
2,5 Speed,FWD,5,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14
3,5 Speed,FWD,5,Power,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14
4,5 Speed,FWD,5,Power,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,5 Speed,4WD,7,Power,5.9 metres,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17
1477,5 Speed,NaN,5,Power,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16
1478,5 Speed,FWD,5,Power,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN
1479,6 Speed,FWD,5,Power,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16
1480,4 Speed,FWD,5,Power,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14

In [67]:
#concat bangalore car details
banglore_cars_data= pd.concat([new_car_detail_b,new_car_overview_blr,new_car_specs_top_blr,new_car_specs_list_blr,new_car_specs_list_2_blr,new_car_specs_list_3_blr], axis=1)
banglore_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Power,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Power,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Power,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,Power,5.9 metres,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,Power,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,Power,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,Power,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,Power,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14

In [68]:
#add city column to dataframe
banglore_cars_data['City']='Bangalore'
#final dataframe
banglore_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Alloy Wheel Size,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,5.9 metres,Ventilated Disc,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5,296-litres,17,Bangalore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,5.3 m,Ventilated Disc,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4,505 litres,16,Bangalore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,4.5 metres,Disc,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5,175-litres,NaN,Bangalore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,5,295-litres,16,Bangalore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,5,256-liters,14,Bangalore

## Chennai cars

In [69]:
# convert excel file to dataframe
df_chennai = pd.read_excel(r"C:/Users/jagadesh/Documents/Python Scripts/car dekho - used car prediction/unstructured_files/chennai_cars.xlsx")
df_chennai

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [70]:
#drop column from dataframe
df_chennai.drop(columns=["car_links"], inplace=True, axis=1)
df_chennai

,new_car_detail,new_car_overview,new_car_feature,new_car_specs
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."

## new_car_detail

In [71]:
#view new_car_detail
df_chennai["new_car_detail"]

0       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
                              ...
1414    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1415    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1416    {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
1417    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1418    {'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...
Name: new_car_detail, Length: 1419, dtype: object

In [72]:
#viewing first row/first index of the 'new_car_detail'
df_chennai["new_car_detail"][0]

"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '20,000', 'transmission': 'Automatic', 'ownerNo': 1, 'owner': '1st Owner', 'oem': 'Kia', 'model': 'Kia Sonet', 'modelYear': 2022, 'centralVariantId': 8654, 'variantName': 'Turbo DCT Anniversary Edition', 'price': 'â‚¹ 11.50 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

In [73]:
#convert string to dict
df_chennai["new_car_detail_dict"]= df_chennai["new_car_detail"].apply(ast.literal_eval)

In [74]:
#flatten the nested dict to dataframe
new_car_detail_che = pd.json_normalize(df_chennai["new_car_detail_dict"])
new_car_detail_che

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,8654,Turbo DCT Anniversary Edition,â‚¹ 11.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,4025,7 Seater Standard BSIV,â‚¹ 4.15 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,8135,Turbo XV Premium BSVI,â‚¹ 7.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,1579,Sportz 1.1L,â‚¹ 3.98 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,1341,1.2 VX i VTEC,â‚¹ 5.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,6190,AMT VXI,â‚¹ 6.20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,5050,85PS Diesel RxZ,â‚¹ 8.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,6364,1.2 Revotron XZA Plus,â‚¹ 8.01 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,5849,2.0 TDI Highline,â‚¹ 20.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,6630,Sport,â‚¹ 35.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

## new_car_overview

In [75]:
#convert string to dict
df_chennai["new_car_overview_dict"]=df_chennai["new_car_overview"].apply(ast.literal_eval)
df_chennai["new_car_overview_dict"]

0       {'heading': 'Car overview', 'top': [{'key': 'R...
1       {'heading': 'Car overview', 'top': [{'key': 'R...
2       {'heading': 'Car overview', 'top': [{'key': 'R...
3       {'heading': 'Car overview', 'top': [{'key': 'R...
4       {'heading': 'Car overview', 'top': [{'key': 'R...
                              ...
1414    {'heading': 'Car overview', 'top': [{'key': 'R...
1415    {'heading': 'Car overview', 'top': [{'key': 'R...
1416    {'heading': 'Car overview', 'top': [{'key': 'R...
1417    {'heading': 'Car overview', 'top': [{'key': 'R...
1418    {'heading': 'Car overview', 'top': [{'key': 'R...
Name: new_car_overview_dict, Length: 1419, dtype: object

In [76]:
df_chennai["new_car_overview_dict"][0]

{'heading': 'Car overview',
 'top': [{'key': 'Registration Year',
   'value': '2022',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'},
  {'key': 'Insurance Validity',
   'value': 'Third Party insurance',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'},
  {'key': 'Fuel Type',
   'value': 'Petrol',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'},
  {'key': 'Seats',
   'value': '5 Seats',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'},
  {'key': 'Kms Driven',
   'value': '20,000 Kms',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'},
  {'key': 'RTO',
   'value': 'TN02',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'},
  {'key': 'Ownership',
   'value': 'First Owner',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'},
  {'key': 'Engine Displacement',
   'value': '998 cc',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'},
  {'key': 'Transmission',
   'value': 'Automatic',
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'},
  {'key': 'Year of Manufacture',
   'value': 2022,
   'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}],
 'bottomData': None}

In [77]:
new_car_overview_CHE = pd.json_normalize(df_chennai["new_car_overview_dict"])
new_car_overview_CHE

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': '2021',...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
...,...,...,...
1414,Car overview,"[{'key': 'Registration Year', 'value': 'Jun 20...",None
1415,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None
1416,Car overview,"[{'key': 'Registration Year', 'value': 'Aug 20...",None
1417,Car overview,"[{'key': 'Registration Year', 'value': 'Aug 20...",None
1418,Car overview,"[{'key': 'Registration Year', 'value': 'Oct 20...",None

In [78]:
#drop column bottomData
new_car_overview_CHE.drop(columns=["bottomData"], inplace=True, axis=1)
new_car_overview_CHE

           heading                                                top
0     Car overview  [{'key': 'Registration Year', 'value': '2022',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
2     Car overview  [{'key': 'Registration Year', 'value': '2021',...
3     Car overview  [{'key': 'Registration Year', 'value': 'May 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2015',...
...            ...                                                ...
1414  Car overview  [{'key': 'Registration Year', 'value': 'Jun 20...
1415  Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
1416  Car overview  [{'key': 'Registration Year', 'value': 'Aug 20...
1417  Car overview  [{'key': 'Registration Year', 'value': 'Aug 20...
1418  Car overview  [{'key': 'Registration Year', 'value': 'Oct 20...

[1419 rows x 2 columns]

In [79]:
#apply function to all values to get key and values from top column
new_car_overview_CHE= new_car_overview_CHE["top"].apply(extract_key_value_dicts)

In [80]:
new_car_overview_CHE

0       {'Registration Year': '2022', 'Insurance Valid...
1       {'Registration Year': 'Feb 2015', 'Insurance V...
2       {'Registration Year': '2021', 'Insurance Valid...
3       {'Registration Year': 'May 2015', 'Insurance V...
4       {'Registration Year': '2015', 'Insurance Valid...
                              ...
1414    {'Registration Year': 'Jun 2018', 'Insurance V...
1415    {'Registration Year': 'Feb 2019', 'Insurance V...
1416    {'Registration Year': 'Aug 2018', 'Insurance V...
1417    {'Registration Year': 'Aug 2017', 'Insurance V...
1418    {'Registration Year': 'Oct 2019', 'Insurance V...
Name: top, Length: 1419, dtype: object

In [81]:
new_car_overview_CHE=pd.json_normalize(new_car_overview_CHE)
new_car_overview_CHE

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2022,Third Party insurance,Petrol,5 Seats,"20,000 Kms",TN02,First Owner,998 cc,Automatic,2022
1,Feb 2015,Comprehensive,Petrol,7 Seats,"20,687 Kms",TN04,First Owner,1196 cc,Manual,2015
2,2021,Third Party insurance,Petrol,5 Seats,"30,000 Kms",TN22,First Owner,999 cc,Manual,2021
3,May 2015,Comprehensive,Petrol,5 Seats,"59,247 Kms",TN11,First Owner,1086 cc,Manual,2015
4,2015,Third Party insurance,Petrol,5 Seats,"50,000 Kms",KA03,First Owner,1199 cc,Manual,2015
...,...,...,...,...,...,...,...,...,...,...
1414,Jun 2018,Third Party insurance,Petrol,5 Seats,"42,891 Kms",TN09,First Owner,1197 cc,Automatic,2018
1415,Feb 2019,Third Party insurance,Diesel,5 Seats,"59,100 Kms",TN11,First Owner,1461 cc,Manual,2018
1416,Aug 2018,Not Available,Petrol,5 Seats,"55,913 Kms",TN11,First Owner,1198 cc,Automatic,2018
1417,Aug 2017,Comprehensive,Diesel,5 Seats,"65,000 Kms",TN22,First Owner,1968 cc,Automatic,2017
1418,Oct 2019,Comprehensive,Diesel,5 Seats,"60,000 Kms",TN87,First Owner,1995 cc,Automatic,2019

## new_car_feature

In [82]:
df_chennai["new_car_feature"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Low...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1414    {'heading': 'Features', 'top': [{'value': 'Pow...
1415    {'heading': 'Features', 'top': [{'value': 'Pow...
1416    {'heading': 'Features', 'top': [{'value': 'Pow...
1417    {'heading': 'Features', 'top': [{'value': 'Pow...
1418    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature, Length: 1419, dtype: object

In [83]:
df_chennai["new_car_feature"][0]

"{'heading': 'Features', 'top': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Anti Lock Braking System'}, {'value': 'Brake Assist'}, {'value': 'Radio'}], 'data': [{'heading': 'Comfort & Convenience', 'subHeading': 'Comfort', 'list': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Power Windows Rear'}, {'value': 'Low Fuel Warning Light'}, {'value': 'Accessory Power Outlet'}, {'value': 'Trunk Light'}, {'value': 'Rear Reading Lamp'}, {'value': 'Rear Seat Headrest'}, {'value': 'Rear Seat Centre Arm Rest'}, {'value': 'Cup Holders Rear'}, {'value': 'Multifunction Steering Wheel'}, {'value': 'Cruise Control'}, {'value': 'Rear ACVents'}, {'value': 'Smart Access Card Entry'}, {'value': 'Engine Start Stop Button'}, {'value': 'Steering Wheel Gearshift Paddles'}, {'value': 'Battery Saver'}, {'value': 'Drive Modes'}, {'value': 'Remote Engine Start Stop'}, {'value': 'Adjustable Headrest'}]}, {'heading': 'Interior', 'subHeading': 'Interior', 'list': [{'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Steering'}, {'value': 'Digital Odometer'}, {'value': 'Electronic Multi Tripmeter'}, {'value': 'Leather Seats'}, {'value': 'Fabric Upholstery'}, {'value': 'Leather Steering Wheel'}, {'value': 'Glove Compartment'}, {'value': 'Digital Clock'}, {'value': 'Driving Experience Control Eco'}, {'value': 'Height Adjustable Driver Seat'}, {'value': 'Leather Wrap Gear Shift Selector'}]}, {'heading': 'Exterior', 'subHeading': 'Exterior', 'list': [{'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Power Adjustable Exterior Rear View Mirror'}, {'value': 'Electric Folding Rear View Mirror'}, {'value': 'Rear Window Defogger'}, {'value': 'Alloy Wheels'}, {'value': 'Integrated Antenna'}, {'value': 'Tinted Glass'}, {'value': 'Rear Spoiler'}, {'value': 'Sun Roof'}, {'value': 'Moon Roof'}, {'value': 'Outside Rear View Mirror Turn Indicators'}, {'value': 'Chrome Grille'}, {'value': 'Roof Rail'}, {'value': 'LEDDRLs'}, {'value': 'LEDHeadlights'}, {'value': 'LEDTaillights'}]}, {'heading': 'Safety', 'subHeading': 'Safety', 'list': [{'value': 'Anti Lock Braking System'}, {'value': 'Brake Assist'}, {'value': 'Centeral Locking'}, {'value': 'Power Door Locks'}, {'value': 'Child Safety Locks'}, {'value': 'Driver Air Bag'}, {'value': 'Passenger Air Bag'}, {'value': 'Side Air Bag Front'}, {'value': 'Day Night Rear View Mirror'}, {'value': 'Passenger Side Rear View Mirror'}, {'value': 'Rear Seat Belts'}, {'value': 'Seat Belt Warning'}, {'value': 'Vehicle Stability Control System'}, {'value': 'Traction Control'}, {'value': 'Adjustable Seats'}, {'value': 'Keyless Entry'}, {'value': 'Engine Check Warning'}, {'value': 'Crash Sensor'}, {'value': 'Automatic Head Lamps'}, {'value': 'Ebd'}, {'value': 'Follow Me Home Headlamps'}, {'value': 'Rear Camera'}, {'value': 'Anti Pinch Power Windows'}, {'value': 'Speed Sensing Auto Door Lock'}, {'value': 'Isofix Child Seat Mounts'}, {'value': 'Pretensioners And Force Limiter Seatbelts'}, {'value': 'Hill Assist'}, {'value': 'Impact Sensing Auto Door Lock'}, {'value': 'No Of Airbags'}, {'value': 'Eletronic Stability Control'}]}, {'heading': 'Entertainment & Communication', 'subHeading': 'Entertainment', 'list': [{'value': 'Radio'}, {'value': 'Speakers Front'}, {'value': 'Speakers Rear'}, {'value': 'Integrated2Din Audio'}, {'value': 'Bluetooth'}, {'value': 'Touch Screen'}, {'value': 'Number Of Speaker'}, {'value': 'Apple Car Play'}, {'value': 'Android Auto'}]}], 'commonIcon': 'https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg'}"

In [84]:
#convert string to dict
df_chennai["new_car_feature_dict"]= df_chennai["new_car_feature"].apply(ast.literal_eval)
df_chennai["new_car_feature_dict"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Low...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1414    {'heading': 'Features', 'top': [{'value': 'Pow...
1415    {'heading': 'Features', 'top': [{'value': 'Pow...
1416    {'heading': 'Features', 'top': [{'value': 'Pow...
1417    {'heading': 'Features', 'top': [{'value': 'Pow...
1418    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature_dict, Length: 1419, dtype: object

In [85]:
#flatten the nested dict to dataframe
new_car_feature_CHE=pd.json_normalize(df_chennai["new_car_feature_dict"])
new_car_feature_CHE

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Low Fuel Warning Light'}, {'value'...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1414,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1415,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1416,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1417,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1418,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [86]:
#drop column 'commonIcon' from dataframe
new_car_feature_CHE.drop(columns=["commonIcon"], inplace=True,axis=1)
new_car_feature_CHE

,heading,top,data
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1,Features,"[{'value': 'Low Fuel Warning Light'}, {'value'...","[{'heading': 'Comfort & Convenience', 'subHead..."
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
...,...,...,...
1414,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1415,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1416,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1417,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1418,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."

In [87]:
#apply function to all the values in top column
new_car_feature_top_1=new_car_feature_CHE["top"].apply(extract_key_value_dicts1)
new_car_feature_top_1

0       {0: 'Power Steering', 1: 'Power Windows Front'...
1       {0: 'Low Fuel Warning Light', 1: 'Accessory Po...
2       {0: 'Power Steering', 1: 'Power Windows Front'...
3       {0: 'Power Steering', 1: 'Power Windows Front'...
4       {0: 'Power Steering', 1: 'Power Windows Front'...
                              ...
1414    {0: 'Power Steering', 1: 'Power Windows Front'...
1415    {0: 'Power Steering', 1: 'Power Windows Front'...
1416    {0: 'Power Steering', 1: 'Power Windows Front'...
1417    {0: 'Power Steering', 1: 'Power Windows Front'...
1418    {0: 'Power Steering', 1: 'Power Windows Front'...
Name: top, Length: 1419, dtype: object

In [88]:
new_car_feature_top_1=pd.json_normalize(new_car_feature_top_1)
new_car_feature_top_1

,0,1,2,3,4,5,6,7,8
0,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Radio
1,Low Fuel Warning Light,Accessory Power Outlet,Heater,Digital Odometer,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Child Safety Locks,NaN
2,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Radio
3,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Centeral Locking,Power Door Locks,Cd Player
4,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
...,...,...,...,...,...,...,...,...,...
1414,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Brake Assist,Cd Player
1415,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player
1416,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
1417,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player
1418,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player

In [89]:
#flatten the nested dict to dataframe
new_car_feature_data_CHE = pd.json_normalize(new_car_feature_CHE["data"])
new_car_feature_data_CHE

,0,1,2,3,4
0,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",None
2,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
3,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
4,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
...,...,...,...,...,...
1414,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1415,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1416,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1417,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1418,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."

In [90]:
#flatten the nested dict to dataframe
new_car_feature_data_1_CHE = pd.json_normalize(new_car_feature_data_CHE[0])
new_car_feature_data_1_CHE

,heading,subHeading,list
0,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1,Comfort & Convenience,Comfort,"[{'value': 'Low Fuel Warning Light'}, {'value'..."
2,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
3,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
4,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
...,...,...,...
1414,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1415,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1416,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1417,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1418,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."

In [91]:
#apply function to all values in list column
new_car_feature_list_1_CHE= new_car_feature_data_1_CHE["list"].apply(extract_key_value_dicts1)
new_car_feature_list_1_CHE= pd.json_normalize(new_car_feature_list_1_CHE)
new_car_feature_list_1

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
#flatten the nested dict to dataframe
new_car_feature_data_2_CHE = pd.json_normalize(new_car_feature_data_CHE[1])
new_car_feature_data_2_CHE

       heading subHeading                                               list
0     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1     Interior   Interior  [{'value': 'Heater'}, {'value': 'Digital Odome...
2     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
3     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
4     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
...        ...        ...                                                ...
1414  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1415  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1416  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1417  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1418  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...

[1419 rows x 3 columns]

In [93]:
#apply function to all values in list column
new_car_feature_list_2_CHE= new_car_feature_data_2_CHE["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2_CHE= pd.json_normalize(new_car_feature_list_2_CHE)
new_car_feature_list_2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Air Conditioner,Heater,Digital Odometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
1477,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,NaN,NaN,NaN,NaN
1478,Air Conditioner,Heater,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
1479,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,Dual Tone Dashboard,NaN,NaN,NaN,NaN,NaN
1480,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN

In [94]:
#flatten the nested dict to dataframe
new_car_feature_data_3_CHE = pd.json_normalize(new_car_feature_data_CHE[2])
new_car_feature_data_3_CHE

       heading subHeading                                               list
0     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
2     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
3     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
4     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
...        ...        ...                                                ...
1414  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1415  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1416  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1417  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1418  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...

[1419 rows x 3 columns]

In [95]:
#apply function to all values in list column
new_car_feature_list_3_CHE= new_car_feature_data_3_CHE["list"].apply(extract_key_value_dicts1)
new_car_feature_list_3_CHE= pd.json_normalize(new_car_feature_list_3_CHE)
new_car_feature_list_3

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Wheel Covers,Power Antenna,Chrome Grille,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Wheel Covers,Power Antenna,Tinted Glass,Rear Spoiler,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Alloy Wheels,Power Antenna,Outside Rear View Mirror Turn Indicators,Chrome Grille,Chrome Garnish,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Tinted Glass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Side Stepper,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Alloy Wheels,Tinted Glass,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Wheel Covers,Power Antenna,Chrome Grille,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Rear Spoiler,Outside Rear View Mirror Turn Indicators,Chrome Grille,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Tinted Glass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
#flatten the nested dict to dataframe
new_car_feature_data_4_CHE = pd.json_normalize(new_car_feature_data_CHE[3])
new_car_feature_data_4_CHE

     heading subHeading                                               list
0     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
2     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
3     Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Pow...
4     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
...      ...        ...                                                ...
1414  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1415  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1416  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1417  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1418  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...

[1419 rows x 3 columns]

In [97]:
#apply function to all values in list column
new_car_feature_list_4_CHE= new_car_feature_data_4_CHE["list"].apply(extract_key_value_dicts1)
new_car_feature_list_4_CHE= pd.json_normalize(new_car_feature_list_4_CHE)
new_car_feature_list_4

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,Centeral Locking,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Door Ajar Warning,Side Impact Beams,Front Impact Beams,Adjustable Seats,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Centeral Locking,Power Door Locks,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,Side Impact Beams,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
#flatten the nested dict to dataframe
new_car_feature_data_5_CHE = pd.json_normalize(new_car_feature_data_CHE[4])
new_car_feature_data_5_CHE

,heading,subHeading,list
0,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1,NaN,NaN,NaN
2,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
3,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
4,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Dvd Player..."
...,...,...,...
1414,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1415,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1416,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1417,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1418,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Cd Changer..."

In [99]:
#apply function to all values in list column
new_car_feature_list_5_CHE= new_car_feature_data_5_CHE["list"].apply(extract_key_value_dicts1)
new_car_feature_list_5_CHE= pd.json_normalize(new_car_feature_list_5_CHE)
new_car_feature_list_5

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Cd Player,Dvd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,Cd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## new_car_specs

In [100]:
df_chennai["new_car_specs"]

0       {'heading': 'Specifications', 'top': [{'key': ...
1       {'heading': 'Specifications', 'top': [{'key': ...
2       {'heading': 'Specifications', 'top': [{'key': ...
3       {'heading': 'Specifications', 'top': [{'key': ...
4       {'heading': 'Specifications', 'top': [{'key': ...
                              ...
1414    {'heading': 'Specifications', 'top': [{'key': ...
1415    {'heading': 'Specifications', 'top': [{'key': ...
1416    {'heading': 'Specifications', 'top': [{'key': ...
1417    {'heading': 'Specifications', 'top': [{'key': ...
1418    {'heading': 'Specifications', 'top': [{'key': ...
Name: new_car_specs, Length: 1419, dtype: object

In [101]:
df_chennai["new_car_specs"][0]

"{'heading': 'Specifications', 'top': [{'key': 'Engine', 'value': '998 CC'}, {'key': 'Max Power', 'value': '118.36bhp'}, {'key': 'Torque', 'value': '172nm'}, {'key': 'Wheel Size', 'value': '16'}, {'key': 'Seats', 'value': '5'}], 'data': [{'heading': 'Engine and Transmission', 'subHeading': 'Engine', 'list': [{'key': 'Color', 'value': 'Black'}, {'key': 'Engine Type', 'value': 'Smartstream G1.0 T - GDi'}, {'key': 'Displacement', 'value': '998'}, {'key': 'Max Power', 'value': '118.36bhp@6000rpm'}, {'key': 'Max Torque', 'value': '172nm@1500-4000rpm'}, {'key': 'No of Cylinder', 'value': 3}, {'key': 'Values per Cylinder', 'value': 4}, {'key': 'Fuel Suppy System', 'value': 'GDi'}, {'key': 'Turbo Charger', 'value': 'Yes'}]}, {'heading': 'Dimensions & Capacity', 'subHeading': 'Dimensions', 'list': [{'key': 'Length', 'value': '3995mm'}, {'key': 'Width', 'value': '1790'}, {'key': 'Height', 'value': '1642'}, {'key': 'Wheel Base', 'value': '2500'}, {'key': 'Kerb Weight', 'value': '1465'}]}, {'heading': 'Miscellaneous', 'subHeading': 'Miscellaneous', 'list': [{'key': 'Gear Box', 'value': '7-Speed DCT'}, {'key': 'Drive Type', 'value': 'FWD'}, {'key': 'Seating Capacity', 'value': '5'}, {'key': 'Steering Type', 'value': 'Electric'}, {'key': 'Front Brake Type', 'value': 'Disc'}, {'key': 'Rear Brake Type', 'value': 'Drum'}, {'key': 'Tyre Type', 'value': 'Tubeless, Radial'}, {'key': 'Alloy Wheel Size', 'value': '16'}, {'key': 'No Door Numbers', 'value': '5'}, {'key': 'Cargo Volumn', 'value': '392'}]}], 'commonIcon': ''}"

In [102]:
#convert string to dict
df_chennai["new_car_specs_dict"]= df_chennai["new_car_specs"].apply(ast.literal_eval)
#flatten the nested dict to dataframe
new_car_specs_CHE= pd.json_normalize(df_chennai["new_car_specs_dict"])
new_car_specs_CHE

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Engine', 'value': '998 CC'}, {'key':...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '15.37 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '20 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '19.81 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '18.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1414,Specifications,"[{'key': 'Mileage', 'value': '22 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1415,Specifications,"[{'key': 'Mileage', 'value': '19.87 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1416,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1417,Specifications,"[{'key': 'Mileage', 'value': '16.65 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1418,Specifications,"[{'key': 'Mileage', 'value': '21.76 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",

In [103]:
#dropcolumn 'commonIcon' from dataframe
new_car_specs_CHE.drop(columns=["commonIcon"], inplace=True, axis=1)
new_car_specs_CHE

,heading,top,data
0,Specifications,"[{'key': 'Engine', 'value': '998 CC'}, {'key':...","[{'heading': 'Engine and Transmission', 'subHe..."
1,Specifications,"[{'key': 'Mileage', 'value': '15.37 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
2,Specifications,"[{'key': 'Mileage', 'value': '20 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
3,Specifications,"[{'key': 'Mileage', 'value': '19.81 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
4,Specifications,"[{'key': 'Mileage', 'value': '18.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
...,...,...,...
1414,Specifications,"[{'key': 'Mileage', 'value': '22 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
1415,Specifications,"[{'key': 'Mileage', 'value': '19.87 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1416,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
1417,Specifications,"[{'key': 'Mileage', 'value': '16.65 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1418,Specifications,"[{'key': 'Mileage', 'value': '21.76 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."

In [104]:
#apply function to all values in top column
new_car_specs_top_CHE= new_car_specs_CHE["top"].apply(extract_key_value_dicts2)
new_car_specs_top_CHE

0       {'Engine': '998 CC', 'Max Power': '118.36bhp',...
1       {'Mileage': '15.37 kmpl', 'Engine': '1196 CC',...
2       {'Mileage': '20 kmpl', 'Engine': '999 CC', 'Ma...
3       {'Mileage': '19.81 kmpl', 'Engine': '1086 CC',...
4       {'Mileage': '18.7 kmpl', 'Engine': '1199 CC', ...
                              ...
1414    {'Mileage': '22 kmpl', 'Engine': '1197 CC', 'M...
1415    {'Mileage': '19.87 kmpl', 'Engine': '1461 CC',...
1416    {'Mileage': '17 kmpl', 'Engine': '1198 CC', 'M...
1417    {'Mileage': '16.65 kmpl', 'Engine': '1968 CC',...
1418    {'Mileage': '21.76 kmpl', 'Engine': '1995 CC',...
Name: top, Length: 1419, dtype: object

In [105]:
new_car_specs_top_CHE=pd.json_normalize(new_car_specs_top_CHE)
new_car_specs_top_CHE

       Engine  Max Power   Torque Wheel Size Seats     Mileage
0      998 CC  118.36bhp    172nm         16     5         NaN
1     1196 CC      73bhp    101Nm        NaN     7  15.37 kmpl
2      999 CC   98.63bhp    160Nm         16     5     20 kmpl
3     1086 CC   68.05bhp  99.04Nm        NaN     5  19.81 kmpl
4     1199 CC    88.7bhp    110Nm         15     5   18.7 kmpl
...       ...        ...      ...        ...   ...         ...
1414  1197 CC   81.80bhp    113Nm        NaN     5     22 kmpl
1415  1461 CC    83.8bhp    200Nm         16     5  19.87 kmpl
1416  1198 CC   108.5bhp    170Nm         16     5     17 kmpl
1417  1968 CC     141bhp    340Nm         18     5  16.65 kmpl
1418  1995 CC     188bhp    400Nm         18     5  21.76 kmpl

[1419 rows x 6 columns]

In [106]:
new_car_specs_CHE["data"]

0       [{'heading': 'Engine and Transmission', 'subHe...
1       [{'heading': 'Engine and Transmission', 'subHe...
2       [{'heading': 'Engine and Transmission', 'subHe...
3       [{'heading': 'Engine and Transmission', 'subHe...
4       [{'heading': 'Engine and Transmission', 'subHe...
                              ...
1414    [{'heading': 'Engine and Transmission', 'subHe...
1415    [{'heading': 'Engine and Transmission', 'subHe...
1416    [{'heading': 'Engine and Transmission', 'subHe...
1417    [{'heading': 'Engine and Transmission', 'subHe...
1418    [{'heading': 'Engine and Transmission', 'subHe...
Name: data, Length: 1419, dtype: object

In [107]:
#flatten the nested dict to dataframe
new_car_specs_data_CHE= pd.json_normalize(new_car_specs_CHE["data"])
new_car_specs_data_CHE

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1414,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1415,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1416,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1417,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1418,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [108]:
#flatten the nested dict in '0:engine and transmission'
new_car_specs_data_1_CHE= pd.json_normalize(new_car_specs_data_CHE[0])
new_car_specs_data_1_CHE

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Black'}, {'key': '..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Grey'}, {'key': 'E..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
...,...,...,...
1414,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Blue'}, {'key': 'E..."
1415,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Orange'}, {'key': ..."
1416,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
1417,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Grey'}, {'key': 'E..."
1418,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."

In [109]:
#apply function to all values in list column
new_car_specs_list_1_CHE= new_car_specs_data_1_CHE["list"].apply(extract_key_value_dicts2)
new_car_specs_list_1_CHE

0       {'Color': 'Black', 'Engine Type': 'Smartstream...
1       {'Color': 'Grey', 'Engine Type': 'In-Line Engi...
2       {'Color': 'Others', 'Engine Type': 'HRA0 1.0 T...
3       {'Color': 'Silver', 'Engine Type': 'IRDE2 Engi...
4       {'Color': 'Others', 'Engine Type': 'i-VTEC Pet...
                              ...
1414    {'Color': 'Blue', 'Engine Type': 'VTVT Engine'...
1415    {'Color': 'Orange', 'Engine Type': 'dCi THP Di...
1416    {'Color': 'White', 'Engine Type': 'Revotron 1....
1417    {'Color': 'Grey', 'Engine Type': 'Common Rail ...
1418    {'Color': 'White', 'Engine Type': 'TwinPower T...
Name: list, Length: 1419, dtype: object

In [110]:
new_car_specs_list_1_CHE= pd.json_normalize(new_car_specs_list_1_CHE)
new_car_specs_list_1_CHE

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Fuel Suppy System,Turbo Charger,Value Configuration,Compression Ratio,Super Charger,BoreX Stroke
0,Black,Smartstream G1.0 T - GDi,998,118.36bhp@6000rpm,172nm@1500-4000rpm,3.0,4.0,GDi,Yes,NaN,NaN,NaN,NaN
1,Grey,In-Line Engine,1196,73bhp@6000rpm,101Nm@3000rpm,4.0,4.0,MPFi,No,DOHC,9.9:1,No,NaN
2,Others,HRA0 1.0 TURBO PETROL,999,98.63bhp@5000rpm,160Nm@2800-3600rpm,3.0,4.0,MPFi,Yes,SOHC,NaN,No,72.2 x 81.3
3,Silver,IRDE2 Engine,1086,68.05bhp@5500rpm,99.04Nm@4500rpm,4.0,3.0,MPFI,No,SOHC,NaN,No,NaN
4,Others,i-VTEC Petrol Engine,1199,88.7bhp@6000rpm,110Nm@4800rpm,4.0,4.0,PGM - Fi,No,SOHC,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,Blue,VTVT Engine,1197,81.80bhp@6000rpm,113Nm@4200rpm,4.0,4.0,MPFi,No,NaN,NaN,No,NaN
1415,Orange,dCi THP Diesel Engine,1461,83.8bhp@3750rpm,200Nm@1750rpm,4.0,4.0,CRDi,Yes,DOHC,NaN,No,NaN
1416,White,Revotron 1.2L Turbocharged engine,1198,108.5bhp@5000rpm,170Nm@1750-4000rpm,3.0,4.0,MPFI,Yes,DOHC,NaN,No,77x85.8
1417,Grey,Common Rail Direct Injection,1968,141bhp@4000rpm,340Nm@1750-2750rpm,4.0,4.0,CRDI,Yes,DOHC,NaN,No,74.5 x 81 mm
1418,White,TwinPower Turbo 4-Cylinder Diesel Engine,1995,188bhp@4000rpm,400Nm@1750-2500rpm,4.0,4.0,CRDi,Yes,DOHC,NaN,No,NaN

In [111]:
#flatten the nested dict in '1:dimension and capacity'
new_car_specs_data_2_CHE= pd.json_normalize(new_car_specs_data_CHE[1])
new_car_specs_data_2_CHE

,heading,subHeading,list
0,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."
1,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3675mm'}, {'key':..."
2,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3994mm'}, {'key':..."
3,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3585mm'}, {'key':..."
4,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3955mm'}, {'key':..."
...,...,...,...
1414,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3840mm'}, {'key':..."
1415,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4315mm'}, {'key':..."
1416,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3994mm'}, {'key':..."
1417,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4486mm'}, {'key':..."
1418,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4824mm'}, {'key':..."

In [112]:
#apply function to all values in list column
new_car_specs_list_2_CHE= new_car_specs_data_2_CHE["list"].apply(extract_key_value_dicts2)
new_car_specs_list_2_CHE

0       {'Length': '3995mm', 'Width': '1790', 'Height'...
1       {'Length': '3675mm', 'Width': '1475mm', 'Heigh...
2       {'Length': '3994mm', 'Width': '1758', 'Height'...
3       {'Length': '3585mm', 'Width': '1595mm', 'Heigh...
4       {'Length': '3955mm', 'Width': '1694mm', 'Heigh...
                              ...
1414    {'Length': '3840mm', 'Width': '1735mm', 'Heigh...
1415    {'Length': '4315mm', 'Width': '1822mm', 'Heigh...
1416    {'Length': '3994mm', 'Width': '1811mm', 'Heigh...
1417    {'Length': '4486mm', 'Width': '1839mm', 'Heigh...
1418    {'Length': '4824mm', 'Width': '1828mm', 'Heigh...
Name: list, Length: 1419, dtype: object

In [113]:
new_car_specs_list_2_CHE= pd.json_normalize(new_car_specs_list_2_CHE)
new_car_specs_list_2_CHE

,Length,Width,Height,Wheel Base,Kerb Weight,Front Tread,Rear Tread,Gross Weight,Ground Clearance Unladen,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,3995mm,1790,1642,2500,1465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3675mm,1475mm,1800mm,2350mm,943kg,1280mm,1290mm,1540kg,NaN,NaN,NaN,NaN,NaN,NaN
2,3994mm,1758,1572,2500,1014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3585mm,1595mm,1550mm,2380mm,860kg,1400mm,1385mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3955mm,1694mm,1544mm,2530mm,1042kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,3840mm,1735mm,1530mm,2450mm,865Kg,1530mm,1530mm,1315kg,NaN,NaN,NaN,NaN,NaN,NaN
1415,4315mm,1822mm,1695mm,2673mm,1210,1560mm,1567mm,1777kg,NaN,NaN,NaN,NaN,NaN,NaN
1416,3994mm,1811mm,1607mm,2498mm,1252Kg,1540 mm,1530 mm,NaN,209 mm,NaN,NaN,NaN,NaN,NaN
1417,4486mm,1839mm,1672mm,2677mm,1720kg,1578mm,1568mm,2250kg,NaN,NaN,NaN,NaN,NaN,NaN
1418,4824mm,1828mm,1508mm,2920 mm,1720,1541 mm,1581 mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
#flatten the nested dict in '2:miscellaneous'
new_car_specs_data_3_CHE= pd.json_normalize(new_car_specs_data_CHE[2])
new_car_specs_data_3_CHE

,heading,subHeading,list
0,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '7-Speed DCT'}, ..."
1,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
2,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
3,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
4,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
...,...,...,...
1414,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5'}, {'key': 'S..."
1415,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 speed'}, {'ke..."
1416,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1417,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '7 Speed'}, {'ke..."
1418,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '8 Speed'}, {'ke..."

In [115]:
#apply function to all values in list column
new_car_specs_list_3_CHE= new_car_specs_data_3_CHE["list"].apply(extract_key_value_dicts2)
new_car_specs_list_3_CHE= pd.json_normalize(new_car_specs_list_3_CHE)
new_car_specs_list_3_CHE

,Gear Box,Drive Type,Seating Capacity,Steering Type,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration
0,7-Speed DCT,FWD,5,Electric,Disc,Drum,"Tubeless, Radial",16,5,392,NaN,NaN,NaN
1,5 Speed,RWD,7,Manual,Ventilated Disc,Drum,Tubeless Tyres,NaN,5,540-liters,4.5 metres,145 Kmph,15.7 Seconds
2,5 Speed,NaN,5,Electronic,Disc,Drum,"Tubeless,Radial",16,5,336,5.0,NaN,11.7
3,5 Speed,FWD,5,Power,Ventilated Disc,Drum,Tubeless,NaN,5,225-litres,4.7 metres,165 Kmph,14.3 Seconds
4,5 Speed,FWD,5,Power,Disc,Drum,"Tubeless,Radial",15,5,354-litres,5.1 meters,172 Kmph,13.7 Seconds
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,5,NaN,5,Power,Disc,Drum,Tubeless,NaN,5,268-litres,4.8 Meters,NaN,NaN
1415,5 speed,FWD,5,Power,Disc,Drum,"Tubeless,Radial",16,5,475-litres,5.2 metres,156 Kmph,13.9 Seconds
1416,6 Speed,FWD,5,Power,Disc,Drum,Tubeless Radial Tyres,16,5,350,5.1m,154.19 kmph,NaN
1417,7 Speed,AWD,5,Electric,Disc,Disc,Tubeless Radial Tyres,18,5,615,5.75meters,NaN,NaN
1418,8 Speed,RWD,5,Power,Disc,Disc,Run-Flat,18,4,520,5.5 metres,226 Kmph,7.7 Seconds

In [116]:
# concat chennai car details
chennai_cars_data=pd.concat([new_car_detail_che,new_car_overview_CHE,new_car_specs_top_CHE,new_car_specs_list_1_CHE,new_car_specs_list_2_CHE,new_car_specs_list_3_CHE],axis=1)
chennai_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Steering Type,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,Electric,Disc,Drum,"Tubeless, Radial",16,5,392,NaN,NaN,NaN
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,Manual,Ventilated Disc,Drum,Tubeless Tyres,NaN,5,540-liters,4.5 metres,145 Kmph,15.7 Seconds
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,Electronic,Disc,Drum,"Tubeless,Radial",16,5,336,5.0,NaN,11.7
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,Power,Ventilated Disc,Drum,Tubeless,NaN,5,225-litres,4.7 metres,165 Kmph,14.3 Seconds
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,Power,Disc,Drum,"Tubeless,Radial",15,5,354-litres,5.1 meters,172 Kmph,13.7 Seconds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,Power,Disc,Drum,Tubeless,NaN,5,268-litres,4.8 Meters,NaN,NaN
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,Power,Disc,Drum,"Tubeless,Radial",16,5,475-litres,5.2 metres,156 Kmph,13.9 Seconds
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,Power,Disc,Drum,Tubeless Radial Tyres,16,5,350,5.1m,154.19 kmph,NaN
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,Electric,Disc,Disc,Tubeless Radial Tyres,18,5,615,5.75meters,NaN,NaN
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,Power,Disc,Disc,Run-Flat,18,4,520,5.5 metres,226 Kmph,7.7 Seconds

In [117]:
#add city column to the data frame
chennai_cars_data["City"]="Chennai"
#final dataframe
chennai_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration,City
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,Disc,Drum,"Tubeless, Radial",16,5,392,NaN,NaN,NaN,Chennai
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,Ventilated Disc,Drum,Tubeless Tyres,NaN,5,540-liters,4.5 metres,145 Kmph,15.7 Seconds,Chennai
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,Disc,Drum,"Tubeless,Radial",16,5,336,5.0,NaN,11.7,Chennai
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,Ventilated Disc,Drum,Tubeless,NaN,5,225-litres,4.7 metres,165 Kmph,14.3 Seconds,Chennai
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,Disc,Drum,"Tubeless,Radial",15,5,354-litres,5.1 meters,172 Kmph,13.7 Seconds,Chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,Disc,Drum,Tubeless,NaN,5,268-litres,4.8 Meters,NaN,NaN,Chennai
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,Disc,Drum,"Tubeless,Radial",16,5,475-litres,5.2 metres,156 Kmph,13.9 Seconds,Chennai
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,Disc,Drum,Tubeless Radial Tyres,16,5,350,5.1m,154.19 kmph,NaN,Chennai
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,Disc,Disc,Tubeless Radial Tyres,18,5,615,5.75meters,NaN,NaN,Chennai
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,Disc,Disc,Run-Flat,18,4,520,5.5 metres,226 Kmph,7.7 Seconds,Chennai

## delhi cars

In [118]:
df_delhi=pd.read_excel(r"C:/Users/jagadesh/Documents/Python Scripts/car dekho - used car prediction/unstructured_files/delhi_cars.xlsx")
df_delhi

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1481,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1482,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1483,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1484,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'I...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [119]:
#drop column from dataframe
df_delhi.drop(columns=["car_links"], inplace=True, axis=1)
df_delhi

,new_car_detail,new_car_overview,new_car_feature,new_car_specs
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
...,...,...,...,...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1481,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1482,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1483,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1484,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'I...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."

In [120]:
#view new_car_detail-detail
df_delhi["new_car_detail"]

0       {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
                              ...
1480    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1481    {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
1482    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1483    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1484    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
Name: new_car_detail, Length: 1485, dtype: object

In [121]:
df_delhi["new_car_detail"][0]

"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '10,000', 'transmission': 'Automatic', 'ownerNo': 1, 'owner': '1st Owner', 'oem': 'Kia', 'model': 'Kia Seltos', 'modelYear': 2022, 'centralVariantId': 7121, 'variantName': 'GTX Plus Diesel AT', 'price': 'â‚¹ 19 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

In [122]:
df_delhi["new_car_detail_dict"]=df_delhi["new_car_detail"].apply(ast.literal_eval)
df_delhi["new_car_detail_dict"]

0       {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
                              ...
1480    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1481    {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
1482    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
1483    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1484    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
Name: new_car_detail_dict, Length: 1485, dtype: object

In [123]:
#flatten the nested dict to dataframe
new_car_detail_dl= pd.json_normalize(df_delhi["new_car_detail_dict"])
new_car_detail_dl

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,7121,GTX Plus Diesel AT,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,1449,1.6 VTVT S,â‚¹ 7.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,6837,200,â‚¹ 56 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,10403,VXI,â‚¹ 5.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,5362,1.6 VTVT E Plus,â‚¹ 7.65 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,5627,i-VTEC CVT V,â‚¹ 9 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,8000,HTK Plus BSVI,â‚¹ 9.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,1832,1.6 SX VTVT,â‚¹ 4.18 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,6440,1.6 SX Option Diesel,â‚¹ 11.95 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,9298,Savvy 6 Str 4x4,â‚¹ 46.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

## new_car_overview

In [124]:
df_delhi["new_car_overview"]

0       {'heading': 'Car overview', 'top': [{'key': 'R...
1       {'heading': 'Car overview', 'top': [{'key': 'R...
2       {'heading': 'Car overview', 'top': [{'key': 'R...
3       {'heading': 'Car overview', 'top': [{'key': 'R...
4       {'heading': 'Car overview', 'top': [{'key': 'R...
                              ...
1480    {'heading': 'Car overview', 'top': [{'key': 'R...
1481    {'heading': 'Car overview', 'top': [{'key': 'R...
1482    {'heading': 'Car overview', 'top': [{'key': 'R...
1483    {'heading': 'Car overview', 'top': [{'key': 'R...
1484    {'heading': 'Car overview', 'top': [{'key': 'I...
Name: new_car_overview, Length: 1485, dtype: object

In [125]:
df_delhi["new_car_overview"][0]

"{'heading': 'Car overview', 'top': [{'key': 'Registration Year', 'value': '2022', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'}, {'key': 'Insurance Validity', 'value': 'Third Party insurance', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'}, {'key': 'Fuel Type', 'value': 'Diesel', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'}, {'key': 'Seats', 'value': '5 Seats', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'}, {'key': 'Kms Driven', 'value': '10,000 Kms', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'}, {'key': 'Ownership', 'value': 'First Owner', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'}, {'key': 'Engine Displacement', 'value': '1493 cc', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'}, {'key': 'Transmission', 'value': 'Automatic', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'}, {'key': 'Year of Manufacture', 'value': 2022, 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}], 'bottomData': None}"

In [126]:
#convert string to dict
df_delhi["new_car_overview_dict"]=df_delhi["new_car_overview"].apply(ast.literal_eval)
df_delhi["new_car_overview_dict"]

0       {'heading': 'Car overview', 'top': [{'key': 'R...
1       {'heading': 'Car overview', 'top': [{'key': 'R...
2       {'heading': 'Car overview', 'top': [{'key': 'R...
3       {'heading': 'Car overview', 'top': [{'key': 'R...
4       {'heading': 'Car overview', 'top': [{'key': 'R...
                              ...
1480    {'heading': 'Car overview', 'top': [{'key': 'R...
1481    {'heading': 'Car overview', 'top': [{'key': 'R...
1482    {'heading': 'Car overview', 'top': [{'key': 'R...
1483    {'heading': 'Car overview', 'top': [{'key': 'R...
1484    {'heading': 'Car overview', 'top': [{'key': 'I...
Name: new_car_overview_dict, Length: 1485, dtype: object

In [127]:
#flatten the nested dict to dataframe
new_car_overview_DL= pd.json_normalize(df_delhi["new_car_overview_dict"])
new_car_overview_DL

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Jan 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2017',...",None
...,...,...,...
1480,Car overview,"[{'key': 'Registration Year', 'value': '2019',...",None
1481,Car overview,"[{'key': 'Registration Year', 'value': '2021',...",None
1482,Car overview,"[{'key': 'Registration Year', 'value': '2011',...",None
1483,Car overview,"[{'key': 'Registration Year', 'value': 'Oct 20...",None
1484,Car overview,"[{'key': 'Insurance Validity', 'value': 'Third...",None

In [128]:
#drop bottomData from dataframe
new_car_overview_DL.drop(columns=["bottomData"], inplace=True, axis=1)
new_car_overview_DL

           heading                                                top
0     Car overview  [{'key': 'Registration Year', 'value': '2022',...
1     Car overview  [{'key': 'Registration Year', 'value': 'May 20...
2     Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
3     Car overview  [{'key': 'Registration Year', 'value': 'Jan 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2017',...
...            ...                                                ...
1480  Car overview  [{'key': 'Registration Year', 'value': '2019',...
1481  Car overview  [{'key': 'Registration Year', 'value': '2021',...
1482  Car overview  [{'key': 'Registration Year', 'value': '2011',...
1483  Car overview  [{'key': 'Registration Year', 'value': 'Oct 20...
1484  Car overview  [{'key': 'Insurance Validity', 'value': 'Third...

[1485 rows x 2 columns]

In [129]:
#apply function to all values in top column
new_car_overview_DL= new_car_overview_DL['top'].apply(extract_key_value_dicts)
new_car_overview_DL

0       {'Registration Year': '2022', 'Insurance Valid...
1       {'Registration Year': 'May 2016', 'Insurance V...
2       {'Registration Year': 'Dec 2020', 'Insurance V...
3       {'Registration Year': 'Jan 2019', 'Insurance V...
4       {'Registration Year': '2017', 'Insurance Valid...
                              ...
1480    {'Registration Year': '2019', 'Insurance Valid...
1481    {'Registration Year': '2021', 'Insurance Valid...
1482    {'Registration Year': '2011', 'Insurance Valid...
1483    {'Registration Year': 'Oct 2019', 'Insurance V...
1484    {'Insurance Validity': 'Third Party insurance'...
Name: top, Length: 1485, dtype: object

In [130]:
new_car_overview_DL=pd.json_normalize(new_car_overview_DL)
new_car_overview_DL

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,Ownership,Engine Displacement,Transmission,Year of Manufacture,RTO
0,2022,Third Party insurance,Diesel,5 Seats,"10,000 Kms",First Owner,1493 cc,Automatic,2022,NaN
1,May 2016,Zero Dep,Petrol,5 Seats,"57,437 Kms",Second Owner,1591 cc,Manual,2016,HR51
2,Dec 2020,Comprehensive,Petrol,5 Seats,"8,000 Kms",First Owner,1991 cc,Automatic,2020,DL01
3,Jan 2019,Comprehensive,Petrol,5 Seats,"28,151 Kms",Second Owner,1197 cc,Manual,2018,DL4C
4,2017,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2017,DL8C
...,...,...,...,...,...,...,...,...,...,...
1480,2019,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1497 cc,Automatic,2019,DL4C
1481,2021,Third Party insurance,Petrol,5 Seats,"20,000 Kms",First Owner,1197 cc,Manual,2021,NaN
1482,2011,Third Party insurance,Petrol,5 Seats,"60,000 Kms",First Owner,1591 cc,Manual,2011,NaN
1483,Oct 2019,Third Party insurance,Diesel,5 Seats,"38,000 Kms",First Owner,1582 cc,Manual,2019,HR26
1484,NaN,Third Party insurance,Diesel,6 Seats,"7,000 Kms",NaN,1996 cc,Automatic,2023,NaN

## new_car_feature

In [131]:
df_delhi["new_car_feature"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1480    {'heading': 'Features', 'top': [{'value': 'Pow...
1481    {'heading': 'Features', 'top': [{'value': 'Pow...
1482    {'heading': 'Features', 'top': [{'value': 'Pow...
1483    {'heading': 'Features', 'top': [{'value': 'Pow...
1484    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature, Length: 1485, dtype: object

In [132]:
df_delhi["new_car_feature"][0]

"{'heading': 'Features', 'top': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Anti Lock Braking System'}, {'value': 'Brake Assist'}, {'value': 'Radio'}], 'data': [{'heading': 'Comfort & Convenience', 'subHeading': 'Comfort', 'list': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Power Windows Rear'}, {'value': 'Air Quality Control'}, {'value': 'Low Fuel Warning Light'}, {'value': 'Accessory Power Outlet'}, {'value': 'Trunk Light'}, {'value': 'Rear Reading Lamp'}, {'value': 'Rear Seat Headrest'}, {'value': 'Rear Seat Centre Arm Rest'}, {'value': 'Height Adjustable Front Seat Belts'}, {'value': 'Cup Holders Rear'}, {'value': 'Seat Lumbar Support'}, {'value': 'Multifunction Steering Wheel'}, {'value': 'Cruise Control'}, {'value': 'Rear ACVents'}, {'value': 'Navigation System'}, {'value': 'Smart Access Card Entry'}, {'value': 'Engine Start Stop Button'}, {'value': 'Voice Control'}, {'value': 'Steering Wheel Gearshift Paddles'}, {'value': 'Drive Modes'}, {'value': 'Remote Engine Start Stop'}, {'value': 'Adjustable Headrest'}]}, {'heading': 'Interior', 'subHeading': 'Interior', 'list': [{'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Steering'}, {'value': 'Digital Odometer'}, {'value': 'Tachometer'}, {'value': 'Electronic Multi Tripmeter'}, {'value': 'Leather Seats'}, {'value': 'Leather Steering Wheel'}, {'value': 'Glove Compartment'}, {'value': 'Digital Clock'}, {'value': 'Driving Experience Control Eco'}, {'value': 'Height Adjustable Driver Seat'}, {'value': 'Ventilated Seats'}, {'value': 'Leather Wrap Gear Shift Selector'}]}, {'heading': 'Exterior', 'subHeading': 'Exterior', 'list': [{'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Power Adjustable Exterior Rear View Mirror'}, {'value': 'Electric Folding Rear View Mirror'}, {'value': 'Rain Sensing Wiper'}, {'value': 'Rear Window Wiper'}, {'value': 'Rear Window Washer'}, {'value': 'Rear Window Defogger'}, {'value': 'Alloy Wheels'}, {'value': 'Integrated Antenna'}, {'value': 'Rear Spoiler'}, {'value': 'Sun Roof'}, {'value': 'Moon Roof'}, {'value': 'Outside Rear View Mirror Turn Indicators'}, {'value': 'Chrome Garnish'}, {'value': 'Roof Rail'}, {'value': 'LEDDRLs'}, {'value': 'LEDHeadlights'}, {'value': 'LEDTaillights'}, {'value': 'LEDFog Lamps'}]}, {'heading': 'Safety', 'subHeading': 'Safety', 'list': [{'value': 'Anti Lock Braking System'}, {'value': 'Brake Assist'}, {'value': 'Centeral Locking'}, {'value': 'Power Door Locks'}, {'value': 'Child Safety Locks'}, {'value': 'Driver Air Bag'}, {'value': 'Passenger Air Bag'}, {'value': 'Side Air Bag Front'}, {'value': 'Day Night Rear View Mirror'}, {'value': 'Passenger Side Rear View Mirror'}, {'value': 'Rear Seat Belts'}, {'value': 'Seat Belt Warning'}, {'value': 'Vehicle Stability Control System'}, {'value': 'Traction Control'}, {'value': 'Adjustable Seats'}, {'value': 'Keyless Entry'}, {'value': 'Engine Immobilizer'}, {'value': 'Engine Check Warning'}, {'value': 'Tyre Pressure Monitor'}, {'value': 'Crash Sensor'}, {'value': 'Automatic Head Lamps'}, {'value': 'Ebd'}, {'value': 'Follow Me Home Headlamps'}, {'value': 'Rear Camera'}, {'value': 'Anti Pinch Power Windows'}, {'value': 'Speed Sensing Auto Door Lock'}, {'value': 'Isofix Child Seat Mounts'}, {'value': 'Heads Up Display'}, {'value': 'Pretensioners And Force Limiter Seatbelts'}, {'value': 'Blind Spot Monitor'}, {'value': 'Hill Assist'}, {'value': 'View360Camera'}, {'value': 'No Of Airbags'}, {'value': 'Eletronic Stability Control'}]}, {'heading': 'Entertainment & Communication', 'subHeading': 'Entertainment', 'list': [{'value': 'Radio'}, {'value': 'Speakers Front'}, {'value': 'Speakers Rear'}, {'value': 'Integrated2Din Audio'}, {'value': 'Bluetooth'}, {'value': 'Touch Screen'}, {'value': 'Number Of Speaker'}, {'value': 'Touch Screen Size'}, {'value': 'Apple Car Play'}, {'value': 'Android Auto'}, {'value': 'Wireless Phone Charging'}]}], 'commonIcon': 'https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg'}"

In [133]:
#convert string to dict
df_delhi["new_car_feature_dict"]= df_delhi["new_car_feature"].apply(ast.literal_eval)

In [134]:
df_delhi["new_car_feature_dict"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1480    {'heading': 'Features', 'top': [{'value': 'Pow...
1481    {'heading': 'Features', 'top': [{'value': 'Pow...
1482    {'heading': 'Features', 'top': [{'value': 'Pow...
1483    {'heading': 'Features', 'top': [{'value': 'Pow...
1484    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature_dict, Length: 1485, dtype: object

In [135]:
new_car_feature_DL= pd.json_normalize(df_delhi["new_car_feature_dict"])
new_car_feature_DL

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1481,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1482,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1483,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1484,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [136]:
#drop column from dataframe
new_car_feature_DL.drop(columns=["commonIcon"], inplace=True, axis=1)
new_car_feature_DL

,heading,top,data
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
...,...,...,...
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1481,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1482,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1483,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1484,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."

In [137]:
new_car_feature_DL["top"][0]

[{'value': 'Power Steering'},
 {'value': 'Power Windows Front'},
 {'value': 'Air Conditioner'},
 {'value': 'Heater'},
 {'value': 'Adjustable Head Lights'},
 {'value': 'Fog Lights Front'},
 {'value': 'Anti Lock Braking System'},
 {'value': 'Brake Assist'},
 {'value': 'Radio'}]

In [138]:
#apply function to all values in top column
new_car_feature_top_2= new_car_feature_DL["top"].apply(extract_key_value_dicts1)
new_car_feature_top_2

0       {0: 'Power Steering', 1: 'Power Windows Front'...
1       {0: 'Power Steering', 1: 'Power Windows Front'...
2       {0: 'Power Steering', 1: 'Power Windows Front'...
3       {0: 'Power Steering', 1: 'Power Windows Front'...
4       {0: 'Power Steering', 1: 'Power Windows Front'...
                              ...
1480    {0: 'Power Steering', 1: 'Power Windows Front'...
1481    {0: 'Power Steering', 1: 'Power Windows Front'...
1482    {0: 'Power Steering', 1: 'Power Windows Front'...
1483    {0: 'Power Steering', 1: 'Power Windows Front'...
1484    {0: 'Power Steering', 1: 'Power Windows Front'...
Name: top, Length: 1485, dtype: object

In [139]:
new_car_feature_top_2=pd.json_normalize(new_car_feature_top_2)
new_car_feature_top_2

,0,1,2,3,4,5,6,7,8
0,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Radio
1,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
2,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Radio
3,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Brake Assist,Radio
4,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Cd Player
...,...,...,...,...,...,...,...,...,...
1480,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
1481,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
1482,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
1483,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
1484,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Radio

In [140]:
new_car_feature_DL["data"][0]

[{'heading': 'Comfort & Convenience',
  'subHeading': 'Comfort',
  'list': [{'value': 'Power Steering'},
   {'value': 'Power Windows Front'},
   {'value': 'Power Windows Rear'},
   {'value': 'Air Quality Control'},
   {'value': 'Low Fuel Warning Light'},
   {'value': 'Accessory Power Outlet'},
   {'value': 'Trunk Light'},
   {'value': 'Rear Reading Lamp'},
   {'value': 'Rear Seat Headrest'},
   {'value': 'Rear Seat Centre Arm Rest'},
   {'value': 'Height Adjustable Front Seat Belts'},
   {'value': 'Cup Holders Rear'},
   {'value': 'Seat Lumbar Support'},
   {'value': 'Multifunction Steering Wheel'},
   {'value': 'Cruise Control'},
   {'value': 'Rear ACVents'},
   {'value': 'Navigation System'},
   {'value': 'Smart Access Card Entry'},
   {'value': 'Engine Start Stop Button'},
   {'value': 'Voice Control'},
   {'value': 'Steering Wheel Gearshift Paddles'},
   {'value': 'Drive Modes'},
   {'value': 'Remote Engine Start Stop'},
   {'value': 'Adjustable Headrest'}]},
 {'heading': 'Interior',
  'subHeading': 'Interior',
  'list': [{'value': 'Air Conditioner'},
   {'value': 'Heater'},
   {'value': 'Adjustable Steering'},
   {'value': 'Digital Odometer'},
   {'value': 'Tachometer'},
   {'value': 'Electronic Multi Tripmeter'},
   {'value': 'Leather Seats'},
   {'value': 'Leather Steering Wheel'},
   {'value': 'Glove Compartment'},
   {'value': 'Digital Clock'},
   {'value': 'Driving Experience Control Eco'},
   {'value': 'Height Adjustable Driver Seat'},
   {'value': 'Ventilated Seats'},
   {'value': 'Leather Wrap Gear Shift Selector'}]},
 {'heading': 'Exterior',
  'subHeading': 'Exterior',
  'list': [{'value': 'Adjustable Head Lights'},
   {'value': 'Fog Lights Front'},
   {'value': 'Power Adjustable Exterior Rear View Mirror'},
   {'value': 'Electric Folding Rear View Mirror'},
   {'value': 'Rain Sensing Wiper'},
   {'value': 'Rear Window Wiper'},
   {'value': 'Rear Window Washer'},
   {'value': 'Rear Window Defogger'},
   {'value': 'Alloy Wheels'},
   {'value': 'Integrated Antenna'},
   {'value': 'Rear Spoiler'},
   {'value': 'Sun Roof'},
   {'value': 'Moon Roof'},
   {'value': 'Outside Rear View Mirror Turn Indicators'},
   {'value': 'Chrome Garnish'},
   {'value': 'Roof Rail'},
   {'value': 'LEDDRLs'},
   {'value': 'LEDHeadlights'},
   {'value': 'LEDTaillights'},
   {'value': 'LEDFog Lamps'}]},
 {'heading': 'Safety',
  'subHeading': 'Safety',
  'list': [{'value': 'Anti Lock Braking System'},
   {'value': 'Brake Assist'},
   {'value': 'Centeral Locking'},
   {'value': 'Power Door Locks'},
   {'value': 'Child Safety Locks'},
   {'value': 'Driver Air Bag'},
   {'value': 'Passenger Air Bag'},
   {'value': 'Side Air Bag Front'},
   {'value': 'Day Night Rear View Mirror'},
   {'value': 'Passenger Side Rear View Mirror'},
   {'value': 'Rear Seat Belts'},
   {'value': 'Seat Belt Warning'},
   {'value': 'Vehicle Stability Control System'},
   {'value': 'Traction Control'},
   {'value': 'Adjustable Seats'},
   {'value': 'Keyless Entry'},
   {'value': 'Engine Immobilizer'},
   {'value': 'Engine Check Warning'},
   {'value': 'Tyre Pressure Monitor'},
   {'value': 'Crash Sensor'},
   {'value': 'Automatic Head Lamps'},
   {'value': 'Ebd'},
   {'value': 'Follow Me Home Headlamps'},
   {'value': 'Rear Camera'},
   {'value': 'Anti Pinch Power Windows'},
   {'value': 'Speed Sensing Auto Door Lock'},
   {'value': 'Isofix Child Seat Mounts'},
   {'value': 'Heads Up Display'},
   {'value': 'Pretensioners And Force Limiter Seatbelts'},
   {'value': 'Blind Spot Monitor'},
   {'value': 'Hill Assist'},
   {'value': 'View360Camera'},
   {'value': 'No Of Airbags'},
   {'value': 'Eletronic Stability Control'}]},
 {'heading': 'Entertainment & Communication',
  'subHeading': 'Entertainment',
  'list': [{'value': 'Radio'},
   {'value': 'Speakers Front'},
   {'value': 'Speakers Rear'},
   {'value': 'Integrated2Din Audio'},
   {'value': 'Bluetooth'},
   {'value': 'Touch Screen'},
   {'value': 'Number Of Speaker'},
   {'value': 'Touch Screen Size'},
   {'value': 'Apple Car Play'},
   {'value': 'Android Auto'},
   {'value': 'Wireless Phone Charging'}]}]

In [141]:
# flatten the nexted dict to dataframe
new_car_feature_data_DL=pd.json_normalize(new_car_feature_DL["data"])
new_car_feature_data_DL

,0,1,2,3,4
0,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
2,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
3,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
4,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
...,...,...,...,...,...
1480,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1481,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1482,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1483,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1484,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."

In [142]:
#flatten the nested dict to dataframe
new_car_feature_data_1_DL = pd.json_normalize(new_car_feature_data_DL[0])
new_car_feature_data_1_DL

,heading,subHeading,list
0,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
2,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
3,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
4,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
...,...,...,...
1480,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1481,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1482,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1483,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1484,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."

In [143]:
new_car_feature_data_1_DL["list"][0]

[{'value': 'Power Steering'},
 {'value': 'Power Windows Front'},
 {'value': 'Power Windows Rear'},
 {'value': 'Air Quality Control'},
 {'value': 'Low Fuel Warning Light'},
 {'value': 'Accessory Power Outlet'},
 {'value': 'Trunk Light'},
 {'value': 'Rear Reading Lamp'},
 {'value': 'Rear Seat Headrest'},
 {'value': 'Rear Seat Centre Arm Rest'},
 {'value': 'Height Adjustable Front Seat Belts'},
 {'value': 'Cup Holders Rear'},
 {'value': 'Seat Lumbar Support'},
 {'value': 'Multifunction Steering Wheel'},
 {'value': 'Cruise Control'},
 {'value': 'Rear ACVents'},
 {'value': 'Navigation System'},
 {'value': 'Smart Access Card Entry'},
 {'value': 'Engine Start Stop Button'},
 {'value': 'Voice Control'},
 {'value': 'Steering Wheel Gearshift Paddles'},
 {'value': 'Drive Modes'},
 {'value': 'Remote Engine Start Stop'},
 {'value': 'Adjustable Headrest'}]

In [144]:
#apply function to all values in list column
new_car_feature_list_1_DL= new_car_feature_data_1_DL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_1_DL=pd.json_normalize(new_car_feature_list_1_DL)
new_car_feature_list_1_DL

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Rear Reading Lamp,Rear Seat Headrest,Rear Seat Centre Arm Rest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,...,Drive Modes,Remote Engine Start Stop,Remote Climate Control,Adjustable Headrest,NaN,NaN,NaN,NaN,NaN,NaN
3,Power Steering,Power Windows Front,Power Windows Rear,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Multifunction Steering Wheel,Gear Shift Indicator,Adjustable Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,Power Steering,Power Windows Front,Power Windows Rear,Low Fuel Warning Light,Accessory Power Outlet,Rear Reading Lamp,Rear Seat Headrest,Multifunction Steering Wheel,Rear ACVents,Gear Shift Indicator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,Battery Saver,Lane Change Indicator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,...,Power Boot,Hands Free Tailgate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
#flatten the nested dict to dataframe
new_car_feature_data_2_DL = pd.json_normalize(new_car_feature_data_DL[1])
new_car_feature_data_2_DL

       heading subHeading                                               list
0     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
2     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
3     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
4     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
...        ...        ...                                                ...
1480  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1481  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1482  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1483  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1484  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...

[1485 rows x 3 columns]

In [146]:
#apply function to all values in list column
new_car_feature_list_2_DL= new_car_feature_data_2_DL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2_DL=pd.json_normalize(new_car_feature_list_2_DL)
new_car_feature_list_2_DL

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Driving Experience Control Eco,Height Adjustable Driver Seat,Ventilated Seats,Leather Wrap Gear Shift Selector,NaN,NaN,NaN,NaN
1,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Adjustable Steering,Tachometer,Fabric Upholstery,Glove Compartment,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
1484,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Driving Experience Control Eco,Ventilated Seats,Dual Tone Dashboard,NaN,NaN,NaN,NaN,NaN

In [147]:
#flatten the nested dict to dataframe
new_car_feature_data_3_DL = pd.json_normalize(new_car_feature_data_DL[2])
new_car_feature_data_3_DL

       heading subHeading                                               list
0     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
2     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
3     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
4     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
...        ...        ...                                                ...
1480  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1481  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1482  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1483  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1484  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...

[1485 rows x 3 columns]

In [148]:
#apply function to all values in list column
new_car_feature_list_3_DL= new_car_feature_data_3_DL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_3_DL=pd.json_normalize(new_car_feature_list_3_DL)
new_car_feature_list_3_DL

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,...,LEDDRLs,LEDHeadlights,LEDTaillights,LEDFog Lamps,NaN,NaN,NaN,NaN,NaN,NaN
1,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Power Antenna,Tinted Glass,Outside Rear View Mirror Turn Indicators,Smoke Headlamps,Roof Rail,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Sun Roof,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Wheel Covers,Power Antenna,Outside Rear View Mirror Turn Indicators,LEDTaillights,Halogen Headlamps,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Wheel Covers,Integrated Antenna,Tinted Glass,Outside Rear View Mirror Turn Indicators,Smoke Headlamps,Roof Rail,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Outside Rear View Mirror Turn Indicators,Chrome Grille,Chrome Garnish,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Defogger,Wheel Covers,Integrated Antenna,Tinted Glass,Rear Spoiler,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Defogger,Alloy Wheels,Power Antenna,Outside Rear View Mirror Turn Indicators,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Rear Spoiler,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,Adjustable Head Lights,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,...,LEDDRLs,LEDHeadlights,LEDTaillights,Cornering Headlamps,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
#flatten the nested dict to dataframe
new_car_feature_data_4_DL = pd.json_normalize(new_car_feature_data_DL[3])
new_car_feature_data_4_DL

     heading subHeading                                               list
0     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
2     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
3     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
4     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
...      ...        ...                                                ...
1480  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1481  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1482  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1483  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1484  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...

[1485 rows x 3 columns]

In [150]:
#apply function to all values in list column
new_car_feature_list_4_DL= new_car_feature_data_4_DL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_4_DL=pd.json_normalize(new_car_feature_list_4_DL)
new_car_feature_list_4_DL

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Side Air Bag Rear,...,Impact Sensing Auto Door Lock,View360Camera,No Of Airbags,Eletronic Stability Control,NaN,NaN,NaN,NaN,NaN,NaN
3,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Side Air Bag Rear,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
#flatten the nested dict to dataframe
new_car_feature_data_5_DL = pd.json_normalize(new_car_feature_data_DL[4])
new_car_feature_data_5_DL

,heading,subHeading,list
0,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
2,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
3,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
4,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
...,...,...,...
1480,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1481,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1482,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1483,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1484,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."

In [152]:
#apply function to all values in list column
new_car_feature_list_5_DL= new_car_feature_data_5_DL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_5_DL=pd.json_normalize(new_car_feature_list_5_DL)
new_car_feature_list_5_DL

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Bluetooth,Touch Screen,Number Of Speaker,Touch Screen Size,Apple Car Play,Android Auto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,Rear Entertainment System,Apple Car Play,...,Wireless Phone Charging,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Radio,Speakers Front,Speakers Rear,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Internal Storage,Number Of Speaker,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Bluetooth,Touch Screen,Number Of Speaker,Touch Screen Size,Apple Car Play,Android Auto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Cd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,Radio,Speakers Front,Speakers Rear,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,Touch Screen Size,Apple Car Play,...,Wireless Phone Charging,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## new_car_specs

In [153]:
#convert string to dict
df_delhi["new_car_specs_dict"]= df_delhi["new_car_specs"].apply(ast.literal_eval)
df_delhi["new_car_specs_dict"]

0       {'heading': 'Specifications', 'top': [{'key': ...
1       {'heading': 'Specifications', 'top': [{'key': ...
2       {'heading': 'Specifications', 'top': [{'key': ...
3       {'heading': 'Specifications', 'top': [{'key': ...
4       {'heading': 'Specifications', 'top': [{'key': ...
                              ...
1480    {'heading': 'Specifications', 'top': [{'key': ...
1481    {'heading': 'Specifications', 'top': [{'key': ...
1482    {'heading': 'Specifications', 'top': [{'key': ...
1483    {'heading': 'Specifications', 'top': [{'key': ...
1484    {'heading': 'Specifications', 'top': [{'key': ...
Name: new_car_specs_dict, Length: 1485, dtype: object

In [154]:
#flatten the nested dict to dataframe
new_car_specs_DL= pd.json_normalize(df_delhi["new_car_specs_dict"])
new_car_specs_DL

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '18 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '12.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1480,Specifications,"[{'key': 'Mileage', 'value': '18 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
1481,Specifications,"[{'key': 'Mileage', 'value': '18.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1482,Specifications,"[{'key': 'Mileage', 'value': '17.01 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1483,Specifications,"[{'key': 'Mileage', 'value': '20.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1484,Specifications,"[{'key': 'Mileage', 'value': '12.04 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",

In [155]:
#drop column from dataframe
new_car_specs_DL.drop(columns=["commonIcon"], inplace=True, axis=1)
new_car_specs_DL

,heading,top,data
0,Specifications,"[{'key': 'Mileage', 'value': '18 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
1,Specifications,"[{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
2,Specifications,"[{'key': 'Mileage', 'value': '12.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
3,Specifications,"[{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
4,Specifications,"[{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
...,...,...,...
1480,Specifications,"[{'key': 'Mileage', 'value': '18 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
1481,Specifications,"[{'key': 'Mileage', 'value': '18.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1482,Specifications,"[{'key': 'Mileage', 'value': '17.01 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1483,Specifications,"[{'key': 'Mileage', 'value': '20.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1484,Specifications,"[{'key': 'Mileage', 'value': '12.04 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."

In [156]:
new_car_specs_DL["top"][0]

[{'key': 'Mileage', 'value': '18 kmpl'},
 {'key': 'Engine', 'value': '1493 CC'},
 {'key': 'Max Power', 'value': '113.43bhp'},
 {'key': 'Torque', 'value': '250Nm'},
 {'key': 'Wheel Size', 'value': '17'},
 {'key': 'Seats', 'value': '5'}]

In [157]:
#apply function to all values in top column
new_car_specs_top_DL=new_car_specs_DL["top"].apply(extract_key_value_dicts2)
new_car_specs_top_DL= pd.json_normalize(new_car_specs_top_DL)
new_car_specs_top_DL

         Mileage   Engine  Max Power    Torque Wheel Size Seats
0        18 kmpl  1493 CC  113.43bhp     250Nm         17     5
1     15.29 kmpl  1591 CC   121.3bhp     151Nm        NaN     5
2     12.74 kmpl  1991 CC     197bhp     320nm         19     5
3     22.38 kmpl  1197 CC   88.50bhp     113Nm        NaN     5
4     15.29 kmpl  1591 CC   121.3bhp     151Nm        NaN     5
...          ...      ...        ...       ...        ...   ...
1480     18 kmpl  1497 CC   117.6bhp     145Nm         15     5
1481   18.4 kmpl  1197 CC   81.86bhp     115Nm        NaN     5
1482  17.01 kmpl  1591 CC   121.3bhp   154.9Nm         16     5
1483   20.5 kmpl  1582 CC   126.2bhp  259.87NM         17     5
1484  12.04 kmpl  1996 CC  212.55bhp   478.5Nm         19     6

[1485 rows x 6 columns]

In [158]:
new_car_specs_DL["data"][0]

[{'heading': 'Engine and Transmission',
  'subHeading': 'Engine',
  'list': [{'key': 'Color', 'value': 'Gray'},
   {'key': 'Engine Type', 'value': '1.5 L CRDi VGT'},
   {'key': 'Displacement', 'value': '1493'},
   {'key': 'Max Power', 'value': '113.43bhp@4000rpm'},
   {'key': 'Max Torque', 'value': '250Nm@1500-2750rpm'},
   {'key': 'No of Cylinder', 'value': 4},
   {'key': 'Values per Cylinder', 'value': 4},
   {'key': 'Fuel Suppy System', 'value': 'CRDi'},
   {'key': 'Turbo Charger', 'value': 'Yes'}]},
 {'heading': 'Dimensions & Capacity',
  'subHeading': 'Dimensions',
  'list': [{'key': 'Length', 'value': '4315mm'},
   {'key': 'Width', 'value': '1800mm'},
   {'key': 'Height', 'value': '1645mm'},
   {'key': 'Wheel Base', 'value': '2610mm'},
   {'key': 'Kerb Weight', 'value': '1540'}]},
 {'heading': 'Miscellaneous',
  'subHeading': 'Miscellaneous',
  'list': [{'key': 'Gear Box', 'value': '6-Speed'},
   {'key': 'Drive Type', 'value': 'FWD'},
   {'key': 'Seating Capacity', 'value': '5'},
   {'key': 'Steering Type', 'value': 'Electric'},
   {'key': 'Front Brake Type', 'value': 'Disc'},
   {'key': 'Rear Brake Type', 'value': 'Disc'},
   {'key': 'Tyre Type', 'value': 'Tubeless, Radial'},
   {'key': 'Alloy Wheel Size', 'value': '17'},
   {'key': 'No Door Numbers', 'value': '5'},
   {'key': 'Cargo Volumn', 'value': '433'}]}]

In [159]:
#apply function to all values in data column
new_car_specs_data_DL=pd.json_normalize(new_car_specs_DL["data"])
new_car_specs_data_DL

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1480,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1481,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1482,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1483,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1484,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [160]:
#flatten the nested dict to dataframe
new_car_specs_data_1_DL= pd.json_normalize(new_car_specs_data_DL[0])
new_car_specs_data_1_DL

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Gray'}, {'key': 'E..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Grey'}, {'key': 'E..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
...,...,...,...
1480,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1481,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1482,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1483,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
1484,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Grey'}, {'key': 'E..."

In [161]:
#apply function to all values in top column
new_car_specs_list_1_DL=new_car_specs_data_1_DL["list"].apply(extract_key_value_dicts2)
new_car_specs_list_1_DL= pd.json_normalize(new_car_specs_list_1_DL)
new_car_specs_list_1_DL

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Fuel Suppy System,Turbo Charger,Value Configuration,Super Charger,BoreX Stroke,Compression Ratio
0,Gray,1.5 L CRDi VGT,1493,113.43bhp@4000rpm,250Nm@1500-2750rpm,4.0,4.0,CRDi,Yes,NaN,NaN,NaN,NaN
1,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN
2,Grey,M 264 petrol engine,1991,197bhp@5500-6100rpm,320nm@1650-4000rpm,4.0,4.0,EFI,No,NaN,NaN,NaN,NaN
3,Silver,K Series Dual jet,1197,88.50bhp@6000rpm,113Nm@4400rpm,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,White,VTVT Petrol Engine,1591,121.3bhp@6400rpm,151Nm@4850rpm,4.0,4.0,MPFI,No,DOHC,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,Others,i VTEC Engine,1497,117.6bhp@6600rpm,145Nm@4600rpm,4.0,4.0,PGM-Fi,No,SOHC,No,73.0 X 89.4 mm,10.3:1
1481,Others,SMARTSTREAM G1.2,1197,81.86bhp@6000rpm,115Nm@4200rpm,4.0,4.0,MPI,No,NaN,NaN,NaN,NaN
1482,Others,VTVT Petrol Engine,1591,121.3bhp@6300rpm,154.9Nm@4200rpm,4.0,4.0,MPFI,No,DOHC,No,77.0mm X 85.44mm,10.5;1
1483,Silver,U2 CRDI VGT Engine,1582,126.2bhp@4000rpm,259.87NM@1500-3000rpm,4.0,4.0,CRDi,Yes,DOHC,No,NaN,NaN
1484,Grey,DIESEL 2.0L TWIN TURBO,1996,212.55bhp@4000rpm,478.5Nm@1500-2400rpm,4.0,4.0,NaN,Twin,NaN,NaN,NaN,NaN

In [162]:
#flatten the nested dict to dataframe
new_car_specs_data_2_DL= pd.json_normalize(new_car_specs_data_DL[1])
new_car_specs_data_2_DL

,heading,subHeading,list
0,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4315mm'}, {'key':..."
1,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4270mm'}, {'key':..."
2,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4658mm'}, {'key':..."
3,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3845mm'}, {'key':..."
4,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4270mm'}, {'key':..."
...,...,...,...
1480,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4440mm'}, {'key':..."
1481,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."
1482,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4375mm'}, {'key':..."
1483,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4270mm'}, {'key':..."
1484,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4985mm'}, {'key':..."

In [163]:
#apply function to all values in top column
new_car_specs_list_2_DL=new_car_specs_data_2_DL["list"].apply(extract_key_value_dicts2)
new_car_specs_list_2_DL= pd.json_normalize(new_car_specs_list_2_DL)
new_car_specs_list_2_DL

,Length,Width,Height,Wheel Base,Kerb Weight,Gross Weight,Front Tread,Rear Tread,Ground Clearance Unladen,Gear Box,...,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers
0,4315mm,1800mm,1645mm,2610mm,1540,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4270mm,1780mm,1630mm,2590mm,"1,310",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4658mm,1890mm,1644mm,2873mm,1585,2360kg,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3845mm,1735,1530,2450,875-905,1335,1530,1530,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4270mm,1780mm,1630mm,2590mm,"1,300",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,4440mm,1695mm,1495mm,2600mm,1080kg,1455kg,1490mm,1480mm,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,3995mm,1790,1642,2500,1192,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,4375mm,1700mm,1475mm,2570mm,1260,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,4270mm,1780mm,1665mm,2590mm,1340,NaN,NaN,NaN,190mm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,4985mm,1926mm,1867mm,2950mm,2600,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [164]:
#flatten the nested dict to dataframe
new_car_specs_data_3_DL= pd.json_normalize(new_car_specs_data_DL[2])
new_car_specs_data_3_DL

,heading,subHeading,list
0,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6-Speed'}, {'ke..."
1,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
2,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '9 speed Tronic'..."
3,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
4,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
...,...,...,...
1480,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': 'CVT'}, {'key': ..."
1481,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
1482,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1483,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1484,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '8 Speed'}, {'ke..."

In [165]:
#apply function to all values in top column
new_car_specs_list_3_DL=new_car_specs_data_3_DL["list"].apply(extract_key_value_dicts2)
new_car_specs_list_3_DL= pd.json_normalize(new_car_specs_list_3_DL)
new_car_specs_list_3_DL

,Gear Box,Drive Type,Seating Capacity,Steering Type,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration
0,6-Speed,FWD,5,Electric,Disc,Disc,"Tubeless, Radial",17,5,433,NaN,NaN,NaN
1,6 Speed,FWD,5,Power,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds
2,9 speed Tronic,AWD,5,Power,Disc,Disc,"Tubeless,Radial",19,5,550-litres,NaN,217 Kmph,NaN
3,5-Speed,NaN,5,Electric,Disc,Drum,"Radial, Tubeless",NaN,5,268,4.8,NaN,NaN
4,6 Speed,FWD,5,Power,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,CVT,FWD,5,Power,Ventilated Disc,Drum,"Tubeless,Radial",15,4,510,5.3 metres,195 Kmph,10 Seconds
1481,5-Speed,FWD,5,Electric,Disc,Drum,"Tubeless, Radial",NaN,5,392,NaN,NaN,NaN
1482,5 Speed,FWD,5,Power,Disc,Drum,"Tubeless,Radial",16,4,465-litre,5.2 metres,196km/hr,10.5 Seconds
1483,6 Speed,FWD,5,Power,Disc,Drum,Tubeless,17,5,400,5.3 metres,160.58kmph,10.83 s
1484,8 Speed,4x4,6,Electric,Disc,Disc,"Tubeless, Radial",19,5,NaN,NaN,NaN,NaN

In [166]:
# concat delhi car details
delhi_cars_data=pd.concat([new_car_detail_dl,new_car_overview_DL,new_car_specs_top_DL,new_car_specs_list_1_DL,new_car_specs_list_2_DL,new_car_specs_list_3_DL],axis=1)
delhi_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Steering Type,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,Electric,Disc,Disc,"Tubeless, Radial",17,5,433,NaN,NaN,NaN
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,Power,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,Power,Disc,Disc,"Tubeless,Radial",19,5,550-litres,NaN,217 Kmph,NaN
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,Electric,Disc,Drum,"Radial, Tubeless",NaN,5,268,4.8,NaN,NaN
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,Power,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,...,Power,Ventilated Disc,Drum,"Tubeless,Radial",15,4,510,5.3 metres,195 Kmph,10 Seconds
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,...,Electric,Disc,Drum,"Tubeless, Radial",NaN,5,392,NaN,NaN,NaN
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,...,Power,Disc,Drum,"Tubeless,Radial",16,4,465-litre,5.2 metres,196km/hr,10.5 Seconds
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,...,Power,Disc,Drum,Tubeless,17,5,400,5.3 metres,160.58kmph,10.83 s
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,...,Electric,Disc,Disc,"Tubeless, Radial",19,5,NaN,NaN,NaN,NaN

In [167]:
# add city column to dataframe
delhi_cars_data["City"]="Delhi"
# final dataframe
delhi_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Turning Radius,Top Speed,Acceleration,City
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,Disc,Disc,"Tubeless, Radial",17,5,433,NaN,NaN,NaN,Delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds,Delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,Disc,Disc,"Tubeless,Radial",19,5,550-litres,NaN,217 Kmph,NaN,Delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,Disc,Drum,"Radial, Tubeless",NaN,5,268,4.8,NaN,NaN,Delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,Disc,Drum,Tubeless,NaN,5,400-litres,5.3 metres,165 Kmph,10.5 Seconds,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,...,Ventilated Disc,Drum,"Tubeless,Radial",15,4,510,5.3 metres,195 Kmph,10 Seconds,Delhi
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,...,Disc,Drum,"Tubeless, Radial",NaN,5,392,NaN,NaN,NaN,Delhi
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,...,Disc,Drum,"Tubeless,Radial",16,4,465-litre,5.2 metres,196km/hr,10.5 Seconds,Delhi
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,...,Disc,Drum,Tubeless,17,5,400,5.3 metres,160.58kmph,10.83 s,Delhi
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,...,Disc,Disc,"Tubeless, Radial",19,5,NaN,NaN,NaN,NaN,Delhi

## hyderabad cars

In [168]:
#convert excel file to data frame
df_hyderabad=pd.read_excel(r"C:/Users/jagadesh/Documents/Python Scripts/car dekho - used car prediction/unstructured_files/hyderabad_cars.xlsx")
df_hyderabad

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1478,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1481,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1482,"{'it': 0, 'ft': 'Diesel', 'bt': 'MUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [169]:
#drop column 'car_links' from dataframe
df_hyderabad.drop(columns=["car_links"],inplace= True,axis=1)
df_hyderabad

,new_car_detail,new_car_overview,new_car_feature,new_car_specs
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
...,...,...,...,...
1478,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1480,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1481,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1482,"{'it': 0, 'ft': 'Diesel', 'bt': 'MUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."

## new_car_detail

In [170]:
#view new_car_detail_hyderabad
df_hyderabad["new_car_detail"]

0       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
                              ...
1478    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1479    {'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...
1480    {'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...
1481    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1482    {'it': 0, 'ft': 'Diesel', 'bt': 'MUV', 'km': '...
Name: new_car_detail, Length: 1483, dtype: object

In [171]:
df_hyderabad["new_car_detail"][0]

"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', 'km': '20,000', 'transmission': 'Automatic', 'ownerNo': 1, 'owner': '1st Owner', 'oem': 'Volkswagen', 'model': 'Volkswagen Polo', 'modelYear': 2022, 'centralVariantId': 7746, 'variantName': '1.0 TSI Highline Plus AT', 'price': 'â‚¹ 10.44 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

In [172]:
#convert string to dictionary
df_hyderabad["new_car_detail_dict"]=df_hyderabad["new_car_detail"].apply(ast.literal_eval)
df_hyderabad["new_car_detail_dict"]

0       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
                              ...
1478    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1479    {'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...
1480    {'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...
1481    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
1482    {'it': 0, 'ft': 'Diesel', 'bt': 'MUV', 'km': '...
Name: new_car_detail_dict, Length: 1483, dtype: object

In [173]:
#flatten the nested dict to dataframe
new_car_detail_hd=pd.json_normalize(df_hyderabad["new_car_detail_dict"])
new_car_detail_hd

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,7746,1.0 TSI Highline Plus AT,â‚¹ 10.44 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,1502,Era Plus,â‚¹ 2.60 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,9153,S BSVI,â‚¹ 9.55 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,3970,1.2 Alpha,â‚¹ 6.71 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,8074,LX 4-Str Hard Top AT BSVI,â‚¹ 19 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,3823,W8 2WD,â‚¹ 7 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,5007,3.0 Litre S Premium Luxury,â‚¹ 20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,250,520d Luxury Line,â‚¹ 35 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,6500,1.5 Revotorq XMA,â‚¹ 8.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,2294,2.5 ZX Diesel 7 Seater,â‚¹ 15 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

# new_car_overview

In [174]:
df_hyderabad["new_car_overview"]

0       {'heading': 'Car overview', 'top': [{'key': 'R...
1       {'heading': 'Car overview', 'top': [{'key': 'R...
2       {'heading': 'Car overview', 'top': [{'key': 'R...
3       {'heading': 'Car overview', 'top': [{'key': 'R...
4       {'heading': 'Car overview', 'top': [{'key': 'R...
                              ...
1478    {'heading': 'Car overview', 'top': [{'key': 'R...
1479    {'heading': 'Car overview', 'top': [{'key': 'R...
1480    {'heading': 'Car overview', 'top': [{'key': 'R...
1481    {'heading': 'Car overview', 'top': [{'key': 'R...
1482    {'heading': 'Car overview', 'top': [{'key': 'R...
Name: new_car_overview, Length: 1483, dtype: object

In [175]:
df_hyderabad["new_car_overview"][0]

"{'heading': 'Car overview', 'top': [{'key': 'Registration Year', 'value': '2022', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'}, {'key': 'Insurance Validity', 'value': 'Third Party insurance', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'}, {'key': 'Fuel Type', 'value': 'Petrol', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'}, {'key': 'Seats', 'value': '5 Seats', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'}, {'key': 'Kms Driven', 'value': '20,000 Kms', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'}, {'key': 'RTO', 'value': 'TS04', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'}, {'key': 'Ownership', 'value': 'First Owner', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'}, {'key': 'Engine Displacement', 'value': '999 cc', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'}, {'key': 'Transmission', 'value': 'Automatic', 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'}, {'key': 'Year of Manufacture', 'value': 2022, 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}], 'bottomData': None}"

In [176]:
#convert string to dictionary
df_hyderabad["new_car_overview_dict"]=df_hyderabad["new_car_overview"].apply(ast.literal_eval)
df_hyderabad["new_car_overview_dict"]

0       {'heading': 'Car overview', 'top': [{'key': 'R...
1       {'heading': 'Car overview', 'top': [{'key': 'R...
2       {'heading': 'Car overview', 'top': [{'key': 'R...
3       {'heading': 'Car overview', 'top': [{'key': 'R...
4       {'heading': 'Car overview', 'top': [{'key': 'R...
                              ...
1478    {'heading': 'Car overview', 'top': [{'key': 'R...
1479    {'heading': 'Car overview', 'top': [{'key': 'R...
1480    {'heading': 'Car overview', 'top': [{'key': 'R...
1481    {'heading': 'Car overview', 'top': [{'key': 'R...
1482    {'heading': 'Car overview', 'top': [{'key': 'R...
Name: new_car_overview_dict, Length: 1483, dtype: object

In [177]:
#flatten the nested dict to dataframe
new_car_overview_HD=pd.json_normalize(df_hyderabad["new_car_overview_dict"])
new_car_overview_HD

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Oct 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': '2023',...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Mar 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
...,...,...,...
1478,Car overview,"[{'key': 'Registration Year', 'value': '2013',...",None
1479,Car overview,"[{'key': 'Registration Year', 'value': '2014',...",None
1480,Car overview,"[{'key': 'Registration Year', 'value': '2018',...",None
1481,Car overview,"[{'key': 'Registration Year', 'value': '2019',...",None
1482,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None

In [178]:
#drop column 'bottomData' from dataframe
new_car_overview_HD.drop(columns=["bottomData"],inplace=True,axis=1)
new_car_overview_HD

           heading                                                top
0     Car overview  [{'key': 'Registration Year', 'value': '2022',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Oct 20...
2     Car overview  [{'key': 'Registration Year', 'value': '2023',...
3     Car overview  [{'key': 'Registration Year', 'value': 'Mar 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2022',...
...            ...                                                ...
1478  Car overview  [{'key': 'Registration Year', 'value': '2013',...
1479  Car overview  [{'key': 'Registration Year', 'value': '2014',...
1480  Car overview  [{'key': 'Registration Year', 'value': '2018',...
1481  Car overview  [{'key': 'Registration Year', 'value': '2019',...
1482  Car overview  [{'key': 'Registration Year', 'value': '2015',...

[1483 rows x 2 columns]

In [179]:
new_car_overview_HD["top"][0]

[{'key': 'Registration Year',
  'value': '2022',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'},
 {'key': 'Insurance Validity',
  'value': 'Third Party insurance',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/insuranceValidity.svg'},
 {'key': 'Fuel Type',
  'value': 'Petrol',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/fuel.svg'},
 {'key': 'Seats',
  'value': '5 Seats',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/seats.svg'},
 {'key': 'Kms Driven',
  'value': '20,000 Kms',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/kmsDriven.svg'},
 {'key': 'RTO',
  'value': 'TS04',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/rto.svg'},
 {'key': 'Ownership',
  'value': 'First Owner',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/ownership.svg'},
 {'key': 'Engine Displacement',
  'value': '999 cc',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/engineDisplacement.svg'},
 {'key': 'Transmission',
  'value': 'Automatic',
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/transmission.svg'},
 {'key': 'Year of Manufacture',
  'value': 2022,
  'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/yearManufacture.svg'}]

In [180]:
#apply function to all values in 'top' column
new_car_overview_HD=new_car_overview_HD["top"].apply(extract_key_value_dicts)
new_car_overview_HD

0       {'Registration Year': '2022', 'Insurance Valid...
1       {'Registration Year': 'Oct 2014', 'Insurance V...
2       {'Registration Year': '2023', 'Insurance Valid...
3       {'Registration Year': 'Mar 2017', 'Insurance V...
4       {'Registration Year': '2022', 'Insurance Valid...
                              ...
1478    {'Registration Year': '2013', 'Insurance Valid...
1479    {'Registration Year': '2014', 'Insurance Valid...
1480    {'Registration Year': '2018', 'Insurance Valid...
1481    {'Registration Year': '2019', 'Insurance Valid...
1482    {'Registration Year': '2015', 'Insurance Valid...
Name: top, Length: 1483, dtype: object

In [181]:
new_car_overview_HD[0]

{'Registration Year': '2022',
 'Insurance Validity': 'Third Party insurance',
 'Fuel Type': 'Petrol',
 'Seats': '5 Seats',
 'Kms Driven': '20,000 Kms',
 'RTO': 'TS04',
 'Ownership': 'First Owner',
 'Engine Displacement': '999 cc',
 'Transmission': 'Automatic',
 'Year of Manufacture': 2022}

In [182]:
new_car_overview_HD=pd.json_normalize(new_car_overview_HD)
new_car_overview_HD

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2022,Third Party insurance,Petrol,5 Seats,"20,000 Kms",TS04,First Owner,999 cc,Automatic,2022.0
1,Oct 2014,Third Party insurance,Petrol,5 Seats,"85,582 Kms",TS09,Second Owner,814 cc,Manual,2014.0
2,2023,Third Party insurance,Petrol,5 Seats,"10,000 Kms",NaN,First Owner,1197 cc,Manual,2023.0
3,Mar 2017,Third Party insurance,Petrol,5 Seats,"50,750 Kms",TS07,First Owner,1197 cc,Manual,2017.0
4,2022,Third Party insurance,Petrol,4 Seats,"10,000 Kms",NaN,First Owner,1997 cc,Automatic,2022.0
...,...,...,...,...,...,...,...,...,...,...
1478,2013,Third Party insurance,Diesel,7 Seats,"60,000 Kms",TS09,First Owner,2179 cc,Manual,2013.0
1479,2014,Third Party insurance,Diesel,5 Seats,"50,000 Kms",NaN,First Owner,2993 cc,Automatic,2014.0
1480,2018,Third Party insurance,Diesel,5 Seats,"1,20,000 Kms",TS09,Third Owner,1995 cc,Automatic,2018.0
1481,2019,Third Party insurance,Diesel,5 Seats,"50,000 Kms",TS08,Second Owner,1497 cc,Automatic,2019.0
1482,2015,Third Party insurance,Diesel,7 Seats,"1,00,000 Kms",NaN,First Owner,2494 cc,Manual,2015.0

## new_car_feature

In [183]:
#view 'new_car_feature' from data frame
df_hyderabad["new_car_feature"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1478    {'heading': 'Features', 'top': [{'value': 'Pow...
1479    {'heading': 'Features', 'top': [{'value': 'Pow...
1480    {'heading': 'Features', 'top': [{'value': 'Pow...
1481    {'heading': 'Features', 'top': [{'value': 'Pow...
1482    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature, Length: 1483, dtype: object

In [184]:
df_hyderabad["new_car_feature"][0]

"{'heading': 'Features', 'top': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Anti Lock Braking System'}, {'value': 'Centeral Locking'}, {'value': 'Radio'}], 'data': [{'heading': 'Comfort & Convenience', 'subHeading': 'Comfort', 'list': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Power Windows Rear'}, {'value': 'Remote Trunk Opener'}, {'value': 'Low Fuel Warning Light'}, {'value': 'Accessory Power Outlet'}, {'value': 'Vanity Mirror'}, {'value': 'Rear Seat Headrest'}, {'value': 'Cup Holders Front'}, {'value': 'Seat Lumbar Support'}, {'value': 'Multifunction Steering Wheel'}, {'value': 'Cruise Control'}, {'value': 'Rear ACVents'}, {'value': 'Glove Box Cooling'}, {'value': 'Voice Control'}, {'value': 'Gear Shift Indicator'}, {'value': 'Lane Change Indicator'}, {'value': 'Adjustable Headrest'}]}, {'heading': 'Interior', 'subHeading': 'Interior', 'list': [{'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Steering'}, {'value': 'Digital Odometer'}, {'value': 'Tachometer'}, {'value': 'Electronic Multi Tripmeter'}, {'value': 'Fabric Upholstery'}, {'value': 'Leather Steering Wheel'}, {'value': 'Glove Compartment'}, {'value': 'Digital Clock'}, {'value': 'Height Adjustable Driver Seat'}, {'value': 'Dual Tone Dashboard'}, {'value': 'Leather Wrap Gear Shift Selector'}]}, {'heading': 'Exterior', 'subHeading': 'Exterior', 'list': [{'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Fog Lights Rear'}, {'value': 'Power Adjustable Exterior Rear View Mirror'}, {'value': 'Electric Folding Rear View Mirror'}, {'value': 'Rain Sensing Wiper'}, {'value': 'Rear Window Wiper'}, {'value': 'Rear Window Washer'}, {'value': 'Rear Window Defogger'}, {'value': 'Alloy Wheels'}, {'value': 'Power Antenna'}, {'value': 'Integrated Antenna'}, {'value': 'Outside Rear View Mirror Turn Indicators'}, {'value': 'Cornering Headlamps'}, {'value': 'Halogen Headlamps'}]}, {'heading': 'Safety', 'subHeading': 'Safety', 'list': [{'value': 'Anti Lock Braking System'}, {'value': 'Centeral Locking'}, {'value': 'Power Door Locks'}, {'value': 'Child Safety Locks'}, {'value': 'Driver Air Bag'}, {'value': 'Passenger Air Bag'}, {'value': 'Day Night Rear View Mirror'}, {'value': 'Passenger Side Rear View Mirror'}, {'value': 'Halogen Headlamps'}, {'value': 'Rear Seat Belts'}, {'value': 'Seat Belt Warning'}, {'value': 'Side Impact Beams'}, {'value': 'Front Impact Beams'}, {'value': 'Vehicle Stability Control System'}, {'value': 'Adjustable Seats'}, {'value': 'Keyless Entry'}, {'value': 'Centrally Mounted Fuel Tank'}, {'value': 'Engine Immobilizer'}, {'value': 'Engine Check Warning'}, {'value': 'Crash Sensor'}, {'value': 'Ebd'}, {'value': 'Anti Theft Device'}, {'value': 'Anti Pinch Power Windows'}, {'value': 'Speed Sensing Auto Door Lock'}, {'value': 'Isofix Child Seat Mounts'}, {'value': 'Pretensioners And Force Limiter Seatbelts'}, {'value': 'Hill Assist'}, {'value': 'Impact Sensing Auto Door Lock'}, {'value': 'No Of Airbags'}, {'value': 'Eletronic Stability Control'}]}, {'heading': 'Entertainment & Communication', 'subHeading': 'Entertainment', 'list': [{'value': 'Radio'}, {'value': 'Speakers Front'}, {'value': 'Speakers Rear'}, {'value': 'Usb Auxiliary Input'}, {'value': 'Bluetooth'}, {'value': 'Touch Screen'}, {'value': 'Number Of Speaker'}, {'value': 'Apple Car Play'}, {'value': 'Android Auto'}, {'value': 'Mirror Link'}]}], 'commonIcon': 'https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg'}"

In [185]:
df_hyderabad["new_car_feature_dict"]=df_hyderabad["new_car_feature"].apply(ast.literal_eval)
df_hyderabad["new_car_feature_dict"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1478    {'heading': 'Features', 'top': [{'value': 'Pow...
1479    {'heading': 'Features', 'top': [{'value': 'Pow...
1480    {'heading': 'Features', 'top': [{'value': 'Pow...
1481    {'heading': 'Features', 'top': [{'value': 'Pow...
1482    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature_dict, Length: 1483, dtype: object

In [186]:
#flatten the nested dict to dataframe
new_car_feature_HD=pd.json_normalize(df_hyderabad["new_car_feature_dict"])
new_car_feature_HD

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1478,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1479,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1481,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1482,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [187]:
#drop column 'commonIcon' from dataframe
new_car_feature_HD.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_feature_HD

,heading,top,data
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
...,...,...,...
1478,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1479,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1480,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1481,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1482,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."

In [188]:
new_car_feature_HD["top"][0]

[{'value': 'Power Steering'},
 {'value': 'Power Windows Front'},
 {'value': 'Air Conditioner'},
 {'value': 'Heater'},
 {'value': 'Adjustable Head Lights'},
 {'value': 'Fog Lights Front'},
 {'value': 'Anti Lock Braking System'},
 {'value': 'Centeral Locking'},
 {'value': 'Radio'}]

In [189]:
#apply function to all values of top column in dataframe
new_car_feature_top_3= new_car_feature_HD["top"].apply(extract_key_value_dicts1)
new_car_feature_top_3

0       {0: 'Power Steering', 1: 'Power Windows Front'...
1       {0: 'Power Steering', 1: 'Power Windows Front'...
2       {0: 'Power Steering', 1: 'Power Windows Front'...
3       {0: 'Power Steering', 1: 'Power Windows Front'...
4       {0: 'Power Steering', 1: 'Power Windows Front'...
                              ...
1478    {0: 'Power Steering', 1: 'Power Windows Front'...
1479    {0: 'Power Steering', 1: 'Power Windows Front'...
1480    {0: 'Power Steering', 1: 'Power Windows Front'...
1481    {0: 'Power Steering', 1: 'Power Windows Front'...
1482    {0: 'Power Steering', 1: 'Power Windows Front'...
Name: top, Length: 1483, dtype: object

In [190]:
new_car_feature_top_3=pd.json_normalize(new_car_feature_top_3)
new_car_feature_top_3

,0,1,2,3,4,5,6,7,8
0,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
1,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Child Safety Locks,Driver Air Bag,NaN
2,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Brake Assist,Radio
3,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Radio
4,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Radio
...,...,...,...,...,...,...,...,...,...
1478,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
1479,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Brake Assist,Cd Player
1480,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Changer
1481,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Radio
1482,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player

In [191]:
new_car_feature_HD["data"]

0       [{'heading': 'Comfort & Convenience', 'subHead...
1       [{'heading': 'Comfort & Convenience', 'subHead...
2       [{'heading': 'Comfort & Convenience', 'subHead...
3       [{'heading': 'Comfort & Convenience', 'subHead...
4       [{'heading': 'Comfort & Convenience', 'subHead...
                              ...
1478    [{'heading': 'Comfort & Convenience', 'subHead...
1479    [{'heading': 'Comfort & Convenience', 'subHead...
1480    [{'heading': 'Comfort & Convenience', 'subHead...
1481    [{'heading': 'Comfort & Convenience', 'subHead...
1482    [{'heading': 'Comfort & Convenience', 'subHead...
Name: data, Length: 1483, dtype: object

In [192]:
new_car_feature_HD["data"][0]

[{'heading': 'Comfort & Convenience',
  'subHeading': 'Comfort',
  'list': [{'value': 'Power Steering'},
   {'value': 'Power Windows Front'},
   {'value': 'Power Windows Rear'},
   {'value': 'Remote Trunk Opener'},
   {'value': 'Low Fuel Warning Light'},
   {'value': 'Accessory Power Outlet'},
   {'value': 'Vanity Mirror'},
   {'value': 'Rear Seat Headrest'},
   {'value': 'Cup Holders Front'},
   {'value': 'Seat Lumbar Support'},
   {'value': 'Multifunction Steering Wheel'},
   {'value': 'Cruise Control'},
   {'value': 'Rear ACVents'},
   {'value': 'Glove Box Cooling'},
   {'value': 'Voice Control'},
   {'value': 'Gear Shift Indicator'},
   {'value': 'Lane Change Indicator'},
   {'value': 'Adjustable Headrest'}]},
 {'heading': 'Interior',
  'subHeading': 'Interior',
  'list': [{'value': 'Air Conditioner'},
   {'value': 'Heater'},
   {'value': 'Adjustable Steering'},
   {'value': 'Digital Odometer'},
   {'value': 'Tachometer'},
   {'value': 'Electronic Multi Tripmeter'},
   {'value': 'Fabric Upholstery'},
   {'value': 'Leather Steering Wheel'},
   {'value': 'Glove Compartment'},
   {'value': 'Digital Clock'},
   {'value': 'Height Adjustable Driver Seat'},
   {'value': 'Dual Tone Dashboard'},
   {'value': 'Leather Wrap Gear Shift Selector'}]},
 {'heading': 'Exterior',
  'subHeading': 'Exterior',
  'list': [{'value': 'Adjustable Head Lights'},
   {'value': 'Fog Lights Front'},
   {'value': 'Fog Lights Rear'},
   {'value': 'Power Adjustable Exterior Rear View Mirror'},
   {'value': 'Electric Folding Rear View Mirror'},
   {'value': 'Rain Sensing Wiper'},
   {'value': 'Rear Window Wiper'},
   {'value': 'Rear Window Washer'},
   {'value': 'Rear Window Defogger'},
   {'value': 'Alloy Wheels'},
   {'value': 'Power Antenna'},
   {'value': 'Integrated Antenna'},
   {'value': 'Outside Rear View Mirror Turn Indicators'},
   {'value': 'Cornering Headlamps'},
   {'value': 'Halogen Headlamps'}]},
 {'heading': 'Safety',
  'subHeading': 'Safety',
  'list': [{'value': 'Anti Lock Braking System'},
   {'value': 'Centeral Locking'},
   {'value': 'Power Door Locks'},
   {'value': 'Child Safety Locks'},
   {'value': 'Driver Air Bag'},
   {'value': 'Passenger Air Bag'},
   {'value': 'Day Night Rear View Mirror'},
   {'value': 'Passenger Side Rear View Mirror'},
   {'value': 'Halogen Headlamps'},
   {'value': 'Rear Seat Belts'},
   {'value': 'Seat Belt Warning'},
   {'value': 'Side Impact Beams'},
   {'value': 'Front Impact Beams'},
   {'value': 'Vehicle Stability Control System'},
   {'value': 'Adjustable Seats'},
   {'value': 'Keyless Entry'},
   {'value': 'Centrally Mounted Fuel Tank'},
   {'value': 'Engine Immobilizer'},
   {'value': 'Engine Check Warning'},
   {'value': 'Crash Sensor'},
   {'value': 'Ebd'},
   {'value': 'Anti Theft Device'},
   {'value': 'Anti Pinch Power Windows'},
   {'value': 'Speed Sensing Auto Door Lock'},
   {'value': 'Isofix Child Seat Mounts'},
   {'value': 'Pretensioners And Force Limiter Seatbelts'},
   {'value': 'Hill Assist'},
   {'value': 'Impact Sensing Auto Door Lock'},
   {'value': 'No Of Airbags'},
   {'value': 'Eletronic Stability Control'}]},
 {'heading': 'Entertainment & Communication',
  'subHeading': 'Entertainment',
  'list': [{'value': 'Radio'},
   {'value': 'Speakers Front'},
   {'value': 'Speakers Rear'},
   {'value': 'Usb Auxiliary Input'},
   {'value': 'Bluetooth'},
   {'value': 'Touch Screen'},
   {'value': 'Number Of Speaker'},
   {'value': 'Apple Car Play'},
   {'value': 'Android Auto'},
   {'value': 'Mirror Link'}]}]

In [193]:
new_car_feature_data_HD=pd.json_normalize(new_car_feature_HD["data"])
new_car_feature_data_HD

,0,1,2,3,4
0,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",None
2,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
3,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
4,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
...,...,...,...,...,...
1478,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1479,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1480,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1481,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1482,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."

In [194]:
#flatten the nested dict to dataframe
new_car_feature_data_1_HD=pd.json_normalize(new_car_feature_data_HD[0])
new_car_feature_data_1_HD

,heading,subHeading,list
0,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
2,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
3,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
4,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
...,...,...,...
1478,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1479,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1480,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1481,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1482,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."

In [195]:
#apply function to all values in list column
new_car_feature_list_1_HD= new_car_feature_data_1_HD["list"].apply(extract_key_value_dicts1)
new_car_feature_list_1_HD

0       {0: 'Power Steering', 1: 'Power Windows Front'...
1       {0: 'Power Steering', 1: 'Power Windows Front'...
2       {0: 'Power Steering', 1: 'Power Windows Front'...
3       {0: 'Power Steering', 1: 'Power Windows Front'...
4       {0: 'Power Steering', 1: 'Power Windows Front'...
                              ...
1478    {0: 'Power Steering', 1: 'Power Windows Front'...
1479    {0: 'Power Steering', 1: 'Power Windows Front'...
1480    {0: 'Power Steering', 1: 'Power Windows Front'...
1481    {0: 'Power Steering', 1: 'Power Windows Front'...
1482    {0: 'Power Steering', 1: 'Power Windows Front'...
Name: list, Length: 1483, dtype: object

In [196]:
new_car_feature_list_1_HD=pd.json_normalize(new_car_feature_list_1_HD)
new_car_feature_list_1_HD

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,Seat Lumbar Support,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Power Steering,Power Windows Front,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Rear Seat Headrest,Cup Holders Front,Gear Shift Indicator,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Power Steering,Power Windows Front,Power Windows Rear,Low Fuel Warning Light,Accessory Power Outlet,Rear Seat Headrest,Multifunction Steering Wheel,Rear ACVents,Voice Control,Battery Saver,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Power Steering,Power Windows Front,Low Fuel Warning Light,Accessory Power Outlet,Rear Seat Headrest,Seat Lumbar Support,Multifunction Steering Wheel,Cruise Control,Navigation System,Voice Control,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Rear Reading Lamp,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Reading Lamp,...,Steering Wheel Gearshift Paddles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,...,Voice Control,Steering Wheel Gearshift Paddles,Tailgate Ajar,Lane Change Indicator,Drive Modes,Remote Climate Control,Adjustable Headrest,NaN,NaN,NaN
1481,Power Steering,Power Windows Front,Power Windows Rear,Low Fuel Warning Light,Accessory Power Outlet,Rear Seat Headrest,Cup Holders Front,Multifunction Steering Wheel,Voice Control,Drive Modes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
new_car_feature_data_2_HD= pd.json_normalize(new_car_feature_data_HD[1])
new_car_feature_data_2_HD

       heading subHeading                                               list
0     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
2     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
3     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
4     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
...        ...        ...                                                ...
1478  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1479  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1480  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1481  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1482  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...

[1483 rows x 3 columns]

In [198]:
#apply function to all values in the list column
new_car_feature_list_2_HD = new_car_feature_data_2_HD["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2_HD = pd.json_normalize(new_car_feature_list_2_HD )
new_car_feature_list_2_HD

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,Dual Tone Dashboard,Leather Wrap Gear Shift Selector,NaN,NaN,NaN
1,Air Conditioner,Heater,Digital Odometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Dual Tone Dashboard,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Cigarette Lighter,NaN,NaN,NaN,NaN,NaN
1479,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN
1480,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,Driving Experience Control Eco,Height Adjustable Driver Seat,Dual Tone Dashboard,NaN
1481,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,Driving Experience Control Eco,NaN,NaN,NaN,NaN,NaN
1482,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Cigarette Lighter,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN

In [199]:
#flatten the nested dict to dataframe
new_car_feature_data_3_HD= pd.json_normalize(new_car_feature_data_HD[2])
new_car_feature_data_3_HD

       heading subHeading                                               list
0     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
2     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
3     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
4     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
...        ...        ...                                                ...
1478  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1479  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1480  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1481  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1482  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...

[1483 rows x 3 columns]

In [200]:
#apply function to all values in the list column
new_car_feature_list_3_HD= new_car_feature_data_3_HD["list"].apply(extract_key_value_dicts1)
new_car_feature_list_3_HD = pd.json_normalize(new_car_feature_list_3_HD)
new_car_feature_list_3_HD

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,Adjustable Head Lights,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Power Antenna,Tinted Glass,Rear Spoiler,Chrome Grille,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Wheel Covers,Integrated Antenna,Chrome Grille,Roof Rail,Halogen Headlamps,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Tinted Glass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Rear Window Defogger,Alloy Wheels,Integrated Antenna,LEDTaillights,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Defogger,Alloy Wheels,Power Antenna,Tinted Glass,Sun Roof,Moon Roof,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Tinted Glass,Sun Roof,...,Heated Wing Mirror,LEDDRLs,LEDHeadlights,LEDFog Lamps,Cornering Headlamps,NaN,NaN,NaN,NaN,NaN
1481,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Wheel Covers,Integrated Antenna,Rear Spoiler,Outside Rear View Mirror Turn Indicators,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Defogger,Alloy Wheels,Power Antenna,Rear Spoiler,Outside Rear View Mirror Turn Indicators,Chrome Grille,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [201]:
#flatten the nested dict to dataframe
new_car_feature_data_4_HD =pd.json_normalize(new_car_feature_data_HD[3])
new_car_feature_data_4_HD

     heading subHeading                                               list
0     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1     Safety     Safety  [{'value': 'Child Safety Locks'}, {'value': 'D...
2     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
3     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
4     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
...      ...        ...                                                ...
1478  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1479  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1480  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1481  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1482  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...

[1483 rows x 3 columns]

In [202]:
#apply function to all values in the list column
new_car_feature_list_4_HD= new_car_feature_data_4_HD["list"].apply(extract_key_value_dicts1)
new_car_feature_list_4_HD = pd.json_normalize(new_car_feature_list_4_HD)
new_car_feature_list_4_HD

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Child Safety Locks,Driver Air Bag,Day Night Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Side Impact Beams,Front Impact Beams,Adjustable Seats,Centrally Mounted Fuel Tank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,Anti Lock Braking System,Centeral Locking,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,...,Isofix Child Seat Mounts,Pretensioners And Force Limiter Seatbelts,Hill Assist,Impact Sensing Auto Door Lock,View360Camera,No Of Airbags,Eletronic Stability Control,NaN,NaN,NaN
1481,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [203]:
#flatten the nested dict to dataframe
new_car_feature_data_5_HD =pd.json_normalize(new_car_feature_data_HD[4])
new_car_feature_data_5_HD

,heading,subHeading,list
0,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1,NaN,NaN,NaN
2,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
3,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Audio System R..."
4,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
...,...,...,...
1478,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Dvd Player..."
1479,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1480,Entertainment & Communication,Entertainment,"[{'value': 'Cd Changer'}, {'value': 'Radio'}, ..."
1481,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1482,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Dvd Player..."

In [204]:
#apply function to all values in the list column
new_car_feature_list_5_HD= new_car_feature_data_5_HD["list"].apply(extract_key_value_dicts1)
new_car_feature_list_5_HD = pd.json_normalize(new_car_feature_list_5_HD)
new_car_feature_list_5_HD

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,Radio,Speakers Front,Speakers Rear,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,Apple Car Play,Android Auto,Mirror Link,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Touch Screen,Number Of Speaker,Touch Screen Size,Apple Car Play,Android Auto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,Touch Screen Size,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,Cd Player,Dvd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,Cd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,Cd Changer,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Internal Storage,Number Of Speaker,Rear Entertainment System,Apple Car Play,NaN,NaN,NaN,NaN,NaN,NaN
1481,Radio,Speakers Front,Speakers Rear,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,Cd Player,Dvd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## new_car_specs

In [205]:
#convert string to dict
df_hyderabad["new_car_specs_dict"]= df_hyderabad["new_car_specs"].apply(ast.literal_eval)

In [206]:
df_hyderabad["new_car_specs_dict"]

0       {'heading': 'Specifications', 'top': [{'key': ...
1       {'heading': 'Specifications', 'top': [{'key': ...
2       {'heading': 'Specifications', 'top': [{'key': ...
3       {'heading': 'Specifications', 'top': [{'key': ...
4       {'heading': 'Specifications', 'top': [{'key': ...
                              ...
1478    {'heading': 'Specifications', 'top': [{'key': ...
1479    {'heading': 'Specifications', 'top': [{'key': ...
1480    {'heading': 'Specifications', 'top': [{'key': ...
1481    {'heading': 'Specifications', 'top': [{'key': ...
1482    {'heading': 'Specifications', 'top': [{'key': ...
Name: new_car_specs_dict, Length: 1483, dtype: object

In [207]:
#flatten the nested dict to dataframe
new_car_specs_HD=pd.json_normalize(df_hyderabad["new_car_specs_dict"])
new_car_specs_HD

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '16.47 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '21.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Engine', 'value': '1197 CC'}, {'key'...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Engine', 'value': '1997 CC'}, {'key'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1478,Specifications,"[{'key': 'Mileage', 'value': '15.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1479,Specifications,"[{'key': 'Mileage', 'value': '14.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1480,Specifications,"[{'key': 'Mileage', 'value': '20.37 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1481,Specifications,"[{'key': 'Mileage', 'value': '21.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1482,Specifications,"[{'key': 'Mileage', 'value': '12.99 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",

In [208]:
#drop column 'commonIcon'from dataframe
new_car_specs_HD.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_specs_HD

,heading,top,data
0,Specifications,"[{'key': 'Mileage', 'value': '16.47 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1,Specifications,"[{'key': 'Mileage', 'value': '21.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
2,Specifications,"[{'key': 'Engine', 'value': '1197 CC'}, {'key'...","[{'heading': 'Engine and Transmission', 'subHe..."
3,Specifications,"[{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
4,Specifications,"[{'key': 'Engine', 'value': '1997 CC'}, {'key'...","[{'heading': 'Engine and Transmission', 'subHe..."
...,...,...,...
1478,Specifications,"[{'key': 'Mileage', 'value': '15.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1479,Specifications,"[{'key': 'Mileage', 'value': '14.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1480,Specifications,"[{'key': 'Mileage', 'value': '20.37 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1481,Specifications,"[{'key': 'Mileage', 'value': '21.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1482,Specifications,"[{'key': 'Mileage', 'value': '12.99 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."

In [209]:
#apply function to all values in top column
new_car_specs_top_HD=new_car_specs_HD["top"].apply(extract_key_value_dicts2)
new_car_specs_top_HD

0       {'Mileage': '16.47 kmpl', 'Engine': '999 CC', ...
1       {'Mileage': '21.1 kmpl', 'Engine': '814 CC', '...
2       {'Engine': '1197 CC', 'Max Power': '81.80bhp',...
3       {'Mileage': '21.4 kmpl', 'Engine': '1197 CC', ...
4       {'Engine': '1997 CC', 'Max Power': '150bhp', '...
                              ...
1478    {'Mileage': '15.1 kmpl', 'Engine': '2179 CC', ...
1479    {'Mileage': '14.74 kmpl', 'Engine': '2993 CC',...
1480    {'Mileage': '20.37 kmpl', 'Engine': '1995 CC',...
1481    {'Mileage': '21.5 kmpl', 'Engine': '1497 CC', ...
1482    {'Mileage': '12.99 kmpl', 'Engine': '2494 CC',...
Name: top, Length: 1483, dtype: object

In [210]:
new_car_specs_top_HD[0]

{'Mileage': '16.47 kmpl',
 'Engine': '999 CC',
 'Max Power': '108.62bhp',
 'Torque': '175nm',
 'Wheel Size': 'R16',
 'Seats': '5'}

In [211]:
new_car_specs_top_HD=pd.json_normalize(new_car_specs_top_HD)
new_car_specs_top_HD

         Mileage   Engine  Max Power   Torque Wheel Size Seats
0     16.47 kmpl   999 CC  108.62bhp    175nm        R16     5
1      21.1 kmpl   814 CC    55.2bhp   74.5Nm        NaN     5
2            NaN  1197 CC   81.80bhp  113.8Nm        NaN     5
3      21.4 kmpl  1197 CC    83.1bhp    115Nm         16     5
4            NaN  1997 CC     150bhp    320Nm         18     4
...          ...      ...        ...      ...        ...   ...
1478   15.1 kmpl  2179 CC     140bhp    330Nm         17     7
1479  14.74 kmpl  2993 CC   270.9bhp    600Nm         20     5
1480  20.37 kmpl  1995 CC  187.74bhp    400Nm        R18     5
1481   21.5 kmpl  1497 CC   108.5bhp    260Nm        NaN     5
1482  12.99 kmpl  2494 CC   100.6bhp    200Nm         15     7

[1483 rows x 6 columns]

In [212]:
#flatten the nested dict to dataframe
new_car_specs_data_HD=pd.json_normalize(new_car_specs_HD["data"])
new_car_specs_data_HD

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1478,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1479,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1480,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1481,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1482,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [213]:
new_car_specs_data_HD[0][0]

{'heading': 'Engine and Transmission',
 'subHeading': 'Engine',
 'list': [{'key': 'Color', 'value': 'Others'},
  {'key': 'Engine Type', 'value': '1.0L TSI Petrol'},
  {'key': 'Displacement', 'value': '999'},
  {'key': 'Max Power', 'value': '108.62bhp@5000-5500rpm'},
  {'key': 'Max Torque', 'value': '175nm@1750-4000rpm'},
  {'key': 'No of Cylinder', 'value': 3},
  {'key': 'Values per Cylinder', 'value': 4},
  {'key': 'Value Configuration', 'value': 'DOHC'},
  {'key': 'Fuel Suppy System', 'value': 'TSI'},
  {'key': 'BoreX Stroke', 'value': '74.5x76.4 mm'},
  {'key': 'Compression Ratio', 'value': '10.5:1'},
  {'key': 'Turbo Charger', 'value': 'Yes'},
  {'key': 'Super Charger', 'value': 'No'}]}

In [214]:
#flatten the nested dict to dataframe
new_car_specs_data_1_HD=pd.json_normalize(new_car_specs_data_HD[0])
new_car_specs_data_1_HD

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
...,...,...,...
1478,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1479,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Blue'}, {'key': 'E..."
1480,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Blue'}, {'key': 'E..."
1481,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1482,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."

In [215]:
#apply function function to all values in list column
new_car_specs_list_1_HD= new_car_specs_data_1_HD["list"].apply(extract_key_value_dicts2)
new_car_specs_list_1_HD=pd.json_normalize(new_car_specs_list_1_HD)
new_car_specs_list_1_HD

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,Others,1.0L TSI Petrol,999,108.62bhp@5000-5500rpm,175nm@1750-4000rpm,3.0,4.0,DOHC,TSI,74.5x76.4 mm,10.5:1,Yes,No,NaN,NaN,NaN,NaN,NaN
1,Red,Petrol Engine,814,55.2bhp@5500rpm,74.5Nm@4000rpm,3.0,3.0,SOHC,MPFI,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN
2,Others,1.2 Kappa Petrol,1197,81.80bhp@6000rpm,113.8Nm@4000rpm,4.0,4.0,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN
3,Red,VVT Petrol Engine,1197,83.1bhp@6000rpm,115Nm@4000rpm,4.0,4.0,DOHC,MPFI,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN
4,Others,mStallion 150 TGDi Engine,1997,150bhp@5000rpm,320Nm@1500-3000rpm,4.0,4.0,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,Others,mHawk Diesel Engine,2179,140bhp@3750rpm,330Nm@1600-2800rpm,4.0,4.0,DOHC,Direct Injection,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
1479,Blue,Diesel S Engine,2993,270.9bhp@4000rpm,600Nm@2000rpm,6.0,4.0,DOHC,Direct Injection,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
1480,Blue,TwinPower Turbo Inline 4 Cylinder Engine,1995,187.74bhp@4000rpm,400Nm@1750-2500rpm,4.0,4.0,NaN,CRDi,NaN,NaN,Twin,No,NaN,NaN,NaN,NaN,NaN
1481,Others,"Revotorq, 1.5L Turbocharged engine",1497,108.5bhp@3750rpm,260Nm@1500-2750rpm,4.0,4.0,DOHC,CDI,76x82.5,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN
1482,Others,2KD-FTV Diesel Engine,2494,100.6bhp@3600rpm,200Nm@1200-3600rpm,4.0,4.0,DOHC,CRDi,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN

In [216]:
#flatten the nested dict to dataframe
new_car_specs_data_2_HD=pd.json_normalize(new_car_specs_data_HD[1])
new_car_specs_data_2_HD

,heading,subHeading,list
0,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3971mm'}, {'key':..."
1,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3495mm'}, {'key':..."
2,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."
3,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."
4,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3985mm'}, {'key':..."
...,...,...,...
1478,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4585mm'}, {'key':..."
1479,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4961mm'}, {'key':..."
1480,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4936mm'}, {'key':..."
1481,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3994mm'}, {'key':..."
1482,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4585mm'}, {'key':..."

In [217]:
#apply function function to all values in list column
new_car_specs_list_2_HD= new_car_specs_data_2_HD["list"].apply(extract_key_value_dicts2)

In [218]:
new_car_specs_list_2_HD[0]

{'Length': '3971mm',
 'Width': '1682mm',
 'Height': '1469mm',
 'Wheel Base': '2470mm',
 'Front Tread': '1457mm',
 'Rear Tread': '1500mm',
 'Kerb Weight': '1106',
 'Gross Weight': '1570'}

In [219]:
new_car_specs_list_2_HD=pd.json_normalize(new_car_specs_list_2_HD)
new_car_specs_list_2_HD

,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,3971mm,1682mm,1469mm,2470mm,1457mm,1500mm,1106,1570,NaN,NaN,NaN,NaN,NaN,NaN
1,3495mm,1550mm,1500mm,2380mm,1386mm,1368mm,880,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3995mm,1770mm,1617mm,2500mm,NaN,NaN,1106,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3995mm,1745mm,1510mm,2520mm,1505mm,1515mm,890Kg,1340kg,NaN,NaN,NaN,NaN,NaN,NaN
4,3985mm,1855mm,1844mm,2450mm,1520mm,1520mm,1825,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,4585mm,1890mm,1785mm,2700mm,NaN,NaN,1940,2450kg,NaN,NaN,NaN,NaN,NaN,NaN
1479,4961mm,1877mm,1460mm,2909mm,1559mm,1605mm,1780kg,2360kg,NaN,NaN,NaN,NaN,NaN,NaN
1480,4936mm,2126mm,1466mm,2975mm,1605mm,1630mm,1660,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,3994mm,1811mm,1607mm,2498mm,1540 mm,1530 mm,1305Kg,NaN,209 mm,NaN,NaN,NaN,NaN,NaN
1482,4585mm,1765mm,1760mm,2750mm,1510mm,1510mm,1700kg,2300kg,NaN,NaN,NaN,NaN,NaN,NaN

In [220]:
#flatten the nested dict to dataframe
new_car_specs_data_3_HD=pd.json_normalize(new_car_specs_data_HD[2])
new_car_specs_data_3_HD

,heading,subHeading,list
0,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
2,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
3,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
4,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
...,...,...,...
1478,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1479,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '8 Speed'}, {'ke..."
1480,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '8-Speed Steptro..."
1481,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1482,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."

In [221]:
#apply function function to all values in list column
new_car_specs_list_3_HD= new_car_specs_data_3_HD["list"].apply(extract_key_value_dicts2)
new_car_specs_list_3_HD=pd.json_normalize(new_car_specs_list_3_HD)
new_car_specs_list_3_HD

,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Top Speed,Acceleration
0,6 Speed,FWD,5,Electronic,4.9,Disc,Drum,"Tubeless,Radial",R16,5,280,NaN,NaN
1,5 Speed,FWD,5,Power,4.6 metres,Disc,Drum,Tubeless,NaN,5,215-litres,135 Kmph,19 Seconds
2,5-Speed,NaN,5,Power,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,NaN,NaN,NaN
3,5 Speed,FWD,5,Power,4.9 meters,Disc,Drum,"Tubeless,Radial",16,5,339-litres,180 Kmph,12.36 seconds
4,6 Speed,4X4,4,Power,NaN,Disc,Drum,"Radial, Tubeless",18,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,6 Speed,FWD,7,Power,5.6 metres,Disc & Caliper Type,Disc & Caliper Type,"Tubeless,Radial",17,5,NaN,175 kmph,12.5 Seconds
1479,8 Speed,RWD,5,Power,5.75 metres,Disc,Disc,"Tubeless,Radial",20,4,540-litres,250 Kmph,6.4 Seconds
1480,8-Speed Steptronic,RWD,5,Power,5.6,Ventilated Disc,Ventilated Disc,"Tubeless, Runflat",R18,4,520-litres,235kmph,7.5
1481,6 Speed,FWD,5,Power,5.1m,Disc,Drum,Tubeless Radial Tyres,NaN,5,350,154.19 kmph,13.25 Seconds
1482,5 Speed,RWD,7,Power,5.4 metres,Ventilated Disc,Drum,"Tubeless,Radial",15,5,300-litres,155 Kmph,13.3 Seconds

In [222]:
# concat hyderabad car details
hyderabad_cars_data=pd.concat([new_car_detail_hd,new_car_overview_HD,new_car_specs_top_HD,new_car_specs_list_1_HD,new_car_specs_list_2_HD,new_car_specs_list_3_HD],axis=1)
hyderabad_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Top Speed,Acceleration
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,Electronic,4.9,Disc,Drum,"Tubeless,Radial",R16,5,280,NaN,NaN
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,Power,4.6 metres,Disc,Drum,Tubeless,NaN,5,215-litres,135 Kmph,19 Seconds
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,Power,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,NaN,NaN,NaN
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,Power,4.9 meters,Disc,Drum,"Tubeless,Radial",16,5,339-litres,180 Kmph,12.36 seconds
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,Power,NaN,Disc,Drum,"Radial, Tubeless",18,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,Power,5.6 metres,Disc & Caliper Type,Disc & Caliper Type,"Tubeless,Radial",17,5,NaN,175 kmph,12.5 Seconds
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,Power,5.75 metres,Disc,Disc,"Tubeless,Radial",20,4,540-litres,250 Kmph,6.4 Seconds
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,Power,5.6,Ventilated Disc,Ventilated Disc,"Tubeless, Runflat",R18,4,520-litres,235kmph,7.5
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,Power,5.1m,Disc,Drum,Tubeless Radial Tyres,NaN,5,350,154.19 kmph,13.25 Seconds
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,Power,5.4 metres,Ventilated Disc,Drum,"Tubeless,Radial",15,5,300-litres,155 Kmph,13.3 Seconds

In [223]:
#add city column to dataframe
hyderabad_cars_data["City"]="hyderabad"
#final dataframe
hyderabad_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Top Speed,Acceleration,City
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,4.9,Disc,Drum,"Tubeless,Radial",R16,5,280,NaN,NaN,hyderabad
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,4.6 metres,Disc,Drum,Tubeless,NaN,5,215-litres,135 Kmph,19 Seconds,hyderabad
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,NaN,NaN,NaN,hyderabad
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,4.9 meters,Disc,Drum,"Tubeless,Radial",16,5,339-litres,180 Kmph,12.36 seconds,hyderabad
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,NaN,Disc,Drum,"Radial, Tubeless",18,3,NaN,NaN,NaN,hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,5.6 metres,Disc & Caliper Type,Disc & Caliper Type,"Tubeless,Radial",17,5,NaN,175 kmph,12.5 Seconds,hyderabad
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,5.75 metres,Disc,Disc,"Tubeless,Radial",20,4,540-litres,250 Kmph,6.4 Seconds,hyderabad
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,5.6,Ventilated Disc,Ventilated Disc,"Tubeless, Runflat",R18,4,520-litres,235kmph,7.5,hyderabad
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,5.1m,Disc,Drum,Tubeless Radial Tyres,NaN,5,350,154.19 kmph,13.25 Seconds,hyderabad
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,5.4 metres,Ventilated Disc,Drum,"Tubeless,Radial",15,5,300-litres,155 Kmph,13.3 Seconds,hyderabad

## jaipur cars

In [224]:
#convert excel to dataframe
df_jaipur=pd.read_excel(r"C:/Users/jagadesh/Documents/Python Scripts/car dekho - used car prediction/unstructured_files/jaipur_cars.xlsx")
df_jaipur

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1115,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1116,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1117,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1118,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1119,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [225]:
#drop column 'car_links' from dataframe
df_jaipur.drop(columns=["car_links"],inplace=True,axis=1)
df_jaipur

,new_car_detail,new_car_overview,new_car_feature,new_car_specs
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
...,...,...,...,...
1115,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1116,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ..."
1117,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."
1118,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ..."
1119,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ..."

## new_car_detail

In [226]:
#view new_car_detail
df_jaipur["new_car_detail"]

0       {'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
4       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
                              ...
1115    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1116    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1117    {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
1118    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1119    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
Name: new_car_detail, Length: 1120, dtype: object

In [227]:
df_jaipur["new_car_detail"][0]

"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', 'km': '1,20,000', 'transmission': 'Manual', 'ownerNo': 2, 'owner': '2nd Owner', 'oem': 'Hyundai', 'model': 'Hyundai i20', 'modelYear': 2015, 'centralVariantId': 1487, 'variantName': 'Asta 1.4 CRDi', 'price': 'â‚¹ 5.10 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

In [228]:
#convert string to dict
df_jaipur["new_car_detail_dict"]=df_jaipur["new_car_detail"].apply(ast.literal_eval)

In [229]:
#flatten the nested dict to dataframe
new_car_detail_jp=pd.json_normalize(df_jaipur["new_car_detail_dict"])
new_car_detail_jp

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,1487,Asta 1.4 CRDi,â‚¹ 5.10 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,10403,VXI,â‚¹ 3.81 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,3982,VXI AT,â‚¹ 3.20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,5602,1.2 Kappa Magna BSIV,â‚¹ 4.20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,4319,AMT VXI,â‚¹ 3.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,438,LT,â‚¹ 1.08 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,3917,STD,â‚¹ 1.05 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,8350,RXZ,â‚¹ 8.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,3904,Std,â‚¹ 1 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,3962,1.2 Delta,â‚¹ 5 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

## new_car_overview

In [230]:
#convert string to dict
df_jaipur["new_car_overview_dict"]=df_jaipur["new_car_overview"].apply(ast.literal_eval)
df_jaipur["new_car_overview_dict"]

0       {'heading': 'Car overview', 'top': [{'key': 'R...
1       {'heading': 'Car overview', 'top': [{'key': 'R...
2       {'heading': 'Car overview', 'top': [{'key': 'R...
3       {'heading': 'Car overview', 'top': [{'key': 'R...
4       {'heading': 'Car overview', 'top': [{'key': 'R...
                              ...
1115    {'heading': 'Car overview', 'top': [{'key': 'R...
1116    {'heading': 'Car overview', 'top': [{'key': 'R...
1117    {'heading': 'Car overview', 'top': [{'key': 'R...
1118    {'heading': 'Car overview', 'top': [{'key': 'R...
1119    {'heading': 'Car overview', 'top': [{'key': 'R...
Name: new_car_overview_dict, Length: 1120, dtype: object

In [231]:
#flatten the dict to dataframe
new_car_overview_JP=pd.json_normalize(df_jaipur["new_car_overview_dict"])
new_car_overview_JP

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Jan 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': '2016',...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Apr 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2016',...",None
...,...,...,...
1115,Car overview,"[{'key': 'Registration Year', 'value': '2011',...",None
1116,Car overview,"[{'key': 'Registration Year', 'value': '2007',...",None
1117,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
1118,Car overview,"[{'key': 'Registration Year', 'value': '2009',...",None
1119,Car overview,"[{'key': 'Registration Year', 'value': '2018',...",None

In [232]:
#drop column 'bottomData' from dataframe
new_car_overview_JP.drop(columns=["bottomData"],inplace=True,axis=1)
new_car_overview_JP

           heading                                                top
0     Car overview  [{'key': 'Registration Year', 'value': '2015',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Jan 20...
2     Car overview  [{'key': 'Registration Year', 'value': '2016',...
3     Car overview  [{'key': 'Registration Year', 'value': 'Apr 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2016',...
...            ...                                                ...
1115  Car overview  [{'key': 'Registration Year', 'value': '2011',...
1116  Car overview  [{'key': 'Registration Year', 'value': '2007',...
1117  Car overview  [{'key': 'Registration Year', 'value': '2022',...
1118  Car overview  [{'key': 'Registration Year', 'value': '2009',...
1119  Car overview  [{'key': 'Registration Year', 'value': '2018',...

[1120 rows x 2 columns]

In [233]:
#apply function to all values in top column
new_car_overview_JP=new_car_overview_JP["top"].apply(extract_key_value_dicts)

In [234]:
new_car_overview_JP

0       {'Registration Year': '2015', 'Insurance Valid...
1       {'Registration Year': 'Jan 2012', 'Insurance V...
2       {'Registration Year': '2016', 'Insurance Valid...
3       {'Registration Year': 'Apr 2017', 'Insurance V...
4       {'Registration Year': '2016', 'Insurance Valid...
                              ...
1115    {'Registration Year': '2011', 'Insurance Valid...
1116    {'Registration Year': '2007', 'Insurance Valid...
1117    {'Registration Year': '2022', 'Insurance Valid...
1118    {'Registration Year': '2009', 'Insurance Valid...
1119    {'Registration Year': '2018', 'Insurance Valid...
Name: top, Length: 1120, dtype: object

In [235]:
new_car_overview_JP=pd.json_normalize(new_car_overview_JP)
new_car_overview_JP

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2015,Third Party insurance,Diesel,5 Seats,"1,20,000 Kms",RJ13,Second Owner,1396 cc,Manual,2015.0
1,Jan 2012,Third Party,Petrol,5 Seats,"66,951 Kms",RJ14,First Owner,1197 cc,Manual,2012.0
2,2016,Third Party insurance,Petrol,5 Seats,"80,000 Kms",RJ14,Second Owner,998 cc,Automatic,2016.0
3,Apr 2017,Third Party insurance,Petrol,5 Seats,"44,392 Kms",RJ14,First Owner,1197 cc,Manual,2017.0
4,2016,Third Party insurance,Petrol,5 Seats,"40,000 Kms",RJ14,First Owner,998 cc,Automatic,2016.0
...,...,...,...,...,...,...,...,...,...,...
1115,2011,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",RJ14,First Owner,1199 cc,Manual,2011.0
1116,2007,Third Party insurance,Petrol,5 Seats,"70,000 Kms",RJ30,First Owner,796 cc,Manual,2007.0
1117,2022,Third Party insurance,Petrol,5 Seats,"20,000 Kms",RJ45,First Owner,999 cc,Manual,2022.0
1118,2009,Third Party insurance,Petrol,5 Seats,"40,000 Kms",NaN,First Owner,796 cc,Manual,2009.0
1119,2018,Third Party insurance,Petrol,5 Seats,"80,000 Kms",UP82,First Owner,1197 cc,Manual,2018.0

## new_car_feature

In [236]:
#view new_car_feature
df_jaipur["new_car_feature"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1115    {'heading': 'Features', 'top': [{'value': 'Pow...
1116    {'heading': 'Features', 'top': [{'value': 'Low...
1117    {'heading': 'Features', 'top': [{'value': 'Pow...
1118    {'heading': 'Features', 'top': [{'value': 'Low...
1119    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature, Length: 1120, dtype: object

In [237]:
df_jaipur["new_car_feature"][0]

"{'heading': 'Features', 'top': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Anti Lock Braking System'}, {'value': 'Centeral Locking'}, {'value': 'Cd Player'}], 'data': [{'heading': 'Comfort & Convenience', 'subHeading': 'Comfort', 'list': [{'value': 'Power Steering'}, {'value': 'Power Windows Front'}, {'value': 'Power Windows Rear'}, {'value': 'Air Quality Control'}, {'value': 'Remote Trunk Opener'}, {'value': 'Remote Fuel Lid Opener'}, {'value': 'Low Fuel Warning Light'}, {'value': 'Accessory Power Outlet'}, {'value': 'Trunk Light'}, {'value': 'Vanity Mirror'}, {'value': 'Rear Seat Headrest'}, {'value': 'Cup Holders Front'}, {'value': 'Multifunction Steering Wheel'}, {'value': 'Rear ACVents'}, {'value': 'Smart Access Card Entry'}, {'value': 'Engine Start Stop Button'}, {'value': 'Glove Box Cooling'}]}, {'heading': 'Interior', 'subHeading': 'Interior', 'list': [{'value': 'Air Conditioner'}, {'value': 'Heater'}, {'value': 'Adjustable Steering'}, {'value': 'Digital Odometer'}, {'value': 'Tachometer'}, {'value': 'Electronic Multi Tripmeter'}, {'value': 'Fabric Upholstery'}, {'value': 'Leather Steering Wheel'}, {'value': 'Glove Compartment'}, {'value': 'Digital Clock'}, {'value': 'Height Adjustable Driver Seat'}]}, {'heading': 'Exterior', 'subHeading': 'Exterior', 'list': [{'value': 'Adjustable Head Lights'}, {'value': 'Fog Lights Front'}, {'value': 'Power Adjustable Exterior Rear View Mirror'}, {'value': 'Electric Folding Rear View Mirror'}, {'value': 'Rear Window Wiper'}, {'value': 'Rear Window Washer'}, {'value': 'Rear Window Defogger'}, {'value': 'Alloy Wheels'}, {'value': 'Power Antenna'}, {'value': 'Rear Spoiler'}, {'value': 'Outside Rear View Mirror Turn Indicators'}, {'value': 'Chrome Grille'}]}, {'heading': 'Safety', 'subHeading': 'Safety', 'list': [{'value': 'Anti Lock Braking System'}, {'value': 'Centeral Locking'}, {'value': 'Power Door Locks'}, {'value': 'Child Safety Locks'}, {'value': 'Driver Air Bag'}, {'value': 'Passenger Air Bag'}, {'value': 'Day Night Rear View Mirror'}, {'value': 'Passenger Side Rear View Mirror'}, {'value': 'Halogen Headlamps'}, {'value': 'Rear Seat Belts'}, {'value': 'Seat Belt Warning'}, {'value': 'Door Ajar Warning'}, {'value': 'Side Impact Beams'}, {'value': 'Front Impact Beams'}, {'value': 'Adjustable Seats'}, {'value': 'Keyless Entry'}, {'value': 'Centrally Mounted Fuel Tank'}, {'value': 'Engine Immobilizer'}, {'value': 'Crash Sensor'}, {'value': 'Automatic Head Lamps'}, {'value': 'Clutch Lock'}, {'value': 'Follow Me Home Headlamps'}, {'value': 'Rear Camera'}, {'value': 'Anti Theft Device'}]}, {'heading': 'Entertainment & Communication', 'subHeading': 'Entertainment', 'list': [{'value': 'Cd Player'}, {'value': 'Radio'}, {'value': 'Speakers Front'}, {'value': 'Speakers Rear'}, {'value': 'Integrated2Din Audio'}, {'value': 'Usb Auxiliary Input'}, {'value': 'Bluetooth'}]}], 'commonIcon': 'https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg'}"

In [238]:
#convert string to dict
df_jaipur["new_car_feature_dict"]=df_jaipur["new_car_feature"].apply(ast.literal_eval)
df_jaipur["new_car_feature_dict"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1115    {'heading': 'Features', 'top': [{'value': 'Pow...
1116    {'heading': 'Features', 'top': [{'value': 'Low...
1117    {'heading': 'Features', 'top': [{'value': 'Pow...
1118    {'heading': 'Features', 'top': [{'value': 'Low...
1119    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature_dict, Length: 1120, dtype: object

In [239]:
#flatten the nested dict to dataframe
new_car_feature_JP=pd.json_normalize(df_jaipur["new_car_feature_dict"])
new_car_feature_JP

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1115,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1116,Features,"[{'value': 'Low Fuel Warning Light'}, {'value'...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1117,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1118,Features,"[{'value': 'Low Fuel Warning Light'}, {'value'...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1119,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [240]:
#drop column from dataframe
new_car_feature_JP.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_feature_JP

,heading,top,data
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
...,...,...,...
1115,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1116,Features,"[{'value': 'Low Fuel Warning Light'}, {'value'...","[{'heading': 'Comfort & Convenience', 'subHead..."
1117,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1118,Features,"[{'value': 'Low Fuel Warning Light'}, {'value'...","[{'heading': 'Comfort & Convenience', 'subHead..."
1119,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."

In [241]:
new_car_feature_JP["top"][0]

[{'value': 'Power Steering'},
 {'value': 'Power Windows Front'},
 {'value': 'Air Conditioner'},
 {'value': 'Heater'},
 {'value': 'Adjustable Head Lights'},
 {'value': 'Fog Lights Front'},
 {'value': 'Anti Lock Braking System'},
 {'value': 'Centeral Locking'},
 {'value': 'Cd Player'}]

In [242]:
#apply function to all valuesin top column
new_car_feature_top_4= new_car_feature_JP["top"].apply(extract_key_value_dicts1)
new_car_feature_top_4[0]

{0: 'Power Steering',
 1: 'Power Windows Front',
 2: 'Air Conditioner',
 3: 'Heater',
 4: 'Adjustable Head Lights',
 5: 'Fog Lights Front',
 6: 'Anti Lock Braking System',
 7: 'Centeral Locking',
 8: 'Cd Player'}

In [243]:
new_car_feature_top_4= pd.json_normalize(new_car_feature_top_4)
new_car_feature_top_4

,0,1,2,3,4,5,6,7,8
0,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
1,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Brake Assist,Radio
2,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Centeral Locking,Child Safety Locks,NaN
3,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Speakers Front
4,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Centeral Locking,Power Door Locks,Cd Player
...,...,...,...,...,...,...,...,...,...
1115,Power Steering,Power Windows Front,Air Conditioner,Heater,Fog Lights Front,Manually Adjustable Exterior Rear View Mirror,Centeral Locking,Day Night Rear View Mirror,Cd Player
1116,Low Fuel Warning Light,Electronic Multi Tripmeter,Glove Compartment,Manually Adjustable Exterior Rear View Mirror,Brake Assist,Halogen Headlamps,NaN,NaN,NaN
1117,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Radio
1118,Low Fuel Warning Light,Electronic Multi Tripmeter,Glove Compartment,Manually Adjustable Exterior Rear View Mirror,Brake Assist,Halogen Headlamps,Usb Auxiliary Input,Bluetooth,NaN
1119,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Cd Player

In [244]:
#flatten the nested dict to dataframe
new_car_feature_data_JP=pd.json_normalize(new_car_feature_JP["data"])
new_car_feature_data_JP

,0,1,2,3,4
0,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
2,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",None
3,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
4,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
...,...,...,...,...,...
1115,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1116,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",None
1117,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1118,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1119,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."

In [245]:
# flatten the nested dict to dataframe
new_car_feature_data_1_JP=pd.json_normalize(new_car_feature_data_JP[0])
new_car_feature_data_1_JP

,heading,subHeading,list
0,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
2,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
3,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
4,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
...,...,...,...
1115,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1116,Comfort & Convenience,Comfort,[{'value': 'Low Fuel Warning Light'}]
1117,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1118,Comfort & Convenience,Comfort,[{'value': 'Low Fuel Warning Light'}]
1119,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."

In [246]:
# apply function to all values in list column
new_car_feature_list_1_JP= new_car_feature_data_1_JP["list"].apply(extract_key_value_dicts1)
new_car_feature_list_1_JP=pd.json_normalize(new_car_feature_list_1_JP)
new_car_feature_list_1_JP

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Power Steering,Power Windows Front,Power Windows Rear,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Multifunction Steering Wheel,Gear Shift Indicator,Adjustable Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Power Steering,Power Windows Front,Power Windows Rear,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,Multifunction Steering Wheel,Rear ACVents,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,Low Fuel Warning Light,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,Rear Seat Centre Arm Rest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118,Low Fuel Warning Light,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [247]:
# flatten the nested dict to dataframe
new_car_feature_data_2_JP=pd.json_normalize(new_car_feature_data_JP[1])
new_car_feature_data_2_JP

       heading subHeading                                               list
0     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
2     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
3     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
4     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
...        ...        ...                                                ...
1115  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1116  Interior   Interior  [{'value': 'Electronic Multi Tripmeter'}, {'va...
1117  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1118  Interior   Interior  [{'value': 'Electronic Multi Tripmeter'}, {'va...
1119  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...

[1120 rows x 3 columns]

In [248]:
# apply function to all values in list column
new_car_feature_list_2_JP= new_car_feature_data_2_JP["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2_JP=pd.json_normalize(new_car_feature_list_2_JP)
new_car_feature_list_2_JP

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
1,Air Conditioner,Heater,Adjustable Steering,Tachometer,Fabric Upholstery,Glove Compartment,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Dual Tone Dashboard,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,Air Conditioner,Heater,Adjustable Steering,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,Electronic Multi Tripmeter,Glove Compartment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
1118,Electronic Multi Tripmeter,Glove Compartment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,NaN,NaN,NaN,NaN,NaN,NaN

In [249]:
# flatten the nested dict to dataframe
new_car_feature_data_3_JP=pd.json_normalize(new_car_feature_data_JP[2])
new_car_feature_data_3_JP

       heading subHeading                                               list
0     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
2     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
3     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
4     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
...        ...        ...                                                ...
1115  Exterior   Exterior  [{'value': 'Fog Lights Front'}, {'value': 'Man...
1116  Exterior   Exterior  [{'value': 'Manually Adjustable Exterior Rear ...
1117  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1118  Exterior   Exterior  [{'value': 'Manually Adjustable Exterior Rear ...
1119  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...

[1120 rows x 3 columns]

In [250]:
# apply function to all values in list column
new_car_feature_list_2_JP= new_car_feature_data_2_JP["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2_JP=pd.json_normalize(new_car_feature_list_2_JP)
new_car_feature_list_2_JP

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
1,Air Conditioner,Heater,Adjustable Steering,Tachometer,Fabric Upholstery,Glove Compartment,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Dual Tone Dashboard,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,Air Conditioner,Heater,Adjustable Steering,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,Electronic Multi Tripmeter,Glove Compartment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN
1118,Electronic Multi Tripmeter,Glove Compartment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Outside Temperature Display,NaN,NaN,NaN,NaN,NaN,NaN

In [251]:
# flatten the nested dict to dataframe
new_car_feature_data_3_JP=pd.json_normalize(new_car_feature_data_JP[2])
new_car_feature_data_3_JP

       heading subHeading                                               list
0     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
2     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
3     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
4     Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
...        ...        ...                                                ...
1115  Exterior   Exterior  [{'value': 'Fog Lights Front'}, {'value': 'Man...
1116  Exterior   Exterior  [{'value': 'Manually Adjustable Exterior Rear ...
1117  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...
1118  Exterior   Exterior  [{'value': 'Manually Adjustable Exterior Rear ...
1119  Exterior   Exterior  [{'value': 'Adjustable Head Lights'}, {'value'...

[1120 rows x 3 columns]

In [252]:
# apply function to all values in list column
new_car_feature_list_3_JP= new_car_feature_data_3_JP["list"].apply(extract_key_value_dicts1)
new_car_feature_list_3_JP=pd.json_normalize(new_car_feature_list_3_JP)
new_car_feature_list_3_JP

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Rear Spoiler,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Wheel Covers,Power Antenna,Outside Rear View Mirror Turn Indicators,LEDTaillights,Halogen Headlamps,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Wheel Covers,Power Antenna,Chrome Grille,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Wheel Covers,Integrated Antenna,Tinted Glass,Chrome Grille,Roof Rail,Halogen Headlamps,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Wheel Covers,Power Antenna,Chrome Grille,Chrome Garnish,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,Fog Lights Front,Manually Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Power Antenna,Tinted Glass,Rear Spoiler,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,Manually Adjustable Exterior Rear View Mirror,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Rear Spoiler,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118,Manually Adjustable Exterior Rear View Mirror,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Wheel Covers,Integrated Antenna,Tinted Glass,Rear Spoiler,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [253]:
# flatten the nested dict to dataframe
new_car_feature_data_4_JP=pd.json_normalize(new_car_feature_data_JP[3])
new_car_feature_data_4_JP

     heading subHeading                                               list
0     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
2     Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Chi...
3     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
4     Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Pow...
...      ...        ...                                                ...
1115  Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Day...
1116  Safety     Safety  [{'value': 'Brake Assist'}, {'value': 'Halogen...
1117  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1118  Safety     Safety  [{'value': 'Brake Assist'}, {'value': 'Halogen...
1119  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...

[1120 rows x 3 columns]

In [254]:
# apply function to all values in list column
new_car_feature_list_4_JP= new_car_feature_data_4_JP["list"].apply(extract_key_value_dicts1)
new_car_feature_list_4_JP=pd.json_normalize(new_car_feature_list_4_JP)
new_car_feature_list_4_JP

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Centeral Locking,Child Safety Locks,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Door Ajar Warning,Side Impact Beams,Front Impact Beams,Adjustable Seats,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Side Impact Beams,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,Centeral Locking,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Seat Belt Warning,Door Ajar Warning,Adjustable Seats,Centrally Mounted Fuel Tank,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,Brake Assist,Halogen Headlamps,Rear Seat Belts,Side Impact Beams,Engine Check Warning,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118,Brake Assist,Halogen Headlamps,Rear Seat Belts,Side Impact Beams,Engine Check Warning,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [255]:
# flatten the nested dict to dataframe
new_car_feature_data_5_JP=pd.json_normalize(new_car_feature_data_JP[4])
new_car_feature_data_5_JP

,heading,subHeading,list
0,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
2,NaN,NaN,NaN
3,Entertainment & Communication,Entertainment,"[{'value': 'Speakers Front'}, {'value': 'Speak..."
4,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
...,...,...,...
1115,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1116,NaN,NaN,NaN
1117,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1118,Entertainment & Communication,Entertainment,"[{'value': 'Usb Auxiliary Input'}, {'value': '..."
1119,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."

In [256]:
# apply function to all values in list column
new_car_feature_list_5_JP= new_car_feature_data_5_JP["list"].apply(extract_key_value_dicts1)
new_car_feature_list_5_JP=pd.json_normalize(new_car_feature_list_5_JP)
new_car_feature_list_5_JP

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Radio,Speakers Front,Speakers Rear,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,Cd Player,Radio,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,Touch Screen Size,Apple Car Play,Android Auto,Wireless Phone Charging,NaN,NaN,NaN
1118,Usb Auxiliary Input,Bluetooth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## new_car_specs

In [257]:
# convert string to dict
df_jaipur["new_car_specs_dict"] = df_jaipur["new_car_specs"].apply(ast.literal_eval)

In [258]:
#flatten the nested dict to dataframe
new_car_specs_JP=pd.json_normalize(df_jaipur["new_car_specs_dict"])
new_car_specs_JP

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '20.51 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1115,Specifications,"[{'key': 'Mileage', 'value': '18.6 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1116,Specifications,"[{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1117,Specifications,"[{'key': 'Mileage', 'value': '19.17 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1118,Specifications,"[{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1119,Specifications,"[{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",

In [259]:
# drop column from dataframe
new_car_specs_JP.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_specs_JP

,heading,top,data
0,Specifications,"[{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1,Specifications,"[{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
2,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
3,Specifications,"[{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
4,Specifications,"[{'key': 'Mileage', 'value': '20.51 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
...,...,...,...
1115,Specifications,"[{'key': 'Mileage', 'value': '18.6 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1116,Specifications,"[{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1117,Specifications,"[{'key': 'Mileage', 'value': '19.17 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1118,Specifications,"[{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1119,Specifications,"[{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."

In [260]:
# apply function to all values in top column
new_car_specs_top_JP= new_car_specs_JP["top"].apply(extract_key_value_dicts2)
new_car_specs_top_JP=pd.json_normalize(new_car_specs_top_JP)
new_car_specs_top_JP

         Mileage   Engine Max Power    Torque Wheel Size Seats
0     22.54 kmpl  1396 CC  88.73bhp   219.7Nm         16     5
1     22.38 kmpl  1197 CC  88.50bhp     113Nm        NaN     5
2      23.1 kmpl   998 CC  67.04bhp      90Nm        NaN     5
3      18.9 kmpl  1197 CC  81.86bhp  113.75nm        NaN     5
4     20.51 kmpl   998 CC     67bhp      90Nm        NaN     5
...          ...      ...       ...       ...        ...   ...
1115   18.6 kmpl  1199 CC   79.4bhp     108Nm         14     5
1116   19.7 kmpl   796 CC   46.3bhp      62Nm         12     5
1117  19.17 kmpl   999 CC  71.01bhp      96Nm         16     5
1118   19.7 kmpl   796 CC   46.3bhp      62Nm         12     5
1119   21.4 kmpl  1197 CC   83.1bhp     115Nm        NaN     5

[1120 rows x 6 columns]

In [261]:
# apply function to all values in data column
new_car_specs_data_JP=pd.json_normalize(new_car_specs_JP["data"])
new_car_specs_data_JP

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1115,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1116,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1117,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1118,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1119,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [262]:
# flatten the nested dict to dataframe
new_car_specs_data_1_JP=pd.json_normalize(new_car_specs_data_JP[0])
new_car_specs_data_1_JP

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Silver'}, {'key': ..."
...,...,...,...
1115,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1116,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1117,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1118,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1119,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."

In [263]:
# apply function to all values in list column
new_car_specs_list_1_JP= new_car_specs_data_1_JP["list"].apply(extract_key_value_dicts2)
new_car_specs_list_1_JP=pd.json_normalize(new_car_specs_list_1_JP)
new_car_specs_list_1_JP

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,Turbo Charger,Super Charger,BoreX Stroke,Compression Ratio
0,Others,U2 CRDI Diesel Engine,1396,88.73bhp@4000rpm,219.7Nm@1500-2750rpm,4.0,4.0,DOHC,CRDI,Yes,No,NaN,NaN
1,White,K Series Dual jet,1197,88.50bhp@6000rpm,113Nm@4400rpm,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Others,K10B Engine,998,67.04bhp@6000rpm,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,No,No,73 X 82 mm,11.0:1
3,Silver,Kappa VTVT Petrol Engine,1197,81.86bhp@6000rpm,113.75nm@4000rpm,4.0,4.0,DOHC,MPFI,No,No,NaN,NaN
4,Silver,K10B Petrol Engine,998,67bhp@6000rpm,90Nm@3500rpm,3.0,4.0,DOHC,NaN,No,No,69 x 72 mm,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,Others,Smartech Engine,1199,79.4bhp@6200rpm,108Nm@4400rpm,4.0,4.0,DOHC,MPFI,No,No,NaN,NaN
1116,Others,In-Line Engine,796,46.3bhp@6200rpm,62Nm@3000rpm,3.0,4.0,SOHC,MPFI,No,No,68.5 x 72.0 mm,NaN
1117,Others,1.0L energy,999,71.01bhp@6250rpm,96Nm@3500rpm,3.0,4.0,NaN,MPFi,NaN,NaN,NaN,NaN
1118,Others,In-Line Engine,796,46.3bhp@6200rpm,62Nm@3000rpm,3.0,4.0,SOHC,MPFI,No,No,68.5 x 72.0 mm,NaN
1119,Others,VVT Petrol Engine,1197,83.1bhp@6000rpm,115Nm@4000rpm,4.0,4.0,DOHC,MPFI,No,No,NaN,NaN

In [264]:
# flatten the nested dict to dataframe
new_car_specs_data_2_JP=pd.json_normalize(new_car_specs_data_JP[1])
new_car_specs_data_2_JP

,heading,subHeading,list
0,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3985mm'}, {'key':..."
1,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3845mm'}, {'key':..."
2,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3715mm'}, {'key':..."
3,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3765mm'}, {'key':..."
4,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3599mm'}, {'key':..."
...,...,...,...
1115,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3640mm'}, {'key':..."
1116,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3495mm'}, {'key':..."
1117,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3991mm'}, {'key':..."
1118,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3495mm'}, {'key':..."
1119,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3995mm'}, {'key':..."

In [265]:
# apply function to all values in list column
new_car_specs_list_2_JP= new_car_specs_data_2_JP["list"].apply(extract_key_value_dicts2)
new_car_specs_list_2_JP=pd.json_normalize(new_car_specs_list_2_JP)
new_car_specs_list_2_JP

,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,Seating Capacity,...,Tyre Type,Alloy Wheel Size,No Door Numbers,Gear Box,Drive Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration
0,3985mm,1734mm,1505mm,2570mm,1505mm,1503mm,1515kg,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3845mm,1735,1530,2450,1530,1530,875-905,1335,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,840kg,1250kg,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3765mm,1660mm,1520mm,2425mm,1479mm,1493mm,1100,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3599mm,1495mm,1700mm,2400mm,1295mm,1290mm,890kg,1350kg,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,3640mm,1595mm,1520mm,2375mm,NaN,NaN,990,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,3495mm,1475mm,1460mm,2360mm,1295mm,1290mm,690kg,1140kg,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,3991mm,1750,1605,2500,1536,1535,1012,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118,3495mm,1475mm,1460mm,2360mm,1295mm,1290mm,690kg,1140kg,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,3995mm,1745mm,1510mm,2520mm,1515mm,1525mm,870kg,1340kg,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [266]:
# flatten the nested dict to dataframe
new_car_specs_data_3_JP=pd.json_normalize(new_car_specs_data_JP[2])
new_car_specs_data_3_JP

,heading,subHeading,list
0,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."
1,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
2,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed '}, {'k..."
3,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
4,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
...,...,...,...
1115,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1116,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1117,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1118,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1119,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."

In [267]:
# apply function to all values in list column
new_car_specs_list_3_JP= new_car_specs_data_3_JP["list"].apply(extract_key_value_dicts2)
new_car_specs_list_3_JP=pd.json_normalize(new_car_specs_list_3_JP)
new_car_specs_list_3_JP

,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn
0,6 Speed,FWD,5,Power,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,16,5,295-litres
1,5-Speed,NaN,5,Electric,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268
2,5 Speed,FWD,5,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",NaN,5,235-litres
3,5 Speed,FWD,5,Power,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,NaN,5,256
4,5 Speed,FWD,5,Power,4.6 metres,Ventilated Disc,Drum,152 kmph,18.6 Seconds,Tubeless Tyres,NaN,5,180-liters
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,5 Speed,FWD,5,Power,4.85metres,Disc,Drum,NaN,NaN,"Tubeless,Radial",14,5,170-litres
1116,5 Speed,2WD,5,Manual,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN
1117,5 Speed,NaN,5,Electric,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",16,5,405
1118,5 Speed,2WD,5,Manual,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN
1119,5 Speed,FWD,5,Power,4.9 meters,Disc,Drum,180 Kmph,12.36 seconds,"Tubeless,Radial",NaN,5,339-litres

In [268]:
# concat jaipur car details
jaipur_cars_data=pd.concat([new_car_detail_jp,new_car_overview_JP,new_car_specs_top_JP,new_car_specs_list_1_JP,new_car_specs_list_2_JP,new_car_specs_list_3_JP],axis=1)
jaipur_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,Power,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,16,5,295-litres
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,Electric,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",NaN,5,235-litres
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,Power,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,NaN,5,256
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,Power,4.6 metres,Ventilated Disc,Drum,152 kmph,18.6 Seconds,Tubeless Tyres,NaN,5,180-liters
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,Power,4.85metres,Disc,Drum,NaN,NaN,"Tubeless,Radial",14,5,170-litres
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,Manual,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,Electric,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",16,5,405
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,Manual,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,Power,4.9 meters,Disc,Drum,180 Kmph,12.36 seconds,"Tubeless,Radial",NaN,5,339-litres

In [269]:
# add city column to dataframe
jaipur_cars_data["City"]="Jaipur"
# final dataframe
jaipur_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,City
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,16,5,295-litres,Jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5,268,Jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",NaN,5,235-litres,Jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,NaN,5,256,Jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,4.6 metres,Ventilated Disc,Drum,152 kmph,18.6 Seconds,Tubeless Tyres,NaN,5,180-liters,Jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,4.85metres,Disc,Drum,NaN,NaN,"Tubeless,Radial",14,5,170-litres,Jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN,Jaipur
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,Disc,Drum,NaN,NaN,"Tubeless, Radial",16,5,405,Jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,4.6m,Disc,Drum,137km/hr,17.7 seconds,"Tubeless,Radial",12,5,NaN,Jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,4.9 meters,Disc,Drum,180 Kmph,12.36 seconds,"Tubeless,Radial",NaN,5,339-litres,Jaipur

## Kolkata Cars

In [270]:
# Convert excel file to dataframe
df_kolkata=pd.read_excel(r"C:/Users/jagadesh/Documents/Python Scripts/car dekho - used car prediction/unstructured_files/kolkata_cars.xlsx")
df_kolkata

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1376,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1377,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1378,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1379,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1380,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [271]:
#drop 'car_links' column from dataframe
df_kolkata

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1376,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1377,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1378,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1379,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1380,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

## New_car_detail

In [272]:
# convert string to dict
df_kolkata["new_car_detail_dict"] = df_kolkata["new_car_detail"].apply(ast.literal_eval)

In [273]:
#flatten the nested dict to dataframe
new_car_detail_kl=pd.json_normalize(df_kolkata["new_car_detail_dict"])
new_car_detail_kl

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,2123,Hybrid,â‚¹ 9.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,5236,T Option,â‚¹ 2.66 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,8352,RXT AMT,â‚¹ 5.95 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,1642,1.2 Sportz,â‚¹ 2.23 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,99,35 TDI Quattro Premium,â‚¹ 12 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,8682,ZXI BSVI,â‚¹ 5.10 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,3943,LXI,â‚¹ 1.80 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,4672,C 200 CGI Elegance,â‚¹ 5.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,4144,ZXi,â‚¹ 1.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,5048,110PS Diesel RxZ AWD,â‚¹ 5 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

## New_car_overview

In [274]:
# convert string to dict
df_kolkata["new_car_overview_dict"] = df_kolkata["new_car_overview"].apply(ast.literal_eval)

In [275]:
# flatten the nested dict to dataframe
new_car_overview_KL=pd.json_normalize(df_kolkata["new_car_overview_dict"])
new_car_overview_KL

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2014',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Jul 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': 'Nov 20...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2014',...",None
...,...,...,...
1376,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
1377,Car overview,"[{'key': 'Registration Year', 'value': '2014',...",None
1378,Car overview,"[{'key': 'Registration Year', 'value': '2011',...",None
1379,Car overview,"[{'key': 'Registration Year', 'value': '2012',...",None
1380,Car overview,"[{'key': 'Registration Year', 'value': '2017',...",None

In [276]:
# drop column from dataframe
new_car_overview_KL.drop(columns=["bottomData"],inplace=True,axis=1)
new_car_overview_KL

           heading                                                top
0     Car overview  [{'key': 'Registration Year', 'value': '2014',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Jul 20...
2     Car overview  [{'key': 'Registration Year', 'value': 'Nov 20...
3     Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2014',...
...            ...                                                ...
1376  Car overview  [{'key': 'Registration Year', 'value': '2022',...
1377  Car overview  [{'key': 'Registration Year', 'value': '2014',...
1378  Car overview  [{'key': 'Registration Year', 'value': '2011',...
1379  Car overview  [{'key': 'Registration Year', 'value': '2012',...
1380  Car overview  [{'key': 'Registration Year', 'value': '2017',...

[1381 rows x 2 columns]

In [277]:
# apply function to all values in top column
new_car_overview_KL = new_car_overview_KL['top'].apply(extract_key_value_dicts)
new_car_overview_KL=pd.json_normalize(new_car_overview_KL)
new_car_overview_KL

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2014,Third Party insurance,Petrol,5 Seats,"70,000 Kms",WB02,Third Owner,2494 cc,Automatic,2014.0
1,Jul 2017,Comprehensive,Petrol,5 Seats,"23,981 Kms",WB24,First Owner,799 cc,Manual,2017.0
2,Nov 2021,Comprehensive,Petrol,5 Seats,"7,100 Kms",WB06,First Owner,999 cc,Automatic,2021.0
3,Feb 2012,Third Party,Petrol,5 Seats,"71,574 Kms",WB06,Second Owner,1197 cc,Manual,2011.0
4,2014,Third Party insurance,Diesel,5 Seats,"50,000 Kms",WB02,Second Owner,1968 cc,Automatic,2014.0
...,...,...,...,...,...,...,...,...,...,...
1376,2022,Third Party insurance,Petrol,5 Seats,"10,000 Kms",NaN,First Owner,998 cc,Manual,2022.0
1377,2014,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",NaN,First Owner,796 cc,Manual,2014.0
1378,2011,Third Party insurance,Petrol,5 Seats,"50,000 Kms",WB06,Third Owner,1796 cc,Automatic,2011.0
1379,2012,Third Party insurance,Petrol,5 Seats,"40,000 Kms",NaN,First Owner,1197 cc,Manual,2012.0
1380,2017,Third Party insurance,Diesel,5 Seats,"1,20,000 Kms",NaN,Second Owner,1461 cc,Manual,2017.0

## New_car_feature

In [278]:
# view new_car_feature
df_kolkata["new_car_feature"]

0       {'heading': 'Features', 'top': [{'value': 'Pow...
1       {'heading': 'Features', 'top': [{'value': 'Pow...
2       {'heading': 'Features', 'top': [{'value': 'Pow...
3       {'heading': 'Features', 'top': [{'value': 'Pow...
4       {'heading': 'Features', 'top': [{'value': 'Pow...
                              ...
1376    {'heading': 'Features', 'top': [{'value': 'Pow...
1377    {'heading': 'Features', 'top': [{'value': 'Pow...
1378    {'heading': 'Features', 'top': [{'value': 'Pow...
1379    {'heading': 'Features', 'top': [{'value': 'Pow...
1380    {'heading': 'Features', 'top': [{'value': 'Pow...
Name: new_car_feature, Length: 1381, dtype: object

In [279]:
# convert string to dict
df_kolkata["new_car_feature_dict"] = df_kolkata["new_car_feature"].apply(ast.literal_eval)

In [280]:
# flatten the nested dict to dataframe
new_car_feature_KL=pd.json_normalize(df_kolkata["new_car_feature_dict"])
new_car_feature_KL

,heading,top,data,commonIcon
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...,...,...,...,...
1376,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1377,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1378,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1379,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1380,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [281]:
# drop column from dataframe
new_car_feature_KL.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_feature_KL

,heading,top,data
0,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
2,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
3,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
4,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
...,...,...,...
1376,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1377,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1378,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1379,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."
1380,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead..."

In [282]:
# apply function to all values in top column
new_car_feature_top_5= new_car_feature_KL["top"].apply(extract_key_value_dicts1)
new_car_feature_top_5=pd.json_normalize(new_car_feature_top_5)
new_car_feature_top_5

,0,1,2,3,4,5,6,7,8
0,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player
1,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Radio
2,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Radio
3,Power Steering,Power Windows Front,Air Conditioner,Heater,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Centeral Locking,Power Door Locks,Cd Player
4,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player
...,...,...,...,...,...,...,...,...,...
1376,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Anti Lock Braking System,Centeral Locking,Radio
1377,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Day Night Rear View Mirror,Passenger Side Rear View Mirror,NaN
1378,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player
1379,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Centeral Locking,Cd Player
1380,Power Steering,Power Windows Front,Air Conditioner,Heater,Adjustable Head Lights,Fog Lights Front,Anti Lock Braking System,Brake Assist,Cd Player

In [283]:
# flatten the nested dict to dataframe
new_car_feature_data_KL=pd.json_normalize(new_car_feature_KL["data"])
new_car_feature_data_KL

,0,1,2,3,4
0,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
2,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
3,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
4,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
...,...,...,...,...,...
1376,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1377,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...",None
1378,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1379,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."
1380,"{'heading': 'Comfort & Convenience', 'subHeadi...","{'heading': 'Interior', 'subHeading': 'Interio...","{'heading': 'Exterior', 'subHeading': 'Exterio...","{'heading': 'Safety', 'subHeading': 'Safety', ...","{'heading': 'Entertainment & Communication', '..."

In [284]:
# flatten the nested dict to dataframe
new_car_feature_data_1_KL=pd.json_normalize(new_car_feature_data_KL[0])

In [285]:
new_car_feature_data_1_KL

,heading,subHeading,list
0,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
2,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
3,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
4,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
...,...,...,...
1376,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1377,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1378,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1379,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."
1380,Comfort & Convenience,Comfort,"[{'value': 'Power Steering'}, {'value': 'Power..."

In [286]:
# apply function to all values in list column
new_car_feature_list_1_KL= new_car_feature_data_1_KL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_1_KL=pd.json_normalize(new_car_feature_list_1_KL)
new_car_feature_list_1_KL

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Power Steering,Power Windows Front,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Rear Seat Headrest,Height Adjustable Front Seat Belts,Cup Holders Front,Gear Shift Indicator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,Rear Seat Centre Arm Rest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Power Steering,Power Windows Front,Power Windows Rear,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Cup Holders Front,Seat Lumbar Support,Multifunction Steering Wheel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,Power Steering,Power Windows Front,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Rear Seat Headrest,Cup Holders Front,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1378,Power Steering,Power Windows Front,Power Windows Rear,Air Quality Control,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1379,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Remote Fuel Lid Opener,Low Fuel Warning Light,Accessory Power Outlet,Vanity Mirror,Rear Seat Headrest,Height Adjustable Front Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1380,Power Steering,Power Windows Front,Power Windows Rear,Remote Trunk Opener,Low Fuel Warning Light,Accessory Power Outlet,Trunk Light,Vanity Mirror,Rear Reading Lamp,Rear Seat Headrest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [287]:
# flatten the nested dict to dataframe
new_car_feature_data_2_KL=pd.json_normalize(new_car_feature_data_KL[1])

In [288]:
new_car_feature_data_2_KL

       heading subHeading                                               list
0     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
2     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
3     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
4     Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
...        ...        ...                                                ...
1376  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1377  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1378  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1379  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...
1380  Interior   Interior  [{'value': 'Air Conditioner'}, {'value': 'Heat...

[1381 rows x 3 columns]

In [289]:
# apply function to all values in list column
new_car_feature_list_2_KL= new_car_feature_data_2_KL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_2_KL=pd.json_normalize(new_car_feature_list_2_KL)
new_car_feature_list_2_KL

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN
1,Air Conditioner,Heater,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
3,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,NaN,NaN,NaN,NaN
4,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,Air Conditioner,Heater,Digital Odometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1378,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Leather Seats,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Cigarette Lighter,NaN,NaN,NaN,NaN
1379,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Glove Compartment,Digital Clock,Height Adjustable Driver Seat,NaN,NaN,NaN,NaN,NaN,NaN
1380,Air Conditioner,Heater,Adjustable Steering,Digital Odometer,Tachometer,Electronic Multi Tripmeter,Fabric Upholstery,Leather Steering Wheel,Glove Compartment,Digital Clock,Outside Temperature Display,Driving Experience Control Eco,Height Adjustable Driver Seat,NaN,NaN,NaN

In [290]:
# flatten the nested dict to dataframe
new_car_feature_data_3_KL=pd.json_normalize(new_car_feature_data_KL[2])

In [291]:
# apply function to all values in list column
new_car_feature_list_3_KL= new_car_feature_data_3_KL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_3_KL=pd.json_normalize(new_car_feature_list_3_KL)
new_car_feature_list_3_KL

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,Adjustable Head Lights,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Defogger,Alloy Wheels,Integrated Antenna,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Wheel Covers,Power Antenna,Tinted Glass,Chrome Grille,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Wheel Covers,Integrated Antenna,Rear Spoiler,Outside Rear View Mirror Turn Indicators,Chrome Grille,Roof Rail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Wiper,Wheel Covers,Alloy Wheels,Tinted Glass,Outside Rear View Mirror Turn Indicators,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adjustable Head Lights,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Adjustable Head Lights,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Wheel Covers,Integrated Antenna,Outside Rear View Mirror Turn Indicators,Chrome Grille,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,Adjustable Head Lights,Manually Adjustable Exterior Rear View Mirror,Wheel Covers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1378,Adjustable Head Lights,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rain Sensing Wiper,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,...,Chrome Grille,Chrome Garnish,Smoke Headlamps,Roof Rail,NaN,NaN,NaN,NaN,NaN,NaN
1379,Adjustable Head Lights,Fog Lights Front,Fog Lights Rear,Power Adjustable Exterior Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Rear Spoiler,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1380,Adjustable Head Lights,Fog Lights Front,Power Adjustable Exterior Rear View Mirror,Electric Folding Rear View Mirror,Rear Window Wiper,Rear Window Washer,Rear Window Defogger,Alloy Wheels,Power Antenna,Outside Rear View Mirror Turn Indicators,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [292]:
# flatten the nested dict to dataframe
new_car_feature_data_4_KL=pd.json_normalize(new_car_feature_data_KL[3])

In [293]:
new_car_feature_data_4_KL

     heading subHeading                                               list
0     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
2     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
3     Safety     Safety  [{'value': 'Centeral Locking'}, {'value': 'Pow...
4     Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
...      ...        ...                                                ...
1376  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1377  Safety     Safety  [{'value': 'Day Night Rear View Mirror'}, {'va...
1378  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1379  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...
1380  Safety     Safety  [{'value': 'Anti Lock Braking System'}, {'valu...

[1381 rows x 3 columns]

In [294]:
# apply function to all values in list column
new_car_feature_list_4_KL= new_car_feature_data_4_KL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_4_KL=pd.json_normalize(new_car_feature_list_4_KL)
new_car_feature_list_4_KL

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anti Lock Braking System,Centeral Locking,Child Safety Locks,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Side Impact Beams,Front Impact Beams,Adjustable Seats,Keyless Entry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Door Ajar Warning,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Side Air Bag Rear,Day Night Rear View Mirror,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,Side Impact Beams,Front Impact Beams,Adjustable Seats,Centrally Mounted Fuel Tank,Engine Immobilizer,Anti Theft Device,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1378,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Side Air Bag Front,Side Air Bag Rear,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1379,Anti Lock Braking System,Centeral Locking,Power Door Locks,Child Safety Locks,Anti Theft Alarm,Driver Air Bag,Passenger Air Bag,Day Night Rear View Mirror,Passenger Side Rear View Mirror,Halogen Headlamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1380,Anti Lock Braking System,Brake Assist,Centeral Locking,Power Door Locks,Child Safety Locks,Driver Air Bag,Passenger Air Bag,Passenger Side Rear View Mirror,Halogen Headlamps,Rear Seat Belts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [295]:
# flatten the nested dict to dataframe
new_car_feature_data_5_KL=pd.json_normalize(new_car_feature_data_KL[4])

In [296]:
new_car_feature_data_5_KL

,heading,subHeading,list
0,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Dvd Player..."
1,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
2,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
3,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
4,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
...,...,...,...
1376,Entertainment & Communication,Entertainment,"[{'value': 'Radio'}, {'value': 'Speakers Front..."
1377,NaN,NaN,NaN
1378,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Cd Changer..."
1379,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."
1380,Entertainment & Communication,Entertainment,"[{'value': 'Cd Player'}, {'value': 'Radio'}, {..."

In [297]:
# apply function to all values in list column
new_car_feature_list_5_KL= new_car_feature_data_5_KL["list"].apply(extract_key_value_dicts1)
new_car_feature_list_5_KL=pd.json_normalize(new_car_feature_list_5_KL)
new_car_feature_list_5_KL

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,Cd Player,Dvd Player,Radio,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Radio,Speakers Front,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,Touch Screen Size,Apple Car Play,Android Auto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cd Player,Radio,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cd Player,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1378,Cd Player,Cd Changer,Radio,Audio System Remote Control,Speakers Front,Speakers Rear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1379,Cd Player,Radio,Speakers Front,Speakers Rear,Usb Auxiliary Input,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1380,Cd Player,Radio,Speakers Front,Speakers Rear,Integrated2Din Audio,Usb Auxiliary Input,Bluetooth,Touch Screen,Number Of Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## New_car_specs

In [298]:
# convert string to dict
df_kolkata["new_car_specs_dict"] = df_kolkata["new_car_specs"].apply(ast.literal_eval)

In [299]:
#flatten the nested dict to dataframe
new_car_specs_KL=pd.json_normalize(df_kolkata["new_car_specs_dict"])
new_car_specs_KL

,heading,top,data,commonIcon
0,Specifications,"[{'key': 'Mileage', 'value': '19.16 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1,Specifications,"[{'key': 'Mileage', 'value': '22.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
2,Specifications,"[{'key': 'Mileage', 'value': '19.03 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
3,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",
4,Specifications,"[{'key': 'Mileage', 'value': '15.73 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
...,...,...,...,...
1376,Specifications,"[{'key': 'Mileage', 'value': '25.24 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1377,Specifications,"[{'key': 'Mileage', 'value': '22.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1378,Specifications,"[{'key': 'Mileage', 'value': '11.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",
1379,Specifications,"[{'key': 'Mileage', 'value': '18.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1380,Specifications,"[{'key': 'Mileage', 'value': '19.72 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",

In [300]:
# drop column from dataframe
new_car_specs_KL.drop(columns=["commonIcon"],inplace=True,axis=1)
new_car_specs_KL

,heading,top,data
0,Specifications,"[{'key': 'Mileage', 'value': '19.16 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1,Specifications,"[{'key': 'Mileage', 'value': '22.7 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
2,Specifications,"[{'key': 'Mileage', 'value': '19.03 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
3,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe..."
4,Specifications,"[{'key': 'Mileage', 'value': '15.73 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
...,...,...,...
1376,Specifications,"[{'key': 'Mileage', 'value': '25.24 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1377,Specifications,"[{'key': 'Mileage', 'value': '22.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1378,Specifications,"[{'key': 'Mileage', 'value': '11.74 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."
1379,Specifications,"[{'key': 'Mileage', 'value': '18.5 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe..."
1380,Specifications,"[{'key': 'Mileage', 'value': '19.72 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe..."

In [301]:
# apply function to all values in top column
new_car_specs_top_KL= new_car_specs_KL["top"].apply(extract_key_value_dicts2)
new_car_specs_top_KL=pd.json_normalize(new_car_specs_top_KL)
new_car_specs_top_KL

,Mileage,Engine,Max Power,Torque,Wheel Size,Seats
0,19.16 kmpl,2494 CC,158.2bhp,213Nm,17,5
1,22.7 kmpl,799 CC,53.64bhp,72Nm,NaN,5
2,19.03 kmpl,999 CC,71.01bhp,96Nm,NaN,5
3,17 kmpl,1197 CC,80 PS at 5200 rpm,"11.4 kgm at 4,000 rpm",14,5
4,15.73 kmpl,1968 CC,174.33bhp,380Nm,16,5
...,...,...,...,...,...,...
1376,25.24 kmpl,998 CC,65.71bhp,89Nm,NaN,5
1377,22.74 kmpl,796 CC,47.3bhp,69Nm,NaN,5
1378,11.74 kmpl,1796 CC,186bhp,285Nm,17,5
1379,18.5 kmpl,1197 CC,85.80bhp,114Nm,14,5
1380,19.72 kmpl,1461 CC,108.45bhp,245Nm,16,5

In [302]:
# flatten the nested dict to dataframe
new_car_specs_data_KL=pd.json_normalize(new_car_specs_KL["data"])
new_car_specs_data_KL

,0,1,2
0,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
2,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
3,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
4,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
...,...,...,...
1376,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1377,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1378,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1379,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."
1380,"{'heading': 'Engine and Transmission', 'subHea...","{'heading': 'Dimensions & Capacity', 'subHeadi...","{'heading': 'Miscellaneous', 'subHeading': 'Mi..."

In [303]:
# flatten the nested dict to dataframe
new_car_specs_data_1_KL=pd.json_normalize(new_car_specs_data_KL[0])
new_car_specs_data_1_KL

,heading,subHeading,list
0,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
1,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
2,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Blue'}, {'key': 'E..."
3,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Red'}, {'key': 'En..."
4,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'White'}, {'key': '..."
...,...,...,...
1376,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1377,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1378,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1379,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."
1380,Engine and Transmission,Engine,"[{'key': 'Color', 'value': 'Others'}, {'key': ..."

In [304]:
# apply function to all values in list column
new_car_specs_list_1_KL= new_car_specs_data_1_KL["list"].apply(extract_key_value_dicts2)
new_car_specs_list_1_KL=pd.json_normalize(new_car_specs_list_1_KL)
new_car_specs_list_1_KL

,Color,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Turbo Charger,Super Charger,Compression Ratio
0,White,2AR FXE Petrol Engine,2494,158.2bhp@5700rpm,213Nm@4500rpm,4.0,4.0,DOHC,Electronic Fuel Injection(EFI),90 X 98 mm,No,No,NaN
1,Red,0.8L Petrol Engine,799,53.64bhp@5678rpm,72Nm@4386rpm,3.0,4.0,DOHC,MPFi,NaN,No,No,NaN
2,Blue,1.0L energy,999,71.01bhp@6250rpm,96Nm@3500rpm,3.0,4.0,NaN,MPFi,NaN,NaN,NaN,NaN
3,Red,In-Line Engine,1197,80 PS at 5200 rpm,"11.4 kgm at 4,000 rpm",4.0,4.0,DOHC,MPFI,NaN,No,No,:1
4,White,TDI Diesel Engine,1968,174.33bhp@4200rpm,380Nm@1750-2500rpm,4.0,4.0,DOHC,CRDI,NaN,Yes,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,Others,K10C,998,65.71bhp@5500rpm,89Nm@3500rpm,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
1377,Others,F8D Petrol Engine,796,47.3bhp@6000rpm,69Nm@3500rpm,3.0,4.0,DOHC,MPFi,NaN,No,No,NaN
1378,Others,Blue Efficiency Engine,1796,186bhp@5600rpm,285Nm@2400-4000rpm,4.0,4.0,NaN,Mpfi,NaN,No,No,9.3:1
1379,Others,K Series Petrol Engine,1197,85.80bhp@6000rpm,114Nm@4000rpm,4.0,4.0,DOHC,MPFI,NaN,No,No,NaN
1380,Others,dCi THP Diesel Engine,1461,108.45bhp@4000rpm,245Nm@1750rpm,4.0,4.0,DOHC,CRDi,NaN,Yes,No,NaN

In [305]:
# flatten the nested dict to dataframe
new_car_specs_data_2_KL=pd.json_normalize(new_car_specs_data_KL[1])
new_car_specs_data_2_KL

,heading,subHeading,list
0,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4825mm'}, {'key':..."
1,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3429mm'}, {'key':..."
2,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3991mm'}, {'key':..."
3,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3940 mm'}, {'key'..."
4,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4385mm'}, {'key':..."
...,...,...,...
1376,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3695mm'}, {'key':..."
1377,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3395mm'}, {'key':..."
1378,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4591mm'}, {'key':..."
1379,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '3775mm'}, {'key':..."
1380,Dimensions & Capacity,Dimensions,"[{'key': 'Length', 'value': '4315mm'}, {'key':..."

In [306]:
# apply function to all values in list column
new_car_specs_list_2_KL= new_car_specs_data_2_KL["list"].apply(extract_key_value_dicts2)
new_car_specs_list_2_KL=pd.json_normalize(new_car_specs_list_2_KL)
new_car_specs_list_2_KL

,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Ground Clearance Unladen,Seating Capacity,Steering Type,Tyre Type,Alloy Wheel Size,No Door Numbers
0,4825mm,1825mm,1480mm,2775mm,1580mm,1570mm,1625kg,2100kg,NaN,NaN,NaN,NaN,NaN,NaN
1,3429mm,1560mm,1541mm,2348mm,NaN,NaN,770,NaN,185mm,NaN,NaN,NaN,NaN,NaN
2,3991mm,1750,1605,2500,1536,1535,1055,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3940 mm,1710 mm,1505 mm,"2,525 mm","1,505 mm","1,503 mm",1020,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4385mm,2019mm,1608mm,2603mm,1571mm,1575mm,1660kg,2185kg,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,3695mm,1655,1555,2435,1430,1440,810,1260,NaN,NaN,NaN,NaN,NaN,NaN
1377,3395mm,1490mm,1475mm,2360mm,1295mm,1290mm,720kg,1185kg,NaN,NaN,NaN,NaN,NaN,NaN
1378,4591mm,1770mm,1447mm,2760mm,1549mm,1552mm,1585kg,2020kg,NaN,NaN,NaN,NaN,NaN,NaN
1379,3775mm,1680mm,1620mm,2360mm,1470mm,1480mm,1030kg,1430kg,NaN,NaN,NaN,NaN,NaN,NaN
1380,4315mm,1822mm,1695mm,2673mm,1560mm,1567mm,1350,1889kg,NaN,NaN,NaN,NaN,NaN,NaN

In [307]:
# flatten the nested dict to dataframe
new_car_specs_data_3_KL=pd.json_normalize(new_car_specs_data_KL[2])
new_car_specs_data_3_KL

,heading,subHeading,list
0,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed '}, {'k..."
1,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
2,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
3,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
4,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '7-Speed S-Troni..."
...,...,...,...
1376,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5-Speed'}, {'ke..."
1377,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1378,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '7 Speed'}, {'ke..."
1379,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '5 Speed'}, {'ke..."
1380,Miscellaneous,Miscellaneous,"[{'key': 'Gear Box', 'value': '6 Speed'}, {'ke..."

In [308]:
# apply function to all values in list column
new_car_specs_list_3_KL= new_car_specs_data_3_KL["list"].apply(extract_key_value_dicts2)
new_car_specs_list_3_KL=pd.json_normalize(new_car_specs_list_3_KL)
new_car_specs_list_3_KL

,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Acceleration,Top Speed
0,6 Speed,FWD,5,Power,5.5 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,NaN,NaN,NaN
1,5-Speed,2WD,5,Power,4.7m,Disc,Drum,NaN,NaN,5,222,NaN,NaN
2,5 Speed,NaN,5,Electric,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,405,NaN,NaN
3,5 Speed,FWD,5,Power,5.20 m,Disc,Drum,"Tubeless,Radial",14,5,295 Lit,12.96 Sec,NaN
4,7-Speed S-Tronic,AWD,5,Power,5.9 metres,Ventilated Disc,Drum,"Tubeless,Radial",16,5,460-litres,8.2 Seconds,212 Kmph
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,5-Speed,NaN,5,Electric,NaN,Ventilated Disc,Drum,"Tubeless, Radial",NaN,5,313,NaN,NaN
1377,5 Speed,FWD,5,Power,4.6 metres,Solid Disc,Drum,Tubeless Tyres,NaN,5,177-litres,19 Seconds,140 kmph
1378,7 Speed,RWD,5,Power,5.42 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,475-litres,8.8 Seconds,230km/hr
1379,5 Speed,FWD,5,Power,4.7 metres,Ventilated Disc,Drum,"Tubeless,Radial",14,5,236-liters,15 Seconds,156 Kmph
1380,6 Speed,AWD,5,Power,5.2 metres,Disc,Drum,"Tubeless,Radial",16,5,410-litres,14.20 Seconds,168 Kmph

In [309]:
# concat kolkata car details 
kolkata_cars_data=pd.concat([new_car_detail_kl,new_car_overview_KL,new_car_specs_top_KL,new_car_specs_list_1_KL,new_car_specs_list_2_KL,new_car_specs_list_3_KL],axis=1)
kolkata_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Acceleration,Top Speed
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,Power,5.5 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,NaN,NaN,NaN
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,Power,4.7m,Disc,Drum,NaN,NaN,5,222,NaN,NaN
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,Electric,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,405,NaN,NaN
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,Power,5.20 m,Disc,Drum,"Tubeless,Radial",14,5,295 Lit,12.96 Sec,NaN
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,Power,5.9 metres,Ventilated Disc,Drum,"Tubeless,Radial",16,5,460-litres,8.2 Seconds,212 Kmph
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Electric,NaN,Ventilated Disc,Drum,"Tubeless, Radial",NaN,5,313,NaN,NaN
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Power,4.6 metres,Solid Disc,Drum,Tubeless Tyres,NaN,5,177-litres,19 Seconds,140 kmph
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Power,5.42 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,475-litres,8.8 Seconds,230km/hr
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,Power,4.7 metres,Ventilated Disc,Drum,"Tubeless,Radial",14,5,236-liters,15 Seconds,156 Kmph
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,Power,5.2 metres,Disc,Drum,"Tubeless,Radial",16,5,410-litres,14.20 Seconds,168 Kmph

In [310]:
# add city column to dataframe
kolkata_cars_data["City"]="Kolkata"
# final dataframe
kolkata_cars_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Acceleration,Top Speed,City
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,5.5 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,NaN,NaN,NaN,Kolkata
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,4.7m,Disc,Drum,NaN,NaN,5,222,NaN,NaN,Kolkata
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,NaN,Disc,Drum,"Tubeless, Radial",NaN,5,405,NaN,NaN,Kolkata
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,5.20 m,Disc,Drum,"Tubeless,Radial",14,5,295 Lit,12.96 Sec,NaN,Kolkata
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,5.9 metres,Ventilated Disc,Drum,"Tubeless,Radial",16,5,460-litres,8.2 Seconds,212 Kmph,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,NaN,Ventilated Disc,Drum,"Tubeless, Radial",NaN,5,313,NaN,NaN,Kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,4.6 metres,Solid Disc,Drum,Tubeless Tyres,NaN,5,177-litres,19 Seconds,140 kmph,Kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,5.42 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4,475-litres,8.8 Seconds,230km/hr,Kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,4.7 metres,Ventilated Disc,Drum,"Tubeless,Radial",14,5,236-liters,15 Seconds,156 Kmph,Kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,5.2 metres,Disc,Drum,"Tubeless,Radial",16,5,410-litres,14.20 Seconds,168 Kmph,Kolkata

## Merge all cities data frame

In [311]:
# List of DataFrames
all_cities_car_data = [banglore_cars_data, chennai_cars_data, delhi_cars_data, hyderabad_cars_data, jaipur_cars_data, kolkata_cars_data]

# 1. Rename Duplicate Columns to Ensure Unique Column Names
def rename_duplicate_columns(df):
    # Find duplicate columns
    cols = pd.Series(df.columns)
    for dup in cols[cols.duplicated()].unique():
        # Rename duplicates by appending a suffix '_1', '_2', etc.
        count = 0
        for i in range(len(cols)):
            if cols[i] == dup:
                count += 1
                if count > 1:
                    cols[i] = f"{dup}_{count-1}"
    df.columns = cols
    return df

# Apply the function to each DataFrame to ensure unique column names
all_cities_car_data = [rename_duplicate_columns(df) for df in all_cities_car_data]

# 2. Ensure All DataFrames Have the Same Columns
# Get the set of all unique column names across all DataFrames
all_columns = set()
for df in all_cities_car_data:
    all_columns.update(df.columns)

# Add missing columns to each DataFrame with NaN values
for df in all_cities_car_data:
    missing_cols = all_columns - set(df.columns)
    for col in missing_cols:
        df[col] = pd.NA  # or use np.nan if you prefer

# 3. Concatenate DataFrames with Outer Join
# Reset index for each DataFrame to avoid index conflicts
all_cities_car_data = [df.reset_index(drop=True) for df in all_cities_car_data]

# Concatenate all DataFrames along rows (axis=0) with outer join
combined_df = pd.concat(all_cities_car_data, axis=0, join='outer', ignore_index=True)

print(combined_df.shape)
combined_df.head()

(8369, 88)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Cargo Volumn,Alloy Wheel Size_2,City,Front Brake Type_1,Rear Brake Type_1,Acceleration_1,Gear Box_1,Drive Type_1,Top Speed_1,Turning Radius_1
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,235-litres,NaN,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,352-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,242-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,407-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,353-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [312]:
combined_df.isnull().sum()

it                     0
ft                     0
bt                     0
km                     0
transmission           0
                    ...
Acceleration_1      6822
Gear Box_1          5795
Drive Type_1        6215
Top Speed_1         6900
Turning Radius_1    6277
Length: 88, dtype: int64

In [313]:
combined_df.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'Registration Year',
       'Insurance Validity', 'Fuel Type', 'Seats', 'Kms Driven', 'RTO',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Seats_1', 'Wheel Size', 'Color', 'Engine Type', 'Displacement',
       'Max Power_1', 'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Value Configuration', 'Fuel Suppy System', 'BoreX Stroke',
       'Compression Ratio', 'Turbo Charger', 'Super Charger',
       'Seating Capacity', 'Steering Type', 'Tyre Type', 'Alloy Wheel Size',
       'No Door Numbers', 'Length', 'Width', 'Height', 'Wheel Base',
       'Front Tread', 'Rear Tread', 'Kerb Weight', 'Gross Weight',
       'Ground Clearance Unladen', 'Seating Capacity_1', 'Steering Type_1',
       'Tyre Type_1', 'Alloy Wheel Size_1', 'No Door Numbers_1', 'Gear Box',
       'Drive Type', 'Seating Capacity_2', 'Steering Type_2', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type_2', 'No Door Numbers_2', 'Cargo Volumn',
       'Alloy Wheel Size_2', 'City', 'Front Brake Type_1', 'Rear Brake Type_1',
       'Acceleration_1', 'Gear Box_1', 'Drive Type_1', 'Top Speed_1',
       'Turning Radius_1'],
      dtype='object')

In [314]:
# drop column from dataframe
combined_df.drop(columns=["owner","centralVariantId","priceActual","priceSaving","priceFixedText","trendingText.imgUrl",
                          "trendingText.heading","trendingText.desc","Registration Year","RTO","Ownership",
                          "Engine Displacement","Seats","Wheel Size","Engine Type","Displacement","Max Power_1",
                          "Max Torque","No of Cylinder","Values per Cylinder","Values per Cylinder","Fuel Suppy System",
                          "BoreX Stroke","Compression Ratio","Turbo Charger","Super Charger","Seating Capacity",
                          "Tyre Type","Alloy Wheel Size","Height","Width","Wheel Base","Alloy Wheel Size_1",
                          "Front Tread","Rear Tread","Kerb Weight","Gross Weight","Ground Clearance Unladen",
                          "Seating Capacity_1","Seating Capacity_1","Tyre Type_1","No Door Numbers_1",
                          "Seating Capacity_2","Steering Type_2","Turning Radius","Front Brake Type","Rear Brake Type",
                          "Top Speed","Acceleration","Tyre Type_2","No Door Numbers_2","Alloy Wheel Size_2","Acceleration_1","Top Speed_1",
                          "Rear Brake Type_1","Front Brake Type_1","Gear Box_1","Turning Radius_1","variantName","Value Configuration","Steering Type",
                          "No Door Numbers","Length","Cargo Volumn","Drive Type_1","Torque","Steering Type_1","Year of Manufacture","Max Power","Transmission",
                          "Fuel Type","km"],inplace=True,axis=1)
combined_df

,it,ft,bt,transmission,ownerNo,oem,model,modelYear,price,Insurance Validity,Kms Driven,Mileage,Engine,Seats_1,Color,Gear Box,Drive Type,City
0,0,Petrol,Hatchback,Manual,3,Maruti,Maruti Celerio,2015,â‚¹ 4 Lakh,Third Party insurance,"1,20,000 Kms",23.1 kmpl,998 CC,5,White,5 Speed,FWD,Bangalore
1,0,Petrol,SUV,Manual,2,Ford,Ford Ecosport,2018,â‚¹ 8.11 Lakh,Comprehensive,"32,706 Kms",17 kmpl,1497 CC,5,White,5 Speed,FWD,Bangalore
2,0,Petrol,Hatchback,Manual,1,Tata,Tata Tiago,2018,â‚¹ 5.85 Lakh,Comprehensive,"11,949 Kms",23.84 kmpl,1199 CC,5,Red,5 Speed,FWD,Bangalore
3,0,Petrol,Sedan,Manual,1,Hyundai,Hyundai Xcent,2014,â‚¹ 4.62 Lakh,Comprehensive,"17,794 Kms",19.1 kmpl,1197 CC,5,Others,5 Speed,FWD,Bangalore
4,0,Diesel,SUV,Manual,1,Maruti,Maruti SX4 S Cross,2015,â‚¹ 7.90 Lakh,Third Party insurance,"60,000 Kms",23.65 kmpl,1248 CC,5,Gray,5 Speed,FWD,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Celerio,2022,â‚¹ 5.10 Lakh,Third Party insurance,"10,000 Kms",25.24 kmpl,998 CC,5,Others,5-Speed,NaN,Kolkata
8365,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Alto 800,2014,â‚¹ 1.80 Lakh,Third Party insurance,"1,20,000 Kms",22.74 kmpl,796 CC,5,Others,5 Speed,FWD,Kolkata
8366,0,Petrol,Sedan,Automatic,3,Mercedes-Benz,Mercedes-Benz C-Class,2011,â‚¹ 5.50 Lakh,Third Party insurance,"50,000 Kms",11.74 kmpl,1796 CC,5,Others,7 Speed,RWD,Kolkata
8367,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Ritz,2012,â‚¹ 1.40 Lakh,Third Party insurance,"40,000 Kms",18.5 kmpl,1197 CC,5,Others,5 Speed,FWD,Kolkata
8368,0,Diesel,SUV,Manual,2,Renault,Renault Duster,2017,â‚¹ 5 Lakh,Third Party insurance,"1,20,000 Kms",19.72 kmpl,1461 CC,5,Others,6 Speed,AWD,Kolkata

In [315]:
# change dataframe to csv
combined_df.to_csv('Total_cars_data.csv',index=False)
data = pd.read_csv('Total_cars_data.csv')
data

,it,ft,bt,transmission,ownerNo,oem,model,modelYear,price,Insurance Validity,Kms Driven,Mileage,Engine,Seats_1,Color,Gear Box,Drive Type,City
0,0,Petrol,Hatchback,Manual,3,Maruti,Maruti Celerio,2015,â‚¹ 4 Lakh,Third Party insurance,"1,20,000 Kms",23.1 kmpl,998 CC,5.0,White,5 Speed,FWD,Bangalore
1,0,Petrol,SUV,Manual,2,Ford,Ford Ecosport,2018,â‚¹ 8.11 Lakh,Comprehensive,"32,706 Kms",17 kmpl,1497 CC,5.0,White,5 Speed,FWD,Bangalore
2,0,Petrol,Hatchback,Manual,1,Tata,Tata Tiago,2018,â‚¹ 5.85 Lakh,Comprehensive,"11,949 Kms",23.84 kmpl,1199 CC,5.0,Red,5 Speed,FWD,Bangalore
3,0,Petrol,Sedan,Manual,1,Hyundai,Hyundai Xcent,2014,â‚¹ 4.62 Lakh,Comprehensive,"17,794 Kms",19.1 kmpl,1197 CC,5.0,Others,5 Speed,FWD,Bangalore
4,0,Diesel,SUV,Manual,1,Maruti,Maruti SX4 S Cross,2015,â‚¹ 7.90 Lakh,Third Party insurance,"60,000 Kms",23.65 kmpl,1248 CC,5.0,Gray,5 Speed,FWD,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Celerio,2022,â‚¹ 5.10 Lakh,Third Party insurance,"10,000 Kms",25.24 kmpl,998 CC,5.0,Others,5-Speed,NaN,Kolkata
8365,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Alto 800,2014,â‚¹ 1.80 Lakh,Third Party insurance,"1,20,000 Kms",22.74 kmpl,796 CC,5.0,Others,5 Speed,FWD,Kolkata
8366,0,Petrol,Sedan,Automatic,3,Mercedes-Benz,Mercedes-Benz C-Class,2011,â‚¹ 5.50 Lakh,Third Party insurance,"50,000 Kms",11.74 kmpl,1796 CC,5.0,Others,7 Speed,RWD,Kolkata
8367,0,Petrol,Hatchback,Manual,1,Maruti,Maruti Ritz,2012,â‚¹ 1.40 Lakh,Third Party insurance,"40,000 Kms",18.5 kmpl,1197 CC,5.0,Others,5 Speed,FWD,Kolkata
8368,0,Diesel,SUV,Manual,2,Renault,Renault Duster,2017,â‚¹ 5 Lakh,Third Party insurance,"1,20,000 Kms",19.72 kmpl,1461 CC,5.0,Others,6 Speed,AWD,Kolkata